// Dividend history, income aggregation, forward estimate and calendar.
// Source: Yahoo public chart endpoint dividend events.
import YahooFinance from "yahoo-finance2";
const yf:any=new (YahooFinance as any)({suppressNotices:["yahooSurvey","ripHistorical"]});
export interface DividendEvent{date:string;amount:number}
export interface DividendPeriod{period:string;amount:number;perShare?:number}
export interface HoldingDividend{ticker:string;shares:number;ttmPerShare:number;lastAmount:number|null;lastExDate:string|null;frequency:number|null;frequencyLabel:string;estAnnualIncome:number;currentYield:number|null;yieldOnCost:number|null;nextExDate:string|null;nextPayDate:string|null;estAnnualIncomeNet:number;events:DividendEvent[]}
export interface DividendSummary{holdings:HoldingDividend[];byYear:DividendPeriod[];byMonth:DividendPeriod[];estAnnualIncome:number;estMonthlyAverage:number;trailingIncome12m:number;portfolioYield:number|null;yieldOnCost:number|null;withholdingPct:number;estAnnualIncomeNet:number;estMonthlyAverageNet:number;trailingIncome12mNet:number;portfolioYieldNet:number|null;yieldOnCostNet:number|null;byYearNet:DividendPeriod[];byMonthNet:DividendPeriod[];calendar:{ticker:string;exDate:string;payDate:string;estAmountPerShare:number;estPayout:number;estPayoutNet:number;projected:boolean}[]}
const round2=(x:number)=>Math.round(x*100)/100,iso=(d:Date)=>d.toISOString().slice(0,10);
function normalizeDividendRows(raw:unknown):any[]{if(Array.isArray(raw))return raw;if(raw&&typeof raw==="object")return Object.values(raw as Record<string,unknown>);return[]}
export async function fetchDividends(ticker:string,years=5):Promise<{events:DividendEvent[];price:number|null}>{const period1=new Date(Date.now()-years*365*86400000);const res=await yf.chart(ticker,{period1,interval:"1d",events:"div"});const events=normalizeDividendRows(res?.events?.dividends).map((d:any)=>{const raw=d?.date??d?.datetime??d?.timestamp,p=raw instanceof Date?raw:new Date(typeof raw==="number"&&raw<1e12?raw*1000:raw);return{date:Number.isFinite(p.getTime())?iso(p):"",amount:Number(d?.amount??d?.dividend??d?.value)||0}}).filter((d:any)=>d.date&&d.amount>0).sort((a:any,b:any)=>a.date.localeCompare(b.date));const qr=res?.quotes,qs:any[]=Array.isArray(qr)?qr:qr&&typeof qr==="object"?Object.values(qr):[];const last=[...qs].reverse().find(q=>q?.close!=null)?.close??null;return{events,price:last!=null?Number(last):null}}
export function inferFrequency(events:DividendEvent[]):{perYear:number|null;label:string}{if(events.length<2)return{perYear:null,label:"unknown"};const recent=events.slice(-9),gaps:number[]=[];for(let i=1;i<recent.length;i++){const g=(new Date(recent[i].date).getTime()-new Date(recent[i-1].date).getTime())/86400000;if(g>10)gaps.push(g)}if(!gaps.length)return{perYear:null,label:"unknown"};gaps.sort((a,b)=>a-b);const m=gaps[Math.floor(gaps.length/2)];if(m<=45)return{perYear:12,label:"Monthly"};if(m<=135)return{perYear:4,label:"Quarterly"};if(m<=250)return{perYear:2,label:"Semi-annual"};return{perYear:1,label:"Annual"}}
export const WITHHOLDING_PCT=15;const net=(gross:number,pct=WITHHOLDING_PCT)=>gross*(1-pct/100);function toWeekday(d:Date){const day=d.getUTCDay();if(day===6)return new Date(d.getTime()+2*86400000);if(day===0)return new Date(d.getTime()+86400000);return d}
export function projectNextExDate(events:DividendEvent[],perYear:number|null):string|null{if(!events.length||!perYear)return null;const last=new Date(events.at(-1)!.date+"T00:00:00Z"),now=new Date(),days=events.slice(-8).map(e=>new Date(e.date+"T00:00:00Z").getUTCDate()).sort((a,b)=>a-b),target=days.length?days[Math.floor(days.length/2)]:last.getUTCDate(),step=Math.max(1,Math.round(12/perYear));let c=new Date(Date.UTC(last.getUTCFullYear(),last.getUTCMonth()+step,target)),guard=0;while(c.getTime()<now.getTime()&&guard++<24)c=new Date(Date.UTC(c.getUTCFullYear(),c.getUTCMonth()+step,target));if(c.getUTCDate()!==target)c=new Date(Date.UTC(c.getUTCFullYear(),c.getUTCMonth(),0));return iso(toWeekday(c))}
export function payLagDays(label:string){switch(label){case"Monthly":return 7;case"Quarterly":return 21;case"Semi-annual":return 30;default:return 30}}
export function projectPayDate(exDate:string,label:string){return iso(toWeekday(new Date(new Date(exDate+"T00:00:00Z").getTime()+payLagDays(label)*86400000)))}
export interface HoldingInput{ticker:string;shares:number;avg_cost:number;closed_at?:string|null}
function activeOnly(holdings:HoldingInput[]):HoldingInput[]{const byTicker=new Map<string,HoldingInput>();for(const raw of holdings){const ticker=String(raw.ticker??"").trim().toUpperCase(),shares=Number(raw.shares),cost=Number(raw.avg_cost);if(!ticker||raw.closed_at||!Number.isFinite(shares)||shares<=0)continue;const prior=byTicker.get(ticker);if(!prior){byTicker.set(ticker,{ticker,shares,avg_cost:Number.isFinite(cost)?cost:0});continue}const total=prior.shares+shares;prior.avg_cost=total>0?((prior.avg_cost*prior.shares)+((Number.isFinite(cost)?cost:0)*shares))/total:prior.avg_cost;prior.shares=total}return[...byTicker.values()]}
export async function buildDividendSummary(holdings:HoldingInput[],prices:Record<string,number|null>={}):Promise<DividendSummary>{
  // Last-line defense: callers may accidentally send historical/closed rows.
  // Dividend income describes the current book only, so zero-share and closed
  // positions never reach any TTM, forward-income, yield or calendar calculation.
  const active=activeOnly(holdings),results:HoldingDividend[]=[],yearMap=new Map<string,number>(),monthMap=new Map<string,number>();
  for(const h of active){let events:DividendEvent[]=[],price=prices[h.ticker]??null;try{const f=await fetchDividends(h.ticker,5);events=f.events;price=price??f.price}catch{}const cutoff=iso(new Date(Date.now()-365*86400000)),ttm=events.filter(e=>e.date>=cutoff).reduce((s,e)=>s+e.amount,0),{perYear,label}=inferFrequency(events),last=events.at(-1)??null,estPerShare=perYear&&last?last.amount*perYear:ttm,estAnnual=round2(estPerShare*h.shares),nextEx=projectNextExDate(events,perYear);for(const e of events){const income=e.amount*h.shares,y=e.date.slice(0,4),m=e.date.slice(0,7);yearMap.set(y,(yearMap.get(y)??0)+income);monthMap.set(m,(monthMap.get(m)??0)+income)}results.push({ticker:h.ticker,shares:h.shares,ttmPerShare:round2(ttm),lastAmount:last?.amount??null,lastExDate:last?.date??null,frequency:perYear,frequencyLabel:events.length?label:"No dividend",estAnnualIncome:estAnnual,currentYield:price&&price>0&&estPerShare>0?round2(estPerShare/price*100):null,yieldOnCost:h.avg_cost>0&&estPerShare>0?round2(estPerShare/h.avg_cost*100):null,estAnnualIncomeNet:round2(net(estAnnual)),nextExDate:nextEx,nextPayDate:nextEx?projectPayDate(nextEx,events.length?label:"Quarterly"):null,events})}
  const byYear=[...yearMap.entries()].map(([period,amount])=>({period,amount:round2(amount)})).sort((a,b)=>b.period.localeCompare(a.period)).slice(0,6),months:DividendPeriod[]=[],now=new Date();for(let i=23;i>=0;i--){const d=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-i,1)),key=iso(d).slice(0,7);months.push({period:key,amount:round2(monthMap.get(key)??0)})}const estAnnualIncome=round2(results.reduce((s,r)=>s+r.estAnnualIncome,0)),cutoff12=iso(new Date(Date.now()-365*86400000)).slice(0,7),trailingIncome12m=round2(months.filter(m=>m.period>=cutoff12).reduce((s,m)=>s+m.amount,0));let marketValue=0,costBasis=0;for(const h of active){const p=prices[h.ticker]??null;if(p!=null&&p>0)marketValue+=p*h.shares;costBasis+=h.avg_cost*h.shares}const byYearNet=byYear.map(x=>({...x,amount:round2(net(x.amount))})),byMonthNet=months.map(x=>({...x,amount:round2(net(x.amount))})),calendar=results.filter(r=>r.nextExDate&&r.lastAmount!=null&&r.shares>0).map(r=>({ticker:r.ticker,exDate:r.nextExDate!,payDate:r.nextPayDate!,estAmountPerShare:r.lastAmount!,estPayout:round2(r.lastAmount!*r.shares),estPayoutNet:round2(net(r.lastAmount!*r.shares)),projected:true})).sort((a,b)=>a.exDate.localeCompare(b.exDate));return{holdings:results,byYear,byMonth:months,estAnnualIncome,estMonthlyAverage:round2(estAnnualIncome/12),trailingIncome12m,portfolioYield:marketValue>0?round2(estAnnualIncome/marketValue*100):null,yieldOnCost:costBasis>0?round2(estAnnualIncome/costBasis*100):null,withholdingPct:WITHHOLDING_PCT,estAnnualIncomeNet:round2(net(estAnnualIncome)),estMonthlyAverageNet:round2(net(estAnnualIncome)/12),trailingIncome12mNet:round2(net(trailingIncome12m)),portfolioYieldNet:marketValue>0?round2(net(estAnnualIncome)/marketValue*100):null,yieldOnCostNet:costBasis>0?round2(net(estAnnualIncome)/costBasis*100):null,byYearNet,byMonthNet,calendar}
}
