// Sentinel Investment Team — Intelligence Framework V5
// Shared analytical intelligence for Research, Alpha Scan, Dividend, Thematic and Portfolio.
// Each desk must state evidence, falsification and an actionable output. Missing data is uncertainty, never zero.

import type { Candle, Financials } from "../types";
import { ema, sma, rsi } from "../indicators";

export type DeskId = "cio"|"data"|"macro"|"fundamental"|"momentum"|"income"|"valuation"|"catalyst"|"risk"|"portfolio";
export type CommitteeDecision = "APPROVE"|"WATCH"|"REJECT";
export interface DeskSpec { id:DeskId; name:string; role:string; mission:string; questions:string[]; falsification:string[]; output:string[]; }

export const SENTINEL_TEAM: DeskSpec[] = [
 {id:"cio",name:"James Hartwell",role:"CIO / Committee Chair",mission:"Integrate independent evidence into the best portfolio-level use of risk budget.",questions:["What must be true?","Is this the best marginal use of capital?","What changes the decision?"],falsification:["untestable thesis","poor asymmetry","portfolio fit failure"],output:["APPROVE/WATCH/REJECT","conviction","size multiplier","review trigger"]},
 {id:"data",name:"Nina Okonkwo",role:"Data Integrity & Forensics",mission:"Separate verified facts from estimates, stale observations and unavailable inputs before scoring.",questions:["Is it current?","Is it comparable?","Is missing data being mistaken for zero?"],falsification:["stale market data","insufficient history","contradictory fields"],output:["coverage","warnings","verified fact set"]},
 {id:"macro",name:"Daniel Cho",role:"Macro / Regime Strategist",mission:"Identify whether the tape rewards beta, quality, income or cash using measurable regime evidence.",questions:["What regime?","Which risk profiles are paid?","Is leadership broadening?"],falsification:["trend break","volatility shock","leadership reversal"],output:["regime","deployment fraction","allowed risk"]},
 {id:"fundamental",name:"Sofia Reyes",role:"Fundamental / Quality Analyst",mission:"Underwrite durability from five-year and four-quarter evidence, cash conversion, margins and balance sheet.",questions:["Is growth durable?","Are margins improving?","Does cash validate earnings?"],falsification:["unexplained deceleration","margin collapse","FCF divergence","leverage deterioration"],output:["quality score","growth durability","fundamental risks"]},
 {id:"momentum",name:"Maya Chen",role:"Momentum / Technical Intelligence",mission:"Find genuine acceleration with relative strength, participation and structure while penalizing late entries.",questions:["Is it leading SPY?","Does volume confirm?","Is reward left after the move?"],falsification:["RS rollover","failed breakout","50D trend loss"],output:["momentum score","entry state","invalidation","chase risk"]},
 {id:"income",name:"Lena Müller",role:"Dividend / Income Quality",mission:"Distinguish sustainable distributable cash flow from headline yield and estimate dividend growth capacity.",questions:["Is payout cash-funded?","Can it grow?","Is yield signaling impairment?"],falsification:["FCF undercoverage","debt-funded payout","structural earnings decline"],output:["income quality","coverage","growth capacity","cut risk"]},
 {id:"valuation",name:"Thomas Eriksson",role:"Valuation / Scenario Analyst",mission:"Value ranges rather than point estimates and expose the assumptions that drive DCF and multiples.",questions:["What is priced in?","What drives value most?","Is there margin of safety?"],falsification:["heroic terminal assumptions","unreliable cash base","price above bull economics"],output:["bear/base/bull","fair-value range","sensitivity"]},
 {id:"catalyst",name:"Aisha Fontaine",role:"Catalyst / Thesis Intelligence",mission:"Map events that can change estimates, positioning or narrative; distinguish a catalyst from a story.",questions:["What changes consensus?","When?","Is it priced?"],falsification:["undated narrative","immaterial event","fully priced consensus"],output:["catalyst map","horizon","impact","event risk"]},
 {id:"risk",name:"Miriam Osei",role:"Chief Risk Officer",mission:"Independent veto for permanent-loss, liquidity, concentration, event and thesis-break risk.",questions:["How do we lose permanently?","What is correlated?","Where is invalidation?"],falsification:["undefined downside","policy breach","uncompensated concentration","poor data"],output:["hard blocks","risk score","size cap","invalidation"]},
 {id:"portfolio",name:"Kai Tanaka",role:"Portfolio Construction",mission:"Convert conviction into diversified weights based on marginal portfolio contribution, not rank alone.",questions:["What does this add?","Does it duplicate a bet?","What weight fits risk?"],falsification:["concentration breach","theme duplication","risk budget exhausted"],output:["target weight","ADD/TRIM/KEEP/EXIT","rebalance priority"]},
];

export interface TimeframeRead { timeframe:"Daily"|"Weekly"; trend:"Up"|"Down"|"Sideways"; priceVsMa:string; rsi:number|null; detail:string; }
export interface MtfResult { reads:TimeframeRead[]; aligned:boolean; verdict:string; }
export function toWeekly(candles:Candle[]):Candle[]{ const out:Candle[]=[];let b:Candle[]=[];let wk="";const key=(d:string)=>{const x=new Date(d+"T00:00:00Z"),day=x.getUTCDay();return new Date(x.getTime()-((day+6)%7)*86400000).toISOString().slice(0,10)};const flush=()=>{if(!b.length)return;out.push({date:b.at(-1)!.date,open:b[0].open,high:Math.max(...b.map(x=>x.high)),low:Math.min(...b.map(x=>x.low)),close:b.at(-1)!.close,volume:b.reduce((s,x)=>s+x.volume,0)});b=[]};for(const c of candles){const k=key(c.date);if(k!==wk){flush();wk=k}b.push(c)}flush();return out;}
function tf(c:Candle[],timeframe:"Daily"|"Weekly",fast:number,slow:number):TimeframeRead|null{if(c.length<slow+5)return null;const closes=c.map(x=>x.close),p=closes.at(-1)!,f=ema(closes,fast),s=sma(closes,slow),rr=rsi(closes,14);if(f==null||s==null)return null;const trend=p>f&&f>s?"Up":p<f&&f<s?"Down":"Sideways";return{timeframe,trend,priceVsMa:`price ${p>s?"above":"below"} the ${slow}-period average`,rsi:rr==null?null:Math.round(rr*10)/10,detail:`${timeframe}: ${trend.toLowerCase()} — ${fast}-EMA ${f>s?"above":"below"} ${slow}-SMA, RSI ${rr?.toFixed(1)??"n/a"}`}}
export function multiTimeframe(d:Candle[]):MtfResult{const reads:TimeframeRead[]=[];const a=tf(d,"Daily",20,50),w=tf(toWeekly(d),"Weekly",10,30);if(a)reads.push(a);if(w)reads.push(w);if(reads.length<2)return{reads,aligned:false,verdict:"Not enough history to confirm across timeframes."};const aligned=a!.trend===w!.trend;return{reads,aligned,verdict:aligned?`Daily and weekly agree (${a!.trend.toLowerCase()}).`:`Daily is ${a!.trend.toLowerCase()} while weekly is ${w!.trend.toLowerCase()} — reduce size or wait for confirmation.`}}

export interface QualityFlag {label:string;value:string;verdict:"good"|"watch"|"poor"|"unknown";note:string}
export function earningsQuality(fin:Financials){const inc=fin.income,cf=fin.cashflow,bal=fin.balance,flags:QualityFlag[]=[];const n=(v:any)=>typeof v==="number"&&Number.isFinite(v)?v:0;if(!inc.length||!cf.length)return{flags:[{label:"Earnings quality",value:"n/a",verdict:"unknown" as const,note:"Statements unavailable"}],score:null,summary:"Not gradable without statements."};const ni=n(inc[0].netIncome),ocf=n(cf[0].operatingCashflow),rev=n(inc[0].totalRevenue),capex=Math.abs(n(cf[0].capitalExpenditures));if(ni>0&&ocf!==0){const x=ocf/ni;flags.push({label:"Cash conversion",value:`${x.toFixed(2)}×`,verdict:x>=1.1?"good":x>=.8?"watch":"poor",note:x>=1.1?"Cash validates earnings.":"Review accrual quality."})}if(rev>0){const x=(ocf-capex)/rev*100;flags.push({label:"FCF margin",value:`${x.toFixed(1)}%`,verdict:x>=15?"good":x>=5?"watch":"poor",note:x>=15?"Strong self-funding.":"Cash generation needs scrutiny."})}const assets=n(bal[0]?.totalAssets);if(assets>0&&ni!==0){const x=(ni-ocf)/assets*100;flags.push({label:"Accrual ratio",value:`${x.toFixed(1)}%`,verdict:x<=5?"good":x<=10?"watch":"poor",note:x<=5?"Earnings are cash-backed.":"Non-cash earnings are elevated."})}const equity=n(bal[0]?.totalShareholderEquity),debt=n(bal[0]?.longTermDebt)+n(bal[0]?.shortTermDebt);if(equity>0){const x=debt/equity;flags.push({label:"Debt/equity",value:x.toFixed(2),verdict:x<=1?"good":x<=2?"watch":"poor",note:x<=1?"Conservative financing.":"Leverage is meaningful."})}const graded=flags.filter(x=>x.verdict!=="unknown");const score=graded.length?Math.round(graded.reduce((s,x)=>s+(x.verdict==="good"?1:x.verdict==="watch"?.5:0),0)/graded.length*100):null;return{flags,score,summary:score==null?"Not gradable.":`Earnings quality ${score}/100 from cash conversion, FCF, accrual and leverage evidence.`}}

export interface Conflict {between:string;issue:string;implication:string}
export interface ConvictionInput {momentumScore:number;hasHardBlock:boolean;sampDirection:number|null;sampAcceleration:number|null;mtfAligned:boolean|null;qualityScore:number|null;valuationUpsidePct:number|null;regimeScore:number;gatesCleared:boolean}
export interface ConvictionResult {score:number;label:"High"|"Moderate"|"Low"|"Conflicted";agreements:string[];conflicts:Conflict[];note:string}
export function buildConviction(i:ConvictionInput):ConvictionResult{const agreements:string[]=[],conflicts:Conflict[]=[];const mom=i.momentumScore>=58,sbull=(i.sampDirection??0)>8,sbear=(i.sampDirection??0)<-8,cheap=(i.valuationUpsidePct??0)>=15,rich=(i.valuationUpsidePct??0)<=-10,q=(i.qualityScore??0)>=60;if(mom&&sbull)agreements.push("Momentum and pressure agree bullish.");if(mom&&i.mtfAligned)agreements.push("Daily signal is weekly-confirmed.");if(cheap&&q)agreements.push("Valuation upside is backed by quality.");if(mom&&sbear)conflicts.push({between:"Momentum vs pressure",issue:"Price score is not confirmed by pressure.",implication:"WATCH until confirmation."});if(mom&&i.mtfAligned===false)conflicts.push({between:"Daily vs weekly",issue:"Timeframes disagree.",implication:"Reduce size or wait."});if(mom&&rich)conflicts.push({between:"Momentum vs valuation",issue:"Trend is strong but valuation offers no support.",implication:"Trading sleeve only."});if(i.regimeScore<40&&mom)conflicts.push({between:"Macro vs momentum",issue:"Bullish single name in weak tape.",implication:"Restrict deployment."});let score=Math.min(35,i.momentumScore*.35)+(i.sampDirection==null?0:Math.max(0,Math.min(20,(i.sampDirection+50)/5)))+(i.mtfAligned?12:0)+(i.qualityScore==null?0:i.qualityScore*.15)+(i.valuationUpsidePct==null?0:Math.max(0,Math.min(10,i.valuationUpsidePct/3)))+i.regimeScore*.08+(i.gatesCleared?5:0);if(i.hasHardBlock)score*=.4;score=Math.max(0,Math.min(100,Math.round(score)));const label=conflicts.length>=2?"Conflicted":score>=70?"High":score>=45?"Moderate":"Low";return{score,label,agreements,conflicts,note:label==="Conflicted"?"Resolve desk disagreement before committing capital.":label==="High"?"Evidence is broadly aligned.":label==="Moderate"?"Workable case, size conservatively.":"Evidence does not support a position."}}

export interface CommitteeInput {dataQuality?:number|null;regimeScore?:number|null;qualityScore?:number|null;momentumScore?:number|null;incomeScore?:number|null;valuationUpsidePct?:number|null;catalystScore?:number|null;riskScore?:number|null;portfolioFitScore?:number|null;hardBlocks?:string[];thesis?:string|null;evidenceCount?:number}
export interface SentinelDecision {decision:CommitteeDecision;conviction:number;confidence:"LOW"|"MEDIUM"|"HIGH";deskScores:Record<string,number|null>;reasons:string[];dissent:string[];sizeMultiplier:number}
const ok=(x:number|null|undefined):x is number=>typeof x==="number"&&Number.isFinite(x);
export function sentinelCommittee(i:CommitteeInput):SentinelDecision{const blocks=i.hardBlocks??[],scores:Record<string,number|null>={data:i.dataQuality??null,macro:i.regimeScore??null,fundamental:i.qualityScore??null,momentum:i.momentumScore??null,income:i.incomeScore??null,valuation:ok(i.valuationUpsidePct)?Math.max(0,Math.min(100,50+i.valuationUpsidePct)):null,catalyst:i.catalystScore??null,risk:i.riskScore??null,portfolio:i.portfolioFitScore??null},w:Record<string,number>={data:.10,macro:.10,fundamental:.17,momentum:.12,income:.08,valuation:.12,catalyst:.08,risk:.13,portfolio:.10};let num=0,den=0;for(const [k,v] of Object.entries(scores))if(ok(v)){num+=v*w[k];den+=w[k]}let conviction=den?Math.round(num/den):0;if(!i.thesis)conviction=Math.max(0,conviction-8);if(blocks.length)conviction=Math.min(conviction,49);const coverage=Object.values(scores).filter(ok).length/Object.keys(scores).length,confidence=coverage>=.78&&(i.evidenceCount??0)>=5?"HIGH":coverage>=.5?"MEDIUM":"LOW",decision:CommitteeDecision=blocks.length?"REJECT":conviction>=72&&confidence!=="LOW"?"APPROVE":conviction>=55?"WATCH":"REJECT",reasons:string[]=[],dissent:string[]=[];for(const [k,v] of Object.entries(scores)){if(ok(v)&&v>=70)reasons.push(`${k} ${Math.round(v)}/100 supports the case`);if(ok(v)&&v<45)dissent.push(`${k} ${Math.round(v)}/100 is material dissent`)}blocks.forEach(b=>dissent.push(`Hard block: ${b}`));return{decision,conviction,confidence,deskScores:scores,reasons:reasons.slice(0,4),dissent:dissent.slice(0,5),sizeMultiplier:decision==="APPROVE"?Math.max(.5,Math.min(1.25,conviction/80)):decision==="WATCH"?.35:0}}
