// Sentinel Global Fund — Momentum Scoring System v3.0
//
// A faithful, deterministic implementation of the fund's published scoring
// model. Every point is computed from real price/volume/fundamental data —
// nothing is generated by a language model, so the same inputs always produce
// the same score and every number can be traced to its rule.
//
// Point allocation (100 total):
//   3A Momentum        35  RSI 12 · MACD 13 · ADX 5 · RS 5
//   3B Volume & Flow   25  OBV+MFI 15 · Volume 10
//   3C Structure       15  MA stack 10 · Pattern 5
//   3D High-Beta       10  ATR% 5 · Beta×DollarVol 5
//   3E Trend Maturity   8  BB position 5 · Bars since 20-EMA cross 3
//   3F Volatility       7  ATR expansion 4 · BB squeeze 3
//
// The source document also lists Sector Leadership and Catalyst as "3E ext"
// and "3F ext" worth 15 combined. Since the signal thresholds are stated on a
// /100 scale, those are computed here as a SEPARATE catalyst assessment that
// adjusts the signal through the documented rules (negative catalyst −3,
// earnings within 5 days → REJECT) rather than inflating the base total.

import type { Candle } from "../types";
import {
  rsi, macd, ema, sma, adx, obv, mfi, bollinger,
  barsSinceEmaCross, dollarVolume, atrPercent, atrExpanding,
  avgVolume, relativeStrength, atr,
} from "../indicators";

export type DataFlag = "V" | "E" | "U";

export interface ScoreLine {
  /** Phase id, e.g. "3A". */
  phase: string;
  label: string;
  points: number;
  max: number;
  detail: string;
  /** Rule #5 — data integrity flag. [U] always scores zero. */
  flag: DataFlag;
}

export interface HardBlock {
  code: string;
  reason: string;
}

export type Signal = "STRONG BUY" | "BUY" | "WATCH" | "SOFT-BLOCK WATCH" | "REJECT";

export interface MomentumScoreV3 {
  total: number;
  lines: ScoreLine[];
  phaseTotals: Record<string, { points: number; max: number }>;
  hardBlocks: HardBlock[];
  signal: Signal;
  signalReason: string;
  /** Share of inputs that were verifiable — Gate 7 uses this. */
  dataQualityScore: number;
  unavailable: string[];
}

const clamp = (x: number, lo: number, hi: number) => Math.max(lo, Math.min(hi, x));

export interface ScoringInput {
  candles: Candle[];
  benchmark: Candle[];
  beta: number | null;
  /** Days until the next earnings report, when known. */
  daysToEarnings?: number | null;
  /** Aisha's catalyst score 0-25, when a catalyst has been assessed. */
  catalystScore?: number | null;
  catalystNegative?: boolean;
  /** True when the name sits in a leading sector. */
  sectorLeading?: boolean | null;
}

export function scoreMomentumV3(input: ScoringInput): MomentumScoreV3 {
  const { candles, benchmark } = input;
  const lines: ScoreLine[] = [];
  const blocks: HardBlock[] = [];
  const unavailable: string[] = [];

  const push = (
    phase: string, label: string, points: number, max: number, detail: string, flag: DataFlag
  ) => {
    // Rule #5 — unavailable data scores zero, never a guess.
    lines.push({ phase, label, points: flag === "U" ? 0 : points, max, detail, flag });
    if (flag === "U") unavailable.push(`${phase} ${label}`);
  };

  const closes = candles.map((c) => c.close);
  const price = closes[closes.length - 1] ?? 0;

  // ── Phase 3A — Momentum (35) ──────────────────────────────────────
  const r = rsi(closes, 14);
  const ema10 = ema(closes, 10);
  const ema20v = ema(closes, 20);
  const sma50 = sma(closes, 50);
  const sma200 = sma(closes, 200);
  const maConfirm = ema20v != null && price > ema20v;

  if (r == null) {
    push("3A", "RSI(14)", 0, 12, "insufficient history", "U");
  } else if (r >= 55 && r <= 78) {
    push("3A", "RSI(14)", 12, 12, `${r.toFixed(1)} — Tier 1 power zone (55-78)`, "V");
  } else if (r >= 45 && r <= 54 && maConfirm) {
    push("3A", "RSI(14)", 8, 12, `${r.toFixed(1)} — Tier 2 with MA confirm`, "V");
  } else {
    push("3A", "RSI(14)", 0, 12, `${r.toFixed(1)} — outside scoring band`, "V");
    if (r < 45 && !maConfirm) {
      blocks.push({ code: "RSI_WEAK", reason: `RSI ${r.toFixed(1)} < 45 with no MA confirmation` });
    }
  }

  const m = macd(closes);
  if (m == null) {
    push("3A", "MACD", 0, 13, "insufficient history", "U");
  } else {
    const prevHistSeries = macd(closes.slice(0, -3));
    const expanding = prevHistSeries != null && Math.abs(m.hist) > Math.abs(prevHistSeries.hist);
    if (m.macd > 0 && m.hist > 0 && expanding) {
      push("3A", "MACD", 13, 13, `line ${m.macd.toFixed(2)} > 0, histogram expanding`, "V");
    } else if (m.macd > 0 && m.hist > 0) {
      push("3A", "MACD", 8, 13, `line ${m.macd.toFixed(2)} > 0, histogram not expanding`, "V");
    } else if (m.macd < 0 && m.hist > 0) {
      push("3A", "MACD", 5, 13, `negative but reversing (histogram ${m.hist.toFixed(2)})`, "V");
    } else {
      push("3A", "MACD", 0, 13, `line ${m.macd.toFixed(2)}, histogram ${m.hist.toFixed(2)} — flat or diverging`, "V");
    }
  }

  const adxVal = adx(candles, 14);
  if (adxVal == null) {
    push("3A", "ADX(14)", 0, 5, "insufficient history", "U");
  } else if (adxVal > 25) {
    push("3A", "ADX(14)", 5, 5, `${adxVal.toFixed(1)} — trending`, "V");
  } else if (adxVal >= 20) {
    push("3A", "ADX(14)", 3, 5, `${adxVal.toFixed(1)} — developing trend`, "V");
  } else {
    push("3A", "ADX(14)", 0, 5, `${adxVal.toFixed(1)} — no trend`, "V");
    blocks.push({ code: "ADX_LOW", reason: `ADX ${adxVal.toFixed(1)} < 20 — no established trend` });
  }

  const rs = relativeStrength(candles, benchmark, 20);
  if (rs == null) {
    push("3A", "RS vs SPY (20D)", 0, 5, "benchmark unavailable", "U");
  } else if (rs > 1) {
    push("3A", "RS vs SPY (20D)", 5, 5, `${rs.toFixed(3)} — outperforming`, "V");
  } else {
    push("3A", "RS vs SPY (20D)", 0, 5, `${rs.toFixed(3)} — lagging benchmark`, "V");
  }

  // ── Phase 3B — Volume & Flow (25) ─────────────────────────────────
  const o = obv(candles);
  const mf = mfi(candles, 14);
  const priceRising = closes.length > 20 && price > closes[closes.length - 21];
  if (o == null || mf == null) {
    push("3B", "OBV + MFI", 0, 15, "insufficient history", "U");
  } else if (o.rising && mf > 50) {
    push("3B", "OBV + MFI", 15, 15, `OBV rising (${o.slopePct.toFixed(1)}%), MFI ${mf.toFixed(1)}`, "V");
  } else if (!o.rising && priceRising) {
    push("3B", "OBV + MFI", 0, 15, `OBV declining while price rises — distribution (MFI ${mf.toFixed(1)})`, "V");
    blocks.push({ code: "OBV_DISTRIBUTION", reason: "OBV declining while price advances — institutional distribution" });
  } else {
    push("3B", "OBV + MFI", 6, 15, `OBV ${o.rising ? "rising" : "flat/declining"}, MFI ${mf.toFixed(1)} — no confirmation`, "V");
  }

  const v5 = avgVolume(candles, 5);
  const v20 = avgVolume(candles, 20);
  if (v5 == null || v20 == null || v20 === 0) {
    push("3B", "Volume expansion", 0, 10, "insufficient history", "U");
  } else {
    const ratio = v5 / v20;
    if (ratio > 1.5) push("3B", "Volume expansion", 10, 10, `5d/20d ${ratio.toFixed(2)}× — accumulation`, "V");
    else if (ratio >= 1) push("3B", "Volume expansion", 6, 10, `5d/20d ${ratio.toFixed(2)}×`, "V");
    else push("3B", "Volume expansion", 0, 10, `5d/20d ${ratio.toFixed(2)}× — below average`, "V");
  }

  // ── Phase 3C — Structure (15) ─────────────────────────────────────
  if (ema10 == null || ema20v == null || sma50 == null) {
    push("3C", "MA structure", 0, 10, "insufficient history", "U");
  } else if (price > ema10 && ema10 > ema20v && ema20v > sma50) {
    push("3C", "MA structure", 10, 10, "bullish stack: price > 10EMA > 20EMA > 50SMA", "V");
  } else if (sma200 != null && price > sma50 && price > sma200) {
    push("3C", "MA structure", 6, 10, "Tier 2 pullback — above 50SMA and 200SMA", "V");
  } else if (sma200 != null && price > sma200) {
    push("3C", "MA structure", 3, 10, "above 200SMA only", "V");
  } else {
    push("3C", "MA structure", 0, 10, "below key moving averages", "V");
  }

  if (sma200 == null) {
    unavailable.push("3C 200SMA");
  } else if (price < sma200) {
    blocks.push({ code: "BELOW_200SMA", reason: `Price ${price.toFixed(2)} below 200SMA ${sma200.toFixed(2)}` });
  }

  const pattern = detectPattern(candles);
  push("3C", "Pattern", pattern.points, 5, pattern.label, pattern.points > 0 ? "V" : "E");

  // ── Phase 3D — High-Beta (10) ─────────────────────────────────────
  const atrPct = atrPercent(candles, 14);
  if (atrPct == null) {
    push("3D", "ATR %", 0, 5, "insufficient history", "U");
  } else if (atrPct > 3) {
    push("3D", "ATR %", 5, 5, `${atrPct.toFixed(2)}% — high volatility`, "V");
  } else if (atrPct >= 2) {
    push("3D", "ATR %", 3, 5, `${atrPct.toFixed(2)}%`, "V");
  } else {
    push("3D", "ATR %", 0, 5, `${atrPct.toFixed(2)}% — low volatility`, "V");
  }

  const dv = dollarVolume(candles, 20);
  const beta = input.beta;
  if (dv == null) {
    push("3D", "Beta × liquidity", 0, 5, "insufficient history", "U");
  } else {
    const dvM = dv / 1e6;
    if (beta != null && beta > 1.3 && dv > 50e6) {
      push("3D", "Beta × liquidity", 5, 5, `beta ${beta.toFixed(2)}, $${dvM.toFixed(0)}M/day`, "V");
    } else if (beta != null && beta > 1.0 && dv > 10e6) {
      push("3D", "Beta × liquidity", 3, 5, `beta ${beta.toFixed(2)}, $${dvM.toFixed(0)}M/day`, "V");
    } else {
      push("3D", "Beta × liquidity", 0, 5, `beta ${beta?.toFixed(2) ?? "n/a"}, $${dvM.toFixed(0)}M/day`, beta == null ? "E" : "V");
    }
    if (dv < 10e6) {
      blocks.push({ code: "ILLIQUID", reason: `Dollar volume $${dvM.toFixed(1)}M/day below the $10M floor` });
    }
  }

  // ── Phase 3E — Trend Maturity (8) ─────────────────────────────────
  const bb = bollinger(candles, 20, 2);
  if (bb == null) {
    push("3E", "BB position", 0, 5, "insufficient history", "U");
  } else if (bb.position >= 0.5 && bb.position <= 0.95) {
    push("3E", "BB position", 5, 5, `${(bb.position * 100).toFixed(0)}% of band — mid-to-upper`, "V");
  } else if (bb.position > 0.95) {
    push("3E", "BB position", 2, 5, `${(bb.position * 100).toFixed(0)}% — riding the upper band, extended`, "V");
  } else {
    push("3E", "BB position", 0, 5, `${(bb.position * 100).toFixed(0)}% — lower half`, "V");
  }

  const bars = barsSinceEmaCross(candles, 20);
  if (bars == null) {
    push("3E", "Bars since 20-EMA cross", 0, 3, "no recent cross — trend extended", "V");
  } else if (bars <= 5) {
    push("3E", "Bars since 20-EMA cross", 3, 3, `${bars} bars — fresh`, "V");
  } else if (bars <= 15) {
    push("3E", "Bars since 20-EMA cross", 2, 3, `${bars} bars`, "V");
  } else {
    push("3E", "Bars since 20-EMA cross", 0, 3, `${bars} bars — extended`, "V");
  }

  // ── Phase 3F — Volatility (7) ─────────────────────────────────────
  const ax = atrExpanding(candles, 14);
  if (ax == null) {
    push("3F", "ATR expansion", 0, 4, "insufficient history", "U");
  } else if (ax.above && ax.expanding) {
    push("3F", "ATR expansion", 4, 4, "ATR above average and expanding", "V");
  } else if (ax.above) {
    push("3F", "ATR expansion", 2, 4, "ATR above average", "V");
  } else {
    push("3F", "ATR expansion", 0, 4, "ATR at or below average", "V");
  }

  if (bb == null) {
    push("3F", "Bollinger state", 0, 3, "insufficient history", "U");
  } else if (bb.squeeze) {
    push("3F", "Bollinger state", 3, 3, `squeeze — bandwidth ${bb.bandwidth.toFixed(1)}%`, "V");
  } else {
    push("3F", "Bollinger state", 1, 3, `normal — bandwidth ${bb.bandwidth.toFixed(1)}%`, "V");
  }

  // ── Totals ────────────────────────────────────────────────────────
  const phaseTotals: Record<string, { points: number; max: number }> = {};
  for (const l of lines) {
    phaseTotals[l.phase] ??= { points: 0, max: 0 };
    phaseTotals[l.phase].points += l.points;
    phaseTotals[l.phase].max += l.max;
  }
  let total = lines.reduce((s, l) => s + l.points, 0);

  // Catalyst adjustment (documented rules only — no invented catalysts)
  if (input.catalystNegative) total -= 3;
  total = clamp(Math.round(total), 0, 100);

  // Earnings blackout — a hard reject in the rulebook
  if (input.daysToEarnings != null && input.daysToEarnings >= 0 && input.daysToEarnings <= 5) {
    blocks.push({ code: "EARNINGS_5D", reason: `Earnings in ${input.daysToEarnings} days — inside the 5-day blackout` });
  }

  const scored = lines.filter((l) => l.flag !== "U").length;
  const dataQualityScore = lines.length ? Math.round((scored / lines.length) * 100) : 0;

  const { signal, signalReason } = deriveSignal(total, blocks);

  return { total, lines, phaseTotals, hardBlocks: blocks, signal, signalReason, dataQualityScore, unavailable };
}

/** Signal thresholds, including Rule #1 (soft-block). */
export function deriveSignal(total: number, blocks: HardBlock[]): { signal: Signal; signalReason: string } {
  if (blocks.length >= 2) {
    return { signal: "REJECT", signalReason: `${blocks.length} hard blocks — REJECT is automatic` };
  }
  if (blocks.length === 1) {
    // Rule #1 — a single block with a score above 80 downgrades to WATCH
    if (total > 80) {
      return {
        signal: "SOFT-BLOCK WATCH",
        signalReason: `Rule #1 soft-block: score ${total} > 80 with one block (${blocks[0].code}) — WATCH, not REJECT`,
      };
    }
    return { signal: "REJECT", signalReason: `Hard block: ${blocks[0].reason}` };
  }
  if (total >= 75) return { signal: "STRONG BUY", signalReason: `Score ${total} ≥ 75 — full size` };
  if (total >= 58) return { signal: "BUY", signalReason: `Score ${total} in 58-74 — staggered entry` };
  if (total >= 42) return { signal: "WATCH", signalReason: `Score ${total} in 42-57 — await confirmation` };
  return { signal: "REJECT", signalReason: `Score ${total} < 42` };
}

/** Coarse base-pattern read from price action. */
function detectPattern(candles: Candle[]): { points: number; label: string } {
  if (candles.length < 40) return { points: 1, label: "unclear — insufficient history" };
  const recent = candles.slice(-30);
  const highs = recent.map((c) => c.high);
  const lows = recent.map((c) => c.low);
  const closes = recent.map((c) => c.close);
  const hi = Math.max(...highs);
  const lo = Math.min(...lows);
  const price = closes[closes.length - 1];
  const range = hi - lo;
  if (range <= 0 || hi <= 0) return { points: 1, label: "unclear" };

  // volatility contraction: recent half tighter than the earlier half
  const firstHalf = recent.slice(0, 15);
  const secondHalf = recent.slice(15);
  const spread = (arr: Candle[]) => Math.max(...arr.map((c) => c.high)) - Math.min(...arr.map((c) => c.low));
  const contracting = spread(secondHalf) < spread(firstHalf) * 0.7;
  const nearHigh = (price - lo) / range > 0.8;
  const tightBase = range / hi < 0.15;

  if (contracting && nearHigh) return { points: 5, label: "VCP / high-tight flag — contraction near highs" };
  if (tightBase && nearHigh) return { points: 5, label: "flat base near highs" };
  if (tightBase) return { points: 3, label: "base building" };
  if (nearHigh) return { points: 3, label: "trending near highs" };
  if ((price - lo) / range < 0.3) return { points: 0, label: "broken — price in lower third of range" };
  return { points: 1, label: "unclear structure" };
}

/** ATR-based stop, Rule #4. */
export function atrStop(candles: Candle[], entry: number, mult = 2): { stop: number; atr: number } | null {
  const a = atr(candles, 14);
  if (a == null || !entry) return null;
  return { stop: Math.round((entry - mult * a) * 100) / 100, atr: Math.round(a * 100) / 100 };
}
