"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { money, cls } from "./format";
import type { AppLang } from "../page";

type Entry = { id:string; entry_type:string; amount:number|string; currency:string; entry_date:string; ticker?:string|null; transaction_id?:string|null; dividend_id?:string|null; notes?:string|null };

export default function CashLedgerPanel({ lang, refreshKey }: { lang: AppLang; refreshKey: number }) {
  const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const [form,setForm]=useState({ entry_type:"DEPOSIT", amount:"", entry_date:new Date().toISOString().slice(0,10), notes:"" });
  const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{ setLoading(true); setError(null); try { const r=await fetch("/api/portfolio/cash?limit=300"); const j=await r.json(); if(!r.ok) throw new Error(j.error||"Cash ledger failed"); setData(j); } catch(e:any){ setError(e.message); } finally { setLoading(false); } },[]);
  useEffect(()=>{ load(); },[load,refreshKey]);
  const rows:Entry[]=data?.entries??[];
  const audit=useMemo(()=>({ tradesLinked:(data?.unlinkedTrades??0)===0, dividendsLinked:(data?.unlinkedDividends??0)===0, hasOpeningBalance:rows.some(r=>["DEPOSIT","ADJUSTMENT"].includes(r.entry_type)) }),[data,rows]);
  const t=(en:string,th:string)=>lang==="th"?th:en;
  return <div className="card" style={{marginTop:18}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><h2 className="section" style={{margin:0}}>💵 {t("Cash Ledger & Audit","สมุดเงินสดและการตรวจสอบ")}</h2><p className="muted" style={{margin:"6px 0 0"}}>{t("BUY, SELL and dividends post automatically. Manual entries are for deposits, withdrawals, fees and opening adjustments.","รายการซื้อ ขาย และปันผลบันทึกอัตโนมัติ รายการกรอกเองใช้สำหรับฝาก ถอน ค่าธรรมเนียม และยอดตั้งต้น")}</p></div><button className="btn ghost sm" onClick={load} disabled={loading}>{loading?"…":"↻ Refresh"}</button></div>
    {error&&<div className="err" style={{marginTop:12}}>⚠ {error}</div>}
    <div className="grid cols-4" style={{marginTop:14}}><Metric label={t("Ledger balance","ยอดเงินสดตามสมุด")} value={money(data?.balance??0)} accent={(data?.balance??0)>=0?"pos":"neg"}/><Metric label={t("Entries","จำนวนรายการ")} value={String(data?.count??0)}/><Metric label={t("Trade linkage","การเชื่อมรายการซื้อขาย")} value={audit.tradesLinked?"PASS":"FAILED"} accent={audit.tradesLinked?"pos":"neg"}/><Metric label={t("Dividend linkage","การเชื่อมปันผล")} value={audit.dividendsLinked?"PASS":"FAILED"} accent={audit.dividendsLinked?"pos":"neg"}/></div>
    {!audit.hasOpeningBalance&&<div className="notice" style={{marginTop:12}}>{t("No opening cash/deposit exists yet. Enter the current broker cash once as DEPOSIT or ADJUSTMENT before treating the ledger balance as complete.","ยังไม่มียอดเงินสดตั้งต้นหรือเงินฝาก กรุณากรอกเงินสดปัจจุบันจากโบรกเกอร์หนึ่งครั้งก่อนใช้ยอดสมุดเป็นยอดสมบูรณ์")}</div>}
    <form className="cash-ledger-form" style={{marginTop:14,display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}} onSubmit={async e=>{e.preventDefault();setBusy(true);setError(null);try{const r=await fetch("/api/portfolio/cash",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Save failed");setForm({...form,amount:"",notes:""});await load();}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>
      <select value={form.entry_type} onChange={e=>setForm({...form,entry_type:e.target.value})}><option>DEPOSIT</option><option>WITHDRAWAL</option><option>FEE</option><option>ADJUSTMENT</option></select>
      <input inputMode="decimal" placeholder={t("Amount","จำนวนเงิน")} value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input type="date" value={form.entry_date} onChange={e=>setForm({...form,entry_date:e.target.value})}/><input style={{flex:1,minWidth:180}} placeholder={t("Source / note","ที่มา / หมายเหตุ")} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className="btn" disabled={busy}>{busy?"…":t("Add cash entry","เพิ่มรายการเงินสด")}</button>
    </form>
    <div className="table-wrap" style={{marginTop:14,maxHeight:420,overflowY:"auto"}}><table className="tbl"><thead><tr><th>{t("Date","วันที่")}</th><th>{t("Type","ประเภท")}</th><th>Ticker</th><th className="num">{t("Amount","จำนวนเงิน")}</th><th>{t("Source","ที่มา")}</th><th></th></tr></thead><tbody>{rows.map(r=>{const amount=Number(r.amount);const system=!!(r.transaction_id||r.dividend_id)||["BUY","SELL","DIVIDEND","TAX"].includes(r.entry_type);return <tr key={r.id}><td>{r.entry_date}</td><td><strong>{r.entry_type}</strong></td><td>{r.ticker??"—"}</td><td className={cls("num",amount>=0?"pos":"neg")}>{money(amount)}</td><td className="muted" style={{fontSize:11.5}}>{system?t("Automatic","อัตโนมัติ"):r.notes||t("Manual","กรอกเอง")}</td><td>{!system&&<button type="button" className="btn danger sm" onClick={async()=>{if(!window.confirm(t("Delete this cash entry?","ลบรายการเงินสดนี้หรือไม่?")))return;const res=await fetch(`/api/portfolio/cash?id=${r.id}`,{method:"DELETE"});const j=await res.json().catch(()=>({}));if(!res.ok){setError(j.error||"Delete failed");return;}load();}}>✕</button>}</td></tr>})}{!rows.length&&!loading&&<tr><td colSpan={6} className="muted">{t("No cash entries yet.","ยังไม่มีรายการเงินสด")}</td></tr>}</tbody></table></div>
    <p className="notice" style={{marginTop:12}}>{t("Audit equation: opening cash + deposits − withdrawals − buys + sells + net dividends − tax − fees ± adjustments = ledger balance.","สมการตรวจสอบ: เงินสดตั้งต้น + เงินฝาก − เงินถอน − ซื้อ + ขาย + ปันผลสุทธิ − ภาษี − ค่าธรรมเนียม ± รายการปรับปรุง = ยอดเงินสดตามสมุด")}</p>
  </div>;
}
function Metric({label,value,accent}:{label:string;value:string;accent?:string}){return <div className="metric"><div className="label">{label}</div><div className={cls("value",accent)} style={{fontSize:19}}>{value}</div></div>}
