"use client";

import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";
import {useFundSnapshot,type FundHolding} from "./useFundSnapshot";

type AnyRow=Record<string,any>;
type Member={name:string;role:string;desk:string;skill:string};
type Review={ticker:string;price:number;fairValue:number|null;upside:number|null;valuation:string;decision:string;confidence:string;reason:string;marketValue:number};
type Message={speaker:string;role:string;tone:"support"|"challenge"|"risk"|"neutral";text:string};

const MEMBERS:Member[]=[
 {name:"James Hartwell",role:"CIO / Chair",desk:"Executive",skill:"Investment System"},{name:"Miriam Osei",role:"Chief Risk Officer",desk:"Risk & Governance",skill:"CRO Intelligence"},{name:"Daniel Cho",role:"Head of Macro Strategy",desk:"Macro",skill:"Macro Intelligence"},{name:"Lena Müller",role:"Portfolio Manager",desk:"Portfolio",skill:"Portfolio Management"},{name:"Sofia Reyes",role:"Senior Fundamental Analyst",desk:"Research",skill:"Equity Research"},{name:"Marcus Webb",role:"Senior Financial Analyst",desk:"Research",skill:"Financial Model"},{name:"Thomas Eriksson",role:"Head of Valuation",desk:"Valuation",skill:"Valuation Suite / DCF"},{name:"Aisha Fontaine",role:"Momentum & Catalyst Analyst",desk:"Catalyst",skill:"Catalyst Intelligence"},{name:"Maya Chen",role:"Momentum & Catalyst Analyst",desk:"Momentum",skill:"Momentum Scanner"},{name:"Priya Nair",role:"Quantitative Strategist",desk:"Quant",skill:"Quant Backtest"},{name:"Kai Tanaka",role:"Portfolio Risk Analyst",desk:"Risk",skill:"Risk Engine"},{name:"Ryan Blackwood",role:"Execution Trader",desk:"Execution",skill:"Execution Intelligence"},{name:"Nina Okonkwo",role:"Data & Source Engineer",desk:"Data",skill:"Data Engineering"},{name:"Leo Tanaka",role:"Real-time Data Analyst",desk:"Data",skill:"Live Feed Intelligence"}
];
const tr=(lang:AppLang,en:string,th:string)=>lang==="th"?th:en;
const finite=(v:unknown):number|null=>{const n=Number(v);return Number.isFinite(n)?n:null};
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const pct=(v:number|null,d=1)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(d)}%`;
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
async function json(path:string){const r=await fetch(path,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error??`${path} failed`);return j}

export default function CIOCommandCenterV17({lang,onNavigate}:{lang:AppLang;onNavigate:(id:string)=>void}){
 const[refreshKey,setRefreshKey]=useState(0);const fund=useFundSnapshot(refreshKey);
 const[market,setMarket]=useState<AnyRow|null>(null);const[analyses,setAnalyses]=useState<Record<string,AnyRow>>({});const[actions,setActions]=useState<AnyRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const[tab,setTab]=useState<"meeting"|"desks"|"portfolio"|"resolution">("meeting");
 useEffect(()=>{let active=true;(async()=>{if(!fund.holdings.length){setLoading(false);return}setLoading(true);setError("");try{const tickers=fund.holdings.map(h=>h.ticker);const res=await Promise.allSettled([json("/api/cio/market-context"),json("/api/analyze/actions"),...tickers.map(t=>json(`/api/analyze?ticker=${encodeURIComponent(t)}`))]);if(!active)return;setMarket(res[0].status==="fulfilled"?res[0].value:null);const a=res[1].status==="fulfilled"?res[1].value:null;setActions(Array.isArray(a?.actions)?a.actions:[]);const map:Record<string,AnyRow>={};tickers.forEach((t,i)=>{const r=res[i+2];if(r?.status==="fulfilled")map[t]=r.value});setAnalyses(map)}catch(e){if(active)setError(e instanceof Error?e.message:"Meeting evidence unavailable")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[fund.holdings.map(h=>h.ticker).join(","),refreshKey]);

 const reviews=useMemo<Review[]>(()=>fund.holdings.map((h:FundHolding)=>{const a=analyses[h.ticker]??{};const u=a.underwriting??{};const values=[u?.valuation?.fairValue,u?.valuation?.targetPrice,a?.targetPrice,a?.dcf?.fairValue,a?.multiples?.fairValue].map(finite).filter((v):v is number=>v!=null&&v>0);const fairValue=values.length?[...values].sort((x,y)=>x-y)[Math.floor(values.length/2)]:null;const upside=fairValue&&h.price>0?(fairValue/h.price-1)*100:null;const evidence=finite(u?.evidence?.score)??finite(a?.evidenceCoverage?.percent)??0;const risk=finite(u?.risk?.score)??50;let valuation="ANALYSIS REQUIRED",decision="REVIEW",reason="Insufficient verified valuation evidence.";if(upside!=null){if(upside>=20){valuation="UNDERVALUED";decision="ADD";reason="Material margin of safety with supportive risk/reward."}else if(upside>=7){valuation="BELOW FAIR VALUE";decision="HOLD / ADD ON WEAKNESS";reason="Positive expected return remains, but entry discipline is required."}else if(upside>=-5){valuation="FAIR / NEAR FULL";decision=risk>=70?"TRIM":"HOLD";reason=risk>=70?"Fair valuation with elevated risk; recycle part of capital.":"Valuation is balanced; retain while thesis remains intact."}else if(upside>=-15){valuation="ABOVE FAIR VALUE";decision="TRIM";reason="Expected return is compressed; reduce and reallocate selectively."}else{valuation="MATERIALLY OVERVALUED";decision=risk>=65?"EXIT":"TRIM";reason="Price exceeds defensible value with weak forward reward."}}const confidence=evidence>=80?"HIGH":evidence>=60?"MEDIUM":"LOW";return{ticker:h.ticker,price:h.price,fairValue,upside,valuation,decision,confidence,reason,marketValue:h.marketValue}}).sort((a,b)=>(a.upside??-999)-(b.upside??-999)),[fund.holdings,analyses]);
 const adds=reviews.filter(r=>r.decision.startsWith("ADD"));const trims=reviews.filter(r=>r.decision==="TRIM"||r.decision==="EXIT");
 const trimPool=trims.reduce((s,r)=>s+r.marketValue*(r.decision==="EXIT"?1:.25),0);const macroScore=fund.macroScore;const vix=finite(market?.vix?.value);const defensivePct=macroScore<45||(vix??0)>=25?55:macroScore<60?35:20;const existingPct=adds.length?Math.min(45,100-defensivePct):20;const newPct=Math.max(0,100-defensivePct-existingPct);const researchIdeas=useMemo(()=>actions.map(r=>({ticker:String(r.ticker??"").toUpperCase(),conviction:finite(r.conviction)??0,upside:finite(r.payload?.upsidePct??r.upside_pct),rating:String(r.rating??r.action??"WATCH")})).filter(r=>r.ticker&&!fund.holdings.some(h=>h.ticker===r.ticker)).sort((a,b)=>(b.conviction+(b.upside??0))-(a.conviction+(a.upside??0))).slice(0,3),[actions,fund.holdings]);
 const spyYtd=finite(fund.raw?.analytics?.benchmarkYtdPct??fund.benchmarkYtdPct);const target=spyYtd==null?null:spyYtd*1.3;const performanceRows=[{label:"Portfolio YTD",value:fund.ytdReturnPct},{label:"SPY YTD",value:spyYtd},{label:"1.3× SPY target",value:target}];
 const messages=useMemo<Message[]>(()=>[
 {speaker:"Daniel Cho",role:"Head of Macro",tone:"neutral",text:`Regime score is ${macroScore}/100. ${vix!=null?`VIX is ${vix.toFixed(1)}.`:"VIX verification is pending."} Capital should be ${macroScore>=65?"deployed selectively":"kept balanced with a larger reserve"}.`},
 {speaker:"Thomas Eriksson",role:"Head of Valuation",tone:trims.length?"challenge":"support",text:trims.length?`${trims.length} holding(s) have compressed or negative forward return versus fair value. I recommend recycling capital rather than selling only because a position is large.`:"No verified holding currently requires a valuation-led trim."},
 {speaker:"Sofia Reyes",role:"Fundamental Research",tone:"support",text:adds.length?`${adds.map(x=>x.ticker).join(", ")} retain meaningful margin of safety. Any addition must remain conditional on thesis, earnings quality and catalyst durability.`:"Current holdings do not yet show a high-conviction valuation gap for immediate addition."},
 {speaker:"Aisha Fontaine",role:"Catalyst Desk",tone:"neutral",text:researchIdeas.length?`Research queue leaders are ${researchIdeas.map(x=>x.ticker).join(", ")}. Catalyst verification is required before capital allocation.`:"No investment-ready catalyst candidate is currently approved."},
 {speaker:"Kai Tanaka",role:"Portfolio Risk",tone:"risk",text:`Recommended routing is ${defensivePct}% reserve, ${existingPct}% existing undervalued holdings and ${newPct}% new ideas. Position concentration is a risk context, not a valuation signal.`},
 {speaker:"Miriam Osei",role:"CRO",tone:"risk",text:"No order should proceed without verified data lineage, explicit fair value range, sizing, stop/kill criteria and human approval."},
 {speaker:"James Hartwell",role:"CIO",tone:"support",text:trimPool>0?`Committee resolution: prepare a human approval package for approximately ${money(trimPool)} of potential capital recycling. Do not auto-execute.`:"Committee resolution: hold the current structure and continue research until a stronger risk/reward gap emerges."}
 ],[macroScore,vix,trims,adds,researchIdeas,defensivePct,existingPct,newPct,trimPool]);
 if(fund.loading||loading)return <section className="card"><span className="spinner"/> Loading Sentinel committee…</section>;
 return <div className="workspace-stack" data-cio-version="17.0" data-workspace="sentinel-professional-fund-committee">
  <section className="card" style={{borderTop:"3px solid var(--accent)"}}><div style={{display:"flex",justifyContent:"space-between",gap:14,flexWrap:"wrap"}}><div><span className="tag">SENTINEL GLOBAL FUND · CIO COMMAND CENTER V17</span><h2 className="section" style={{margin:"10px 0 6px"}}>{tr(lang,"Professional Investment Committee","คณะกรรมการลงทุนระดับมืออาชีพ")}</h2><p className="muted" style={{margin:0,maxWidth:920}}>{tr(lang,"A live round-table where macro, research, valuation, quant, risk, portfolio and execution desks challenge each other before a governed resolution.","โต๊ะประชุมที่ทีม Macro, Research, Valuation, Quant, Risk, Portfolio และ Execution แลกเปลี่ยนความเห็นก่อนลงมติ")}</p></div><div><span className="tag">HUMAN APPROVAL REQUIRED</span><button className="btn ghost" style={{marginLeft:8}} onClick={()=>setRefreshKey(v=>v+1)}>↻ Refresh</button></div></div>{error&&<div className="err" style={{marginTop:12}}>{error}</div>}<div style={{display:"flex",gap:8,overflowX:"auto",marginTop:16}}>{(["meeting","desks","portfolio","resolution"] as const).map(x=><button key={x} className={`btn ${tab===x?"":"ghost"}`} onClick={()=>setTab(x)}>{x.toUpperCase()}</button>)}</div></section>

  {(tab==="meeting")&&<><section className="card"><h3 className="sub">Executive scorecard</h3><div className="grid cols-4"><Gauge label="Macro regime" value={macroScore}/><Gauge label="Portfolio health" value={fund.portfolioHealth}/><Gauge label="Risk control" value={100-fund.riskScore}/><Gauge label="Liquidity" value={fund.liquidityScore}/></div><div className="grid cols-4" style={{marginTop:14}}><Metric label="Verified NAV" value={money(fund.totalNav)}/><Metric label="Open holdings" value={String(fund.openPositions)}/><Metric label="Potential recycle pool" value={money(trimPool)}/><Metric label="Broker cash" value={money(fund.cashBalance)}/></div></section>
  <section className="card"><h3 className="sub">Performance versus mandate</h3><BarCompare rows={performanceRows}/><div className="grid cols-3" style={{marginTop:14}}><Metric label="Portfolio YTD" value={pct(fund.ytdReturnPct)}/><Metric label="SPY YTD" value={pct(spyYtd)}/><Metric label="Target: 1.3× SPY" value={pct(target)}/></div></section>
  <section className="card"><h3 className="sub">Sentinel round table</h3><div style={{display:"grid",gap:10}}>{messages.map((m,i)=><article key={i} className="metric" style={{borderLeft:`4px solid ${m.tone==="risk"?"var(--danger)":m.tone==="support"?"var(--success)":"var(--accent)"}`}}><span><strong>{m.speaker}</strong> · {m.role}</span><p style={{margin:"8px 0 0",lineHeight:1.55}}>{m.text}</p></article>)}</div></section></>}

  {tab==="desks"&&<section className="card"><h3 className="sub">Sentinel team structure</h3><div className="grid cols-4">{MEMBERS.map(m=><article className="metric" key={m.name}><span>{m.desk}</span><strong>{m.name}</strong><small>{m.role}</small><small className="muted">{m.skill}</small></article>)}</div><div className="notice" style={{marginTop:14}}>Workflow: Data → Macro → Fundamental / Financial → Catalyst / Momentum → Valuation → Quant → Risk → Portfolio Fit → CRO Gate → CIO Resolution → Execution.</div></section>}

  {tab==="portfolio"&&<section className="card"><h3 className="sub">Holding-by-holding valuation review</h3><div className="table-wrap"><table className="tbl"><thead><tr><th>Ticker</th><th className="num">Price</th><th className="num">Fair value</th><th className="num">Upside</th><th>Valuation</th><th>Decision</th><th>Confidence</th><th>Committee rationale</th></tr></thead><tbody>{reviews.map(r=><tr key={r.ticker}><td><strong>{r.ticker}</strong></td><td className="num">{money(r.price)}</td><td className="num">{money(r.fairValue)}</td><td className="num">{pct(r.upside)}</td><td><span className="tag">{r.valuation}</span></td><td><strong>{r.decision}</strong></td><td>{r.confidence}</td><td style={{minWidth:260}}>{r.reason}</td></tr>)}</tbody></table></div></section>}

  {tab==="resolution"&&<><section className="card"><h3 className="sub">Capital recycling resolution</h3><p className="muted">The committee defines the destination of proceeds before any trim or exit is approved.</p><RoutingChart reserve={defensivePct} existing={existingPct} fresh={newPct}/><div className="grid cols-3" style={{marginTop:14}}><Metric label={`Reserve / SGOV · ${defensivePct}%`} value={money(trimPool*defensivePct/100)}/><Metric label={`Existing undervalued holdings · ${existingPct}%`} value={money(trimPool*existingPct/100)}/><Metric label={`New research ideas · ${newPct}%`} value={money(trimPool*newPct/100)}/></div><div className="grid cols-2" style={{marginTop:14}}><article className="metric"><span>Existing candidates</span><strong>{adds.length?adds.map(x=>x.ticker).join(" · "):"None approved"}</strong><small>Ranked by margin of safety, thesis quality and risk.</small></article><article className="metric"><span>New candidates</span><strong>{researchIdeas.length?researchIdeas.map(x=>x.ticker).join(" · "):"None approved"}</strong><small>Require catalyst and valuation confirmation.</small></article></div></section><section className="card"><h3 className="sub">Governance package</h3><div className="grid cols-3"><Metric label="CRO gate" value="PENDING HUMAN REVIEW"/><Metric label="CIO sign-off" value="REQUIRED"/><Metric label="Auto execution" value="DISABLED"/></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className="btn ghost" onClick={()=>onNavigate("analyze")}>Open Stock Analyze</button><button className="btn ghost" onClick={()=>onNavigate("portfolio")}>Open Portfolio Operations</button></div></section></>}
 </div>
}

function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Gauge({label,value}:{label:string;value:number}){const v=clamp(value);return <div className="metric" style={{textAlign:"center"}}><div style={{width:132,height:132,borderRadius:"50%",margin:"0 auto",display:"grid",placeItems:"center",background:`conic-gradient(var(--accent) ${v*3.6}deg,rgba(90,110,160,.18) 0)`}}><div style={{width:96,height:96,borderRadius:"50%",display:"grid",placeItems:"center",background:"var(--panel)"}}><strong style={{fontSize:24}}>{Math.round(v)}/100</strong></div></div><strong style={{marginTop:10}}>{label}</strong></div>}
function BarCompare({rows}:{rows:{label:string;value:number|null}[]}){const clean=rows.map(r=>({...r,value:r.value??0}));const max=Math.max(...clean.map(r=>Math.abs(r.value)),1);return <div style={{display:"grid",gap:10}}>{clean.map(r=><div key={r.label}><div style={{display:"flex",justifyContent:"space-between"}}><span>{r.label}</span><strong>{pct(r.value)}</strong></div><div style={{height:14,borderRadius:999,background:"rgba(90,110,160,.18)",overflow:"hidden"}}><div style={{height:"100%",width:`${Math.min(100,Math.abs(r.value)/max*100)}%`,background:"linear-gradient(90deg,var(--accent),#8f5cff)"}}/></div></div>)}</div>}
function RoutingChart({reserve,existing,fresh}:{reserve:number;existing:number;fresh:number}){return <div style={{display:"grid",gridTemplateColumns:`${reserve}fr ${existing}fr ${fresh}fr`,height:44,borderRadius:12,overflow:"hidden",marginTop:12}}><div style={{background:"#64748b",display:"grid",placeItems:"center"}}>{reserve}%</div><div style={{background:"#3b82f6",display:"grid",placeItems:"center"}}>{existing}%</div><div style={{background:"#8b5cf6",display:"grid",placeItems:"center"}}>{fresh}%</div></div>}
