"use client";

import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";
import {useFundSnapshot,type FundHolding} from "./useFundSnapshot";

type AnyRow=Record<string,any>;
type HoldingReview={ticker:string;price:number;marketValue:number;fairValue:number|null;upsidePct:number|null;valuation:string;decision:"ADD"|"HOLD"|"TRIM"|"EXIT"|"REVIEW";sellPct:number;proceeds:number;reason:string;evidence:string};
type Candidate={ticker:string;rating:string;conviction:number;target:number|null;upside:number|null};
const tr=(lang:AppLang,en:string,th:string)=>lang==="th"?th:en;
const finite=(v:unknown):number|null=>{const n=Number(v);return Number.isFinite(n)?n:null};
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const pct=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`;
async function json(path:string){const r=await fetch(path,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error??`${path} failed`);return j}

export default function CIOCommandCenterV15({lang,onNavigate}:{lang:AppLang;onNavigate:(id:string)=>void}){
 const[refreshKey,setRefreshKey]=useState(0);const fund=useFundSnapshot(refreshKey);
 const[market,setMarket]=useState<any>(null);const[analyses,setAnalyses]=useState<Record<string,any>>({});const[actions,setActions]=useState<AnyRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const[selected,setSelected]=useState<Record<string,boolean>>({});const[trimPct,setTrimPct]=useState<Record<string,number>>({});
 const[destSgov,setDestSgov]=useState(100);const[destExisting,setDestExisting]=useState(0);const[destNew,setDestNew]=useState(0);const[selectedNew,setSelectedNew]=useState<Record<string,boolean>>({});

 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError("");try{const tickers=fund.holdings.map(h=>h.ticker);const results=await Promise.allSettled([json("/api/cio/market-context"),json("/api/analyze/actions"),...tickers.map(t=>json(`/api/analyze?ticker=${encodeURIComponent(t)}`))]);if(!active)return;setMarket(results[0].status==="fulfilled"?results[0].value:null);const a=results[1].status==="fulfilled"?results[1].value:null;setActions(Array.isArray(a?.actions)?a.actions:[]);const map:Record<string,any>={};tickers.forEach((t,i)=>{const r=results[i+2];if(r?.status==="fulfilled")map[t]=r.value});setAnalyses(map)}catch(e){if(active)setError(e instanceof Error?e.message:"Committee evidence unavailable")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[fund.holdings.map(h=>h.ticker).join(","),refreshKey]);

 const reviews=useMemo<HoldingReview[]>(()=>fund.holdings.map((h:FundHolding)=>{
  const a=analyses[h.ticker];const u=a?.underwriting;const fair=finite(u?.valuation?.fairValue??u?.valuation?.targetPrice??a?.targetPrice);const upside=fair&&h.price>0?(fair/h.price-1)*100:null;const ratio=fair&&fair>0?h.price/fair:null;let decision:HoldingReview["decision"]="REVIEW";let valuation="ANALYSIS REQUIRED";let sellPct=0;let reason="No verified fair value is linked to this holding.";
  if(ratio!=null){if(ratio<.80){decision="ADD";valuation="UNDERVALUED";reason="Price is materially below fair value; keep or add subject to thesis and risk."}else if(ratio<.95){decision="HOLD";valuation="BELOW FAIR VALUE";reason="Upside remains, but not enough to force an add."}else if(ratio<=1.05){decision="TRIM";valuation="NEAR FULL VALUE";sellPct=25;reason="Price is close to fair value. Committee should choose HOLD or recycle part of the capital."}else{decision=(finite(u?.risk?.score)??50)>=70?"EXIT":"TRIM";valuation="ABOVE FAIR VALUE";sellPct=decision==="EXIT"?100:50;reason=decision==="EXIT"?"Price exceeds fair value and risk is elevated.":"Price exceeds fair value; recycle part of the position."}}
  const chosen=trimPct[h.ticker]??sellPct;return{ticker:h.ticker,price:h.price,marketValue:h.marketValue,fairValue:fair,upsidePct:upside,valuation,decision,sellPct:chosen,proceeds:h.marketValue*chosen/100,reason,evidence:u?`${u.decision} · conviction ${u.conviction}/100 · risk ${u.risk?.score??"—"}/100`:"Analyze data unavailable"}
 }),[fund.holdings,analyses,trimPct]);

 const candidates=useMemo<Candidate[]>(()=>actions.map(r=>({ticker:String(r.ticker??"").toUpperCase(),rating:String(r.rating??r.action??"WATCH"),conviction:finite(r.conviction)??0,target:finite(r.payload?.target??r.target_price),upside:finite(r.payload?.upsidePct??r.payload?.expectedReturnPct)})).filter(r=>r.ticker&&!fund.holdings.some(h=>h.ticker===r.ticker)).sort((a,b)=>b.conviction-a.conviction).slice(0,8),[actions,fund.holdings]);
 const selectedReviews=reviews.filter(r=>selected[r.ticker]);const grossProceeds=selectedReviews.reduce((s,r)=>s+r.proceeds,0);const totalPct=destSgov+destExisting+destNew;const normalized=totalPct>0?totalPct:100;const toSgov=grossProceeds*destSgov/normalized;const toExisting=grossProceeds*destExisting/normalized;const toNew=grossProceeds*destNew/normalized;const newNames=candidates.filter(c=>selectedNew[c.ticker]).slice(0,4);const perNew=newNames.length?toNew/newNames.length:0;
 const sentiment=market?.sentiment;const vix=market?.vix;const econ=market?.economic;

 if(fund.loading||loading)return <section className="card"><span className="spinner"/> Loading committee evidence…</section>;
 return <div className="workspace-stack" data-cio-version="15.0" data-workspace="valuation-led-committee">
  <section className="card" style={{borderTop:"3px solid var(--accent)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span className="tag">CIO COMMAND CENTER · VALUATION-LED</span><h2 className="section" style={{margin:"10px 0 5px"}}>{tr(lang,"Investment Committee & Capital Recycling","ประชุมลงทุนและแผนหมุนเวียนเงินทุน")}</h2><p className="muted" style={{margin:0,maxWidth:900}}>{tr(lang,"Every holding is valued by Stock Analyze first. Concentration is shown as risk context, never used as a substitute for fair value.","ทุกหุ้นใน Holdings ต้องผ่าน Stock Analyze เพื่อหาราคาเหมาะสมก่อน น้ำหนักพอร์ตใช้เป็นบริบทความเสี่ยง ไม่ใช้แทนการประเมินมูลค่า")}</p></div><button className="btn ghost" onClick={()=>setRefreshKey(v=>v+1)}>↻ Refresh meeting</button></div>{error&&<div className="err" style={{marginTop:12}}>{error}</div>}</section>

  <section className="card"><Header no="01" title="Macro, Sentiment & Economic Conditions"/><div className="grid cols-2"><LineChart title="Market Sentiment" value={sentiment?.score??null} subtitle={sentiment?.label??"Unavailable"} points={sentiment?.points??[]} suffix="/100"/><LineChart title="VIX Risk" value={vix?.value??null} subtitle={(vix?.value??0)<15?"Low volatility":(vix?.value??0)<22?"Normal":(vix?.value??0)<30?"Elevated":"High stress"} points={vix?.points??[]} suffix=""/></div><div className="grid cols-3" style={{marginTop:14}}><EconomicCard label="Policy Rate" value={econ?.policyRate} suffix="%" points={econ?.policyRateHistory}/><EconomicCard label="Inflation YoY" value={econ?.inflation} suffix="%" points={econ?.inflationHistory}/><EconomicCard label="GDP Growth" value={econ?.gdpGrowth} suffix="%" points={econ?.gdpHistory}/></div><div className="notice" style={{marginTop:14}}>Market charts: Yahoo Finance · Economic series: FRED · As of {market?.asOf?new Date(market.asOf).toLocaleString():"—"}</div></section>

  <section className="card"><Header no="02" title="Holding-by-Holding Fair Value Review"/><div className="notice">Decision bands: below 80% of fair value = ADD review · 80–95% = HOLD · 95–105% = near full value / TRIM review · above 105% = TRIM or EXIT review. Human approval remains mandatory.</div><div className="table-wrap" style={{marginTop:14}}><table className="tbl"><thead><tr><th>Select</th><th>Ticker</th><th className="num">Current</th><th className="num">Fair value</th><th className="num">Upside</th><th>Valuation</th><th>Committee view</th><th className="num">Sell %</th><th className="num">Estimated proceeds</th></tr></thead><tbody>{reviews.map(r=><tr key={r.ticker}><td><input type="checkbox" checked={!!selected[r.ticker]} onChange={e=>setSelected(s=>({...s,[r.ticker]:e.target.checked}))}/></td><td><strong>{r.ticker}</strong><small className="muted" style={{display:"block"}}>{r.evidence}</small></td><td className="num">{money(r.price)}</td><td className="num">{money(r.fairValue)}</td><td className="num">{pct(r.upsidePct)}</td><td><span className="tag">{r.valuation}</span></td><td><strong>{r.decision}</strong><small className="muted" style={{display:"block",maxWidth:260}}>{r.reason}</small></td><td className="num"><select value={r.sellPct} onChange={e=>setTrimPct(s=>({...s,[r.ticker]:Number(e.target.value)}))}><option value={0}>0%</option><option value={25}>25%</option><option value={50}>50%</option><option value={75}>75%</option><option value={100}>100%</option></select></td><td className="num">{money(r.proceeds)}</td></tr>)}</tbody></table></div><div className="grid cols-4" style={{marginTop:14}}><Metric label="Selected holdings" value={String(selectedReviews.length)}/><Metric label="Estimated proceeds" value={money(grossProceeds)}/><Metric label="Broker cash" value={money(fund.cashBalance)}/><Metric label="Total available after approval" value={money(grossProceeds+fund.cashBalance)}/></div></section>

  <section className="card"><Header no="03" title="Where the Trim / Exit Proceeds Go Next"/><p className="muted">A TRIM decision is incomplete until the destination of proceeds is defined. Allocate the estimated proceeds below; this remains a proposal only.</p><div className="grid cols-3"><AllocationInput label="Park in SGOV" value={destSgov} set={setDestSgov}/><AllocationInput label="Add to existing holdings" value={destExisting} set={setDestExisting}/><AllocationInput label="Add new stocks" value={destNew} set={setDestNew}/></div><div className={`notice ${totalPct===100?"":"err"}`} style={{marginTop:12}}>Allocation total: <strong>{totalPct}%</strong> {totalPct===100?"· ready for human review":"· adjust to exactly 100%"}</div><div className="grid cols-3" style={{marginTop:14}}><Metric label="To SGOV" value={money(toSgov)}/><Metric label="To existing holdings" value={money(toExisting)}/><Metric label="To new stocks" value={money(toNew)}/></div>
   <h3 className="sub" style={{marginTop:20}}>Choose 1–4 new stocks</h3>{candidates.length?<div className="grid cols-4">{candidates.map(c=><label className="metric" key={c.ticker} style={{cursor:"pointer"}}><span><input type="checkbox" checked={!!selectedNew[c.ticker]} disabled={!selectedNew[c.ticker]&&newNames.length>=4} onChange={e=>setSelectedNew(s=>({...s,[c.ticker]:e.target.checked}))}/> {c.rating}</span><strong>{c.ticker}</strong><small>Conviction {c.conviction}/100 · target {money(c.target)} · upside {pct(c.upside)}</small></label>)}</div>:<div className="notice">No new-stock candidates are currently in the Analyze queue.</div>}
   <div className="card" style={{marginTop:14}}><h3 className="sub">Capital routing preview</h3><Flow from={`${selectedReviews.map(r=>r.ticker).join(" + ")||"No selected sale"} → ${money(grossProceeds)}`} to={[`SGOV ${money(toSgov)}`,`Existing holdings ${money(toExisting)}`,...(newNames.length?newNames.map(n=>`${n.ticker} ${money(perNew)}`):[`New stocks ${money(toNew)} · select names`])]}/></div>
  </section>

  <section className="card"><Header no="04" title="Human Approval Package"/><div className="notice"><strong>Proposed actions:</strong> {selectedReviews.length?selectedReviews.map(r=>`${r.ticker} sell ${r.sellPct}% (${money(r.proceeds)})`).join(" · "):"No holding selected."}</div><div className="notice" style={{marginTop:10}}><strong>Destination:</strong> SGOV {money(toSgov)} · existing holdings {money(toExisting)} · new stocks {money(toNew)} {newNames.length?`across ${newNames.map(n=>n.ticker).join(", ")}`:"(names not selected)"}.</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className="btn ghost" onClick={()=>onNavigate("analyze")}>Open Stock Analyze</button><button className="btn ghost" onClick={()=>onNavigate("portfolio")}>Open Portfolio Operations</button><span className="tag">NO AUTO EXECUTION</span></div></section>
 </div>
}

function Header({no,title}:{no:string;title:string}){return <div style={{display:"flex",gap:12,alignItems:"center",marginBottom:14}}><span className="tag">{no}</span><h3 className="sub" style={{margin:0}}>{title}</h3></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function AllocationInput({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="metric"><span>{label}</span><strong>{value}%</strong><input type="range" min="0" max="100" step="5" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
function Flow({from,to}:{from:string;to:string[]}){return <div><div className="metric"><span>Capital source</span><strong>{from}</strong></div><div style={{textAlign:"center",fontSize:28,margin:8}}>↓</div><div className="grid cols-3">{to.map(x=><div className="metric" key={x}><span>Destination</span><strong>{x}</strong></div>)}</div></div>}
function LineChart({title,value,subtitle,points,suffix}:{title:string;value:number|null;subtitle:string;points:{date:string;value:number}[];suffix:string}){const clean=(points??[]).filter(p=>Number.isFinite(p.value)).slice(-90);const w=520,h=170,pad=12;const min=clean.length?Math.min(...clean.map(p=>p.value)):0,max=clean.length?Math.max(...clean.map(p=>p.value)):1,span=Math.max(.01,max-min);const path=clean.map((p,i)=>`${pad+i/Math.max(1,clean.length-1)*(w-pad*2)},${h-pad-(p.value-min)/span*(h-pad*2)}`).join(" ");return <div className="card" style={{margin:0}}><span className="tag">LIVE SERIES</span><h3 className="sub">{title}</h3><div style={{fontSize:30,fontWeight:850}}>{value==null?"—":`${value.toFixed(1)}${suffix}`}</div><div className="muted">{subtitle}</div>{clean.length?<svg viewBox={`0 0 ${w} ${h}`} style={{width:"100%",height:180,marginTop:10}}><polyline points={path} fill="none" stroke="var(--accent)" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/></svg>:<div className="notice" style={{marginTop:12}}>Series unavailable</div>}</div>}
function EconomicCard({label,value,suffix,points}:{label:string;value:number|null;suffix:string;points:{date:string;value:number}[]}){const clean=(points??[]).filter(p=>Number.isFinite(p.value)).slice(-12);const max=Math.max(...clean.map(p=>Math.abs(p.value)),1);return <div className="metric"><span>{label}</span><strong>{value==null?"Unavailable":`${Number(value).toFixed(2)}${suffix}`}</strong><div style={{display:"flex",alignItems:"end",gap:3,height:55,marginTop:10}}>{clean.map((p,i)=><div key={`${p.date}-${i}`} title={`${p.date}: ${p.value}`} style={{flex:1,height:`${Math.max(5,Math.abs(p.value)/max*100)}%`,background:"var(--accent)",opacity:.35+i/clean.length*.65,borderRadius:"3px 3px 0 0"}}/>)}</div></div>}
