"use client";
import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";
import {useFundSnapshot} from "./useFundSnapshot";
type Row=Record<string,any>;
const finite=(v:any)=>Number.isFinite(Number(v))?Number(v):null;
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const pct=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`;
async function j(path:string){const r=await fetch(path,{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x?.error??"Request failed");return x}
export default function CIOCommandCenterV18({lang,onNavigate}:{lang:AppLang;onNavigate:(id:string)=>void}){
 const fund=useFundSnapshot();const[actions,setActions]=useState<Row[]>([]);const[analysis,setAnalysis]=useState<Record<string,Row>>({});const[tab,setTab]=useState<"meeting"|"workflow"|"analysis"|"plan">("meeting");
 useEffect(()=>{if(!fund.holdings.length)return;(async()=>{const t=fund.holdings.map(x=>x.ticker);const r=await Promise.allSettled([j("/api/analyze/actions"),...t.map(x=>j(`/api/analyze?ticker=${x}`))]);const a=r[0].status==="fulfilled"?r[0].value:{};setActions(Array.isArray(a?.actions)?a.actions:[]);const m:Record<string,Row>={};t.forEach((x,i)=>{const q=r[i+1];if(q?.status==="fulfilled")m[x]=q.value});setAnalysis(m)})()},[fund.holdings.map(x=>x.ticker).join(",")]);
 const reviews=useMemo(()=>fund.holdings.map(h=>{const a=analysis[h.ticker]??{},u=a.underwriting??{};const vals=[u?.valuation?.fairValue,u?.valuation?.targetPrice,a?.targetPrice,a?.dcf?.fairValue,a?.multiples?.fairValue].map(finite).filter((x):x is number=>x!=null&&x>0).sort((x,y)=>x-y);const fv=vals.length?vals[Math.floor(vals.length/2)]:null;const up=fv&&h.price?((fv/h.price)-1)*100:null;const thesis=String(u?.thesis?.summary??a?.thesis??"Thesis refresh required");const catalyst=String(u?.catalyst?.summary??a?.catalyst??"Catalyst not verified");let decision="REVIEW";if(up!=null)decision=up>=20?"ADD":up>=7?"HOLD / ADD":up>=-5?"HOLD":up>=-15?"TRIM":"EXIT";return{...h,fv,up,thesis,catalyst,decision}}),[fund.holdings,analysis]);
 const trims=reviews.filter(x=>x.decision==="TRIM"||x.decision==="EXIT");const adds=reviews.filter(x=>x.decision.includes("ADD"));const recycle=trims.reduce((s,x)=>s+x.marketValue*(x.decision==="EXIT"?1:.25),0)+fund.deployableCash;
 const ideas=actions.map(x=>({ticker:String(x.ticker??"").toUpperCase(),score:finite(x.conviction)??0,thesis:String(x.payload?.thesis??x.thesis??"Research thesis pending"),catalyst:String(x.payload?.catalyst??x.catalyst??"Catalyst pending")})).filter(x=>x.ticker&&!fund.holdings.some(h=>h.ticker===x.ticker)).sort((a,b)=>b.score-a.score).slice(0,4);
 const candidates=[...adds.map(x=>({ticker:x.ticker,type:"Existing",score:(x.up??0)+50})),...ideas.map(x=>({ticker:x.ticker,type:"New",score:x.score}))].sort((a,b)=>b.score-a.score).slice(0,4);const reserve=fund.macroScore<50?45:20;const invest=100-reserve;const weights=[.4,.3,.2,.1];
 return <div className="workspace-stack" data-cio-version="18.0"><section className="card"><span className="tag">SENTINEL CIO V18 · RESEARCH → ANALYSIS → PORTFOLIO</span><h2>{lang==="th"?"ระบบวางแผนและปรับพอร์ต":"Professional Rebalance Operating System"}</h2><p className="muted">Research ค้นหาการลงทุนใหม่ → Analysis วิเคราะห์ valuation, thesis, catalyst → Portfolio ส่งแผน rebalance และเพิ่มหุ้นเข้าพอร์ต → Human approval</p><div style={{display:"flex",gap:8,overflowX:"auto"}}>{(["meeting","workflow","analysis","plan"] as const).map(x=><button className={`btn ${tab===x?"":"ghost"}`} onClick={()=>setTab(x)} key={x}>{x.toUpperCase()}</button>)}</div></section>
 {tab==="meeting"&&<><section className="card"><div className="grid cols-4"><Gauge n={fund.macroScore} label="Macro"/><Gauge n={fund.portfolioHealth} label="Portfolio health"/><Metric l="Portfolio value" v={money(fund.securitiesValue)}/><Metric l="Rebalance budget" v={money(recycle)}/></div></section><section className="card"><h3>Sentinel meeting</h3><Talk who="Sofia Reyes · Research">เสนอ {ideas.length?ideas.map(x=>x.ticker).join(", "):"ยังไม่มีหุ้นใหม่ที่พร้อม"} จากแนวโน้มอนาคต momentum และ catalyst</Talk><Talk who="Thomas Eriksson · Analysis">วิเคราะห์ทุก holdings ด้วย fair value, thesis และ catalyst ไม่ใช้เพียงน้ำหนักพอร์ตตัดสิน</Talk><Talk who="Lena Müller · Portfolio">เตรียมแผน trim/exit, add หุ้นเดิม, เพิ่มหุ้นใหม่ และพักเงินส่วนเหลือใน SGOV</Talk><Talk who="Miriam Osei · CRO">ต้องผ่านข้อมูลครบและ Human approval ก่อนบันทึกคำสั่งจริง</Talk></section></>}
 {tab==="workflow"&&<section className="card"><div className="grid cols-3"><Desk title="01 Research" text="ค้นหา future themes, sector rotation, momentum, quality และ catalyst" click={()=>onNavigate("research")}/><Desk title="02 Analysis" text="วิเคราะห์ fundamental, fair value, thesis, catalyst และความเสี่ยง" click={()=>onNavigate("analyze")}/><Desk title="03 Portfolio" text="ส่งแผน rebalance: trim, exit, add existing, add new, SGOV residual" click={()=>onNavigate("portfolio")}/></div><h3 style={{marginTop:20}}>New investment pipeline</h3><div className="grid cols-2">{ideas.map(x=><article className="metric" key={x.ticker}><strong>{x.ticker}</strong><span>Conviction {x.score}/100</span><small>{x.thesis}</small><small>{x.catalyst}</small></article>)}</div></section>}
 {tab==="analysis"&&<section className="card"><h3>Analysis team review</h3><div className="table-wrap"><table className="tbl"><thead><tr><th>Ticker</th><th>Price</th><th>Fair value</th><th>Upside</th><th>Decision</th><th>Thesis</th><th>Catalyst</th></tr></thead><tbody>{reviews.map(x=><tr key={x.ticker}><td><strong>{x.ticker}</strong></td><td>{money(x.price)}</td><td>{x.fv?money(x.fv):"—"}</td><td>{pct(x.up)}</td><td><strong>{x.decision}</strong></td><td>{x.thesis}</td><td>{x.catalyst}</td></tr>)}</tbody></table></div></section>}
 {tab==="plan"&&<section className="card"><h3>Portfolio rebalance plan</h3><div className="grid cols-3"><Metric l="Funding source" v={money(recycle)}/><Metric l={`SGOV reserve ${reserve}%`} v={money(recycle*reserve/100)}/><Metric l={`Invest ${invest}%`} v={money(recycle*invest/100)}/></div><div className="grid cols-2" style={{marginTop:14}}>{candidates.map((x,i)=><article className="metric" key={x.ticker}><span>{x.type}</span><strong>{x.ticker} · {money(recycle*invest/100*(weights[i]??0))}</strong><small>Ranked by valuation, thesis, catalyst and conviction</small></article>)}</div><div className="notice" style={{marginTop:14}}>Portfolio submits this plan to CIO/CRO. Human may approve all, approve selected items, change size, or reject. No auto execution.</div></section>}
 </div>}
function Metric({l,v}:{l:string;v:string}){return <div className="metric"><span>{l}</span><strong>{v}</strong></div>}
function Gauge({n,label}:{n:number;label:string}){const v=Math.max(0,Math.min(100,n));return <div className="metric" style={{textAlign:"center"}}><div style={{margin:"auto",width:110,height:110,borderRadius:"50%",display:"grid",placeItems:"center",background:`conic-gradient(var(--accent) ${v*3.6}deg,rgba(90,110,160,.18) 0)`}}><strong>{Math.round(v)}/100</strong></div><strong>{label}</strong></div>}
function Talk({who,children}:{who:string;children:any}){return <article className="metric" style={{marginBottom:10}}><strong>{who}</strong><p>{children}</p></article>}
function Desk({title,text,click}:{title:string;text:string;click:()=>void}){return <article className="metric"><strong>{title}</strong><p>{text}</p><button className="btn ghost" onClick={click}>Open workspace</button></article>}
