"use client";

import {useEffect,useMemo,useRef,useState} from "react";
import type {AppLang} from "../page";
import {useFundSnapshot,type FundHolding} from "./useFundSnapshot";

type AnyRow=Record<string,any>;
type Decision="ADD"|"HOLD"|"TRIM"|"EXIT"|"REVIEW";
type Confidence="HIGH"|"MEDIUM"|"LOW";
type Review={ticker:string;price:number;marketValue:number;fairValue:number|null;upsidePct:number|null;valuation:string;decision:Decision;sellPct:number;proceeds:number;reason:string;evidence:string;confidence:Confidence;score:number;risk:number;quality:number;growth:number;source:string};
type Candidate={ticker:string;rating:string;conviction:number;target:number|null;upside:number|null;score:number};
type Route={sgov:number;existing:number;newStocks:number;rationale:string};

const tr=(lang:AppLang,en:string,th:string)=>lang==="th"?th:en;
const finite=(v:unknown):number|null=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const pct=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`;
async function json(path:string){const r=await fetch(path,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j?.error??`${path} failed`);return j}
const median=(values:number[])=>{const a=values.filter(v=>Number.isFinite(v)&&v>0).sort((x,y)=>x-y);if(!a.length)return null;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const firstFinite=(...values:unknown[])=>values.map(finite).find((v):v is number=>v!=null&&v>0)??null;

function buildReview(h:FundHolding,a:any,override:number|undefined):Review{
 const u=a?.underwriting??{};const risk=finite(u?.risk?.score??a?.committee?.deskScores?.risk)??55;const quality=finite(u?.quality?.score??u?.financial?.scores?.quality)??50;const growth=finite(u?.growth?.score??u?.financial?.scores?.growth)??50;const conviction=finite(u?.conviction??a?.committee?.conviction)??40;
 const direct=[u?.valuation?.fairValue,u?.valuation?.targetPrice,u?.dcf?.fairValue,u?.dcf?.baseValue,a?.targetPrice,a?.dcf?.fairValue,a?.dcf?.baseValue,a?.multiples?.fairValue,a?.research?.analystTarget,a?.data?.overview?.analystTargetPrice].map(finite).filter((v):v is number=>v!=null&&v>0);
 let fair=median(direct);let source=direct.length>=2?`Blended median of ${direct.length} valuation methods`:direct.length===1?"Single verified valuation method":"Committee score model";let confidence:Confidence=direct.length>=2?"HIGH":direct.length===1?"MEDIUM":"LOW";
 if(fair==null&&h.price>0){const implied=clamp((quality-50)*.14+(growth-50)*.12+(conviction-50)*.08-(risk-50)*.11,-25,25);fair=h.price*(1+implied/100);source="Transparent quality/growth/risk fallback";}
 if(["SGOV","BIL","SHV","USFR","TFLO"].includes(h.ticker)){fair=h.price;source="Cash-reserve NAV proxy";confidence="HIGH";}
 const upside=fair&&h.price>0?(fair/h.price-1)*100:null;const ratio=fair&&fair>0?h.price/fair:null;const underwritingDecision=String(u?.decision??a?.signal??"").toUpperCase();let decision:Decision="REVIEW",sellPct=0,valuation="ANALYSIS REQUIRED",reason="Analysis team could not establish a usable valuation range.";
 if(ratio!=null){
  if(ratio<=.78&&quality>=50&&risk<75){decision="ADD";valuation="MATERIALLY UNDERVALUED";reason="Price offers a wide discount to fair value with acceptable quality and risk."}
  else if(ratio<.95){decision="HOLD";valuation="BELOW FAIR VALUE";reason="Expected return remains positive; hold and add only on stronger evidence or weakness."}
  else if(ratio<=1.05){decision=risk>=72||/SELL/.test(underwritingDecision)?"TRIM":"HOLD";valuation="NEAR FAIR VALUE";sellPct=decision==="TRIM"?25:0;reason=decision==="TRIM"?"Valuation is full and risk is elevated; recycle a limited portion.":"Price is near fair value, but thesis and risk do not justify a forced sale."}
  else if(ratio<=1.18){decision="TRIM";valuation="ABOVE FAIR VALUE";sellPct=risk>=70?50:25;reason="Price exceeds the analysis team's fair-value range; recycle part of the position."}
  else {decision=risk>=70||/STRONG SELL|SELL/.test(underwritingDecision)?"EXIT":"TRIM";valuation="MATERIALLY OVERVALUED";sellPct=decision==="EXIT"?100:50;reason=decision==="EXIT"?"Large valuation excess plus elevated risk supports exit review.":"Large valuation excess supports a substantial trim, while thesis risk is not high enough for an automatic exit recommendation."}
 }
 const chosen=override??sellPct;const score=clamp((upside??0)*1.2+quality*.35+growth*.25+(100-risk)*.25);
 return{ticker:h.ticker,price:h.price,marketValue:h.marketValue,fairValue:fair,upsidePct:upside,valuation,decision,sellPct:chosen,proceeds:h.marketValue*chosen/100,reason,evidence:`${underwritingDecision||"ANALYZED"} · conviction ${Math.round(conviction)}/100 · risk ${Math.round(risk)}/100`,confidence,score,risk,quality,growth,source};
}

function committeeRoute(macroScore:number,vix:number|null,hasExisting:boolean,hasNew:boolean):Route{
 let sgov=macroScore<45||((vix??0)>=28)?60:macroScore<60||((vix??0)>=22)?40:20;let existing=hasExisting?(macroScore>=60?40:25):0;let newStocks=hasNew?(macroScore>=65?40:macroScore>=50?25:10):0;const total=sgov+existing+newStocks;if(total<100)sgov+=100-total;if(total>100){const scale=100/total;sgov=Math.round(sgov*scale);existing=Math.round(existing*scale);newStocks=100-sgov-existing}
 const rationale=macroScore>=65?"Constructive regime: recycle capital toward the strongest undervalued holdings and highest-conviction new ideas, while retaining a reserve sleeve.":macroScore>=50?"Balanced regime: split proceeds between reserve assets and selective opportunities.":"Defensive regime: preserve most proceeds in SGOV and deploy only to the clearest valuation gaps.";return{sgov,existing,newStocks,rationale};
}

export default function CIOCommandCenterV16({lang,onNavigate}:{lang:AppLang;onNavigate:(id:string)=>void}){
 const[refreshKey,setRefreshKey]=useState(0);const fund=useFundSnapshot(refreshKey);const[market,setMarket]=useState<any>(null);const[analyses,setAnalyses]=useState<Record<string,any>>({});const[actions,setActions]=useState<AnyRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selected,setSelected]=useState<Record<string,boolean>>({});const[trimPct,setTrimPct]=useState<Record<string,number>>({});const[dest,setDest]=useState<Route>({sgov:100,existing:0,newStocks:0,rationale:""});const[selectedNew,setSelectedNew]=useState<Record<string,boolean>>({});const initialized=useRef("");
 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError("");try{const tickers=fund.holdings.map(h=>h.ticker);const results=await Promise.allSettled([json("/api/cio/market-context"),json("/api/analyze/actions"),...tickers.map(t=>json(`/api/analyze?ticker=${encodeURIComponent(t)}`))]);if(!active)return;setMarket(results[0].status==="fulfilled"?results[0].value:null);const aq=results[1].status==="fulfilled"?results[1].value:null;setActions(Array.isArray(aq?.actions)?aq.actions:[]);const map:Record<string,any>={};tickers.forEach((t,i)=>{const r=results[i+2];if(r?.status==="fulfilled")map[t]=r.value});setAnalyses(map)}catch(e){if(active)setError(e instanceof Error?e.message:"Committee evidence unavailable")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[fund.holdings.map(h=>h.ticker).join(","),refreshKey]);
 const reviews=useMemo(()=>fund.holdings.map(h=>buildReview(h,analyses[h.ticker],trimPct[h.ticker])).sort((a,b)=>b.score-a.score),[fund.holdings,analyses,trimPct]);
 const candidates=useMemo<Candidate[]>(()=>actions.map(r=>({ticker:String(r.ticker??"").toUpperCase(),rating:String(r.rating??r.action??"WATCH"),conviction:finite(r.conviction)??0,target:firstFinite(r.payload?.target,r.target_price),upside:finite(r.payload?.upsidePct??r.payload?.expectedReturnPct),score:(finite(r.conviction)??0)+(finite(r.payload?.upsidePct??r.payload?.expectedReturnPct)??0)*.7})).filter(r=>r.ticker&&!fund.holdings.some(h=>h.ticker===r.ticker)&&(/BUY|ADD|ACCUMULATE|OUTPERFORM/.test(r.rating.toUpperCase())||(r.upside??0)>=10)).sort((a,b)=>b.score-a.score).slice(0,8),[actions,fund.holdings]);
 const existingAdds=reviews.filter(r=>r.decision==="ADD"||(r.decision==="HOLD"&&(r.upsidePct??0)>=10)).sort((a,b)=>b.score-a.score).slice(0,3);const vix=finite(market?.vix?.value);const recommended=useMemo(()=>committeeRoute(fund.macroScore,vix,existingAdds.length>0,candidates.length>0),[fund.macroScore,vix,existingAdds.length,candidates.length]);
 useEffect(()=>{const key=reviews.map(r=>`${r.ticker}:${r.decision}:${r.sellPct}`).join("|");if(!reviews.length||initialized.current===key)return;initialized.current=key;const s:Record<string,boolean>={},p:Record<string,number>={};reviews.forEach(r=>{if(r.decision==="TRIM"||r.decision==="EXIT")s[r.ticker]=true;p[r.ticker]=r.sellPct});setSelected(s);setTrimPct(p);setDest(recommended);const n:Record<string,boolean>={};candidates.slice(0,Math.min(3,candidates.length)).forEach(c=>n[c.ticker]=true);setSelectedNew(n)},[reviews,recommended,candidates]);
 const selectedReviews=reviews.filter(r=>selected[r.ticker]&&r.sellPct>0);const gross=selectedReviews.reduce((s,r)=>s+r.proceeds,0);const toSgov=gross*dest.sgov/100,toExisting=gross*dest.existing/100,toNew=gross*dest.newStocks/100;const newNames=candidates.filter(c=>selectedNew[c.ticker]).slice(0,4);const existingTotalScore=existingAdds.reduce((s,r)=>s+r.score,0)||1;const newTotalScore=newNames.reduce((s,r)=>s+r.score,0)||1;
 if(fund.loading||loading)return <section className="card"><span className="spinner"/> Loading analysis team and committee evidence…</section>;
 return <div className="workspace-stack" data-cio-version="16.0" data-workspace="analysis-led-committee">
  <section className="card" style={{borderTop:"3px solid var(--accent)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span className="tag">CIO COMMAND CENTER · ANALYSIS-LED V16</span><h2 className="section" style={{margin:"10px 0 5px"}}>{tr(lang,"Valuation Committee & Capital Deployment Plan","คณะกรรมการประเมินมูลค่าและแผนจัดสรรเงิน")}</h2><p className="muted" style={{margin:0,maxWidth:900}}>{tr(lang,"The Analysis team must produce a fair-value estimate for every holding. Verified DCF, multiples and analyst targets are blended first; when evidence is incomplete, a transparent low-confidence score model is used instead of returning zero.","ทีม Analysis ต้องประเมิน Fair Value ให้ทุกหุ้น โดยใช้ DCF, Multiples และราคาเป้าหมายก่อน หากข้อมูลไม่ครบจะใช้โมเดลสำรองที่โปร่งใสและระบุความเชื่อมั่นต่ำ แทนการแสดงศูนย์")}</p></div><button className="btn ghost" onClick={()=>{initialized.current="";setRefreshKey(v=>v+1)}}>↻ Run committee again</button></div>{error&&<div className="err" style={{marginTop:12}}>{error}</div>}</section>
  <section className="card"><Header no="01" title="Analysis Team: Fair Value for Every Holding"/><div className="notice">Valuation is based on intrinsic-value evidence, not portfolio weight. Concentration is reviewed separately as risk context.</div><div className="grid cols-2" style={{marginTop:14}}>{reviews.map(r=><article className="card" key={r.ticker} style={{margin:0}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"flex-start"}}><label><input type="checkbox" checked={!!selected[r.ticker]} onChange={e=>setSelected(s=>({...s,[r.ticker]:e.target.checked}))}/> <strong style={{fontSize:22}}>{r.ticker}</strong></label><span className="tag">{r.confidence} CONFIDENCE</span></div><div className="grid cols-3" style={{marginTop:12}}><Metric label="Current" value={money(r.price)}/><Metric label="Fair value" value={money(r.fairValue)}/><Metric label="Upside / downside" value={pct(r.upsidePct)}/></div><p><span className="tag">{r.valuation}</span> <strong style={{marginLeft:8}}>{r.decision}</strong></p><p className="muted">{r.reason}</p><small className="muted">Method: {r.source} · {r.evidence} · quality {Math.round(r.quality)}/100 · growth {Math.round(r.growth)}/100</small><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginTop:12}}><label>Recommended sell <select value={r.sellPct} onChange={e=>setTrimPct(s=>({...s,[r.ticker]:Number(e.target.value)}))}><option value={0}>0%</option><option value={25}>25%</option><option value={50}>50%</option><option value={75}>75%</option><option value={100}>100%</option></select></label><strong>{money(r.proceeds)}</strong></div></article>)}</div><div className="grid cols-4" style={{marginTop:14}}><Metric label="Committee-selected sales" value={String(selectedReviews.length)}/><Metric label="Estimated proceeds" value={money(gross)}/><Metric label="Broker cash" value={money(fund.cashBalance)}/><Metric label="Available after approval" value={money(gross+fund.cashBalance)}/></div></section>
  <section className="card"><Header no="02" title="Committee Decision: Where Proceeds Go Next"/><div className="notice"><strong>Team recommendation:</strong> {recommended.rationale}</div><div className="grid cols-3" style={{marginTop:14}}><Allocation label="SGOV reserve" value={dest.sgov} set={v=>setDest(d=>({...d,sgov:v}))}/><Allocation label="Add existing holdings" value={dest.existing} set={v=>setDest(d=>({...d,existing:v}))}/><Allocation label="Add new stocks" value={dest.newStocks} set={v=>setDest(d=>({...d,newStocks:v}))}/></div><div className={`notice ${dest.sgov+dest.existing+dest.newStocks===100?"":"err"}`} style={{marginTop:12}}>Allocation total: <strong>{dest.sgov+dest.existing+dest.newStocks}%</strong> · committee default was {recommended.sgov}% SGOV / {recommended.existing}% existing / {recommended.newStocks}% new.</div><div className="grid cols-3" style={{marginTop:14}}><Metric label="To SGOV" value={money(toSgov)}/><Metric label="To existing holdings" value={money(toExisting)}/><Metric label="To new stocks" value={money(toNew)}/></div>
   <h3 className="sub" style={{marginTop:20}}>Existing holdings selected by valuation gap</h3>{existingAdds.length?<div className="grid cols-3">{existingAdds.map(r=><div className="metric" key={r.ticker}><span>{r.valuation} · {pct(r.upsidePct)}</span><strong>{r.ticker} {money(toExisting*r.score/existingTotalScore)}</strong></div>)}</div>:<div className="notice">No existing holding has enough verified upside to receive additional capital; this sleeve should remain in SGOV.</div>}
   <h3 className="sub" style={{marginTop:20}}>New investments selected by Research + Analyze</h3>{candidates.length?<div className="grid cols-4">{candidates.map(c=><label className="metric" key={c.ticker}><span><input type="checkbox" checked={!!selectedNew[c.ticker]} disabled={!selectedNew[c.ticker]&&newNames.length>=4} onChange={e=>setSelectedNew(s=>({...s,[c.ticker]:e.target.checked}))}/> {c.rating}</span><strong>{c.ticker}</strong><small>Conviction {Math.round(c.conviction)}/100 · target {money(c.target)} · upside {pct(c.upside)}</small></label>)}</div>:<div className="notice">No new candidate currently passes the committee threshold. The new-stock sleeve should be redirected to SGOV.</div>}
   {newNames.length>0&&<div className="grid cols-4" style={{marginTop:12}}>{newNames.map(c=><div className="metric" key={c.ticker}><span>Proposed new allocation</span><strong>{c.ticker} {money(toNew*c.score/newTotalScore)}</strong></div>)}</div>}
  </section>
  <section className="card"><Header no="03" title="Human Approval Package"/><div className="notice"><strong>Sell / trim proposal:</strong> {selectedReviews.length?selectedReviews.map(r=>`${r.ticker} ${r.sellPct}% (${money(r.proceeds)})`).join(" · "):"No sale proposed."}</div><div className="notice" style={{marginTop:10}}><strong>Capital deployment:</strong> SGOV {money(toSgov)} · existing holdings {money(toExisting)} {existingAdds.length?`to ${existingAdds.map(r=>r.ticker).join(", ")}`:""} · new stocks {money(toNew)} {newNames.length?`to ${newNames.map(n=>n.ticker).join(", ")}`:""}.</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className="btn ghost" onClick={()=>onNavigate("analyze")}>Open Stock Analyze</button><button className="btn ghost" onClick={()=>onNavigate("portfolio")}>Open Portfolio Operations</button><span className="tag">HUMAN APPROVAL REQUIRED · NO AUTO EXECUTION</span></div></section>
 </div>
}
function Header({no,title}:{no:string;title:string}){return <div style={{display:"flex",gap:12,alignItems:"center",marginBottom:14}}><span className="tag">{no}</span><h3 className="sub" style={{margin:0}}>{title}</h3></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Allocation({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="metric"><span>{label}</span><strong>{value}%</strong><input type="range" min="0" max="100" step="5" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
