"use client";

import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";

const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
const finite=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;

type Holding={ticker:string;shares:number;avg_cost:number;closed_at?:string|null};

export default function CIOScenarioLabV13({lang}:{lang:AppLang}){
 const[holdings,setHoldings]=useState<Holding[]>([]);const[market,setMarket]=useState<Record<string,any>>({});const[target,setTarget]=useState("MU");const[amount,setAmount]=useState("500");const[source,setSource]=useState("SGOV");const[loading,setLoading]=useState(true);
 const t=(en:string,th:string)=>lang==="th"?th:en;
 useEffect(()=>{(async()=>{setLoading(true);const p=await fetch("/api/portfolio",{cache:"no-store"}).then(r=>r.json());const hs=(p.holdings??[]).filter((h:Holding)=>!h.closed_at&&Number(h.shares)>0);setHoldings(hs);const tickers=hs.map((h:Holding)=>h.ticker).join(",");if(tickers){const m=await fetch(`/api/holding-market?tickers=${encodeURIComponent(tickers)}`,{cache:"no-store"}).then(r=>r.json());setMarket(m.items??{})}setLoading(false)})()},[]);
 const sim=useMemo(()=>{const rows=holdings.map(h=>{const price=finite(market[h.ticker]?.price)||finite(h.avg_cost);return{ticker:h.ticker,value:price*finite(h.shares)}});const nav=rows.reduce((s,r)=>s+r.value,0);const capital=Math.max(0,finite(amount));const sourceRow=rows.find(r=>r.ticker===source);const sourceAvailable=sourceRow?.value??0;const valid=capital>0&&capital<=sourceAvailable;const after=rows.map(r=>({ticker:r.ticker,currentWeight:nav?100*r.value/nav:0,afterValue:r.ticker===source?r.value-(valid?capital:0):r.value}));const existing=after.find(r=>r.ticker===target);if(existing)existing.afterValue+=valid?capital:0;else after.push({ticker:target,currentWeight:0,afterValue:valid?capital:0});return{nav,capital,sourceAvailable,valid,after:after.map(r=>({...r,afterWeight:nav?100*r.afterValue/nav:0})).sort((a,b)=>b.afterWeight-a.afterWeight),largest:Math.max(...after.map(r=>nav?100*r.afterValue/nav:0),0)}},[holdings,market,target,amount,source]);
 return <section className="card" data-cio-scenario-version="13.0" style={{borderTop:"2px solid var(--accent)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span className="tag">WHAT-IF PORTFOLIO LAB · V13</span><h3 className="sub" style={{margin:"10px 0 4px"}}>{t("Capital-source and rebalance simulation","จำลองแหล่งเงินและผลหลังปรับพอร์ต")}</h3><p className="muted" style={{margin:0}}>{t("Simulation only. It never changes Holdings or sends trades.","เป็นการจำลองเท่านั้น ไม่แก้ Holdings และไม่ส่งคำสั่งซื้อขาย")}</p></div><span className="tag">NO AUTO EXECUTION</span></div>{loading?<div className="notice" style={{marginTop:14}}>Loading portfolio…</div>:<><div className="searchbar" style={{marginTop:14}}><select value={source} onChange={e=>setSource(e.target.value)}>{holdings.map(h=><option key={h.ticker}>{h.ticker}</option>)}</select><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="Amount USD"/><input value={target} onChange={e=>setTarget(e.target.value.toUpperCase())} placeholder="Target ticker"/><span className={`tag ${sim.valid?"":"err"}`}>{sim.valid?"SIMULATION READY":"CHECK CAPITAL"}</span></div><div className="grid cols-4" style={{marginTop:14}}><Metric label="Portfolio NAV" value={money(sim.nav)}/><Metric label="Requested capital" value={money(sim.capital)}/><Metric label={`${source} available`} value={money(sim.sourceAvailable)}/><Metric label="Largest weight after" value={`${sim.largest.toFixed(1)}%`}/></div>{!sim.valid&&<div className="err" style={{marginTop:12}}>{t("Requested capital exceeds the selected funding source or is zero.","จำนวนเงินมากกว่าแหล่งเงินที่เลือกหรือเป็นศูนย์")}</div>}<div className="table-wrap" style={{marginTop:14}}><table className="tbl"><thead><tr><th>Ticker</th><th className="num">Current weight</th><th className="num">After weight</th><th className="num">Change</th></tr></thead><tbody>{sim.after.map(r=><tr key={r.ticker}><td><strong>{r.ticker}</strong></td><td className="num">{r.currentWeight.toFixed(2)}%</td><td className="num">{r.afterWeight.toFixed(2)}%</td><td className={`num ${r.afterWeight-r.currentWeight>=0?"pos":"neg"}`}>{(r.afterWeight-r.currentWeight>=0?"+":"")+(r.afterWeight-r.currentWeight).toFixed(2)}%</td></tr>)}</tbody></table></div><div className="notice" style={{marginTop:14}}>{t("To execute an approved scenario, Portfolio Operations must record the actual SELL and BUY transactions separately so the Trade Ledger remains auditable.","เมื่อต้องการดำเนินการจริง ทีม Portfolio ต้องบันทึก SELL และ BUY แยกกันเพื่อให้ Trade Ledger ตรวจสอบย้อนหลังได้")}</div></>}</section>
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
