"use client";
import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";
import CommitteeMeetingV10 from "./CommitteeMeetingV10";

async function getJson(path:string){const r=await fetch(path,{cache:"no-store",headers:{Accept:"application/json"}});const j=await r.json();if(!r.ok)throw new Error(j?.error||path);return j}
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v||0);

export default function EndToEndInvestmentCommittee({lang}:{lang:AppLang}){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let ok=true;setLoading(true);Promise.allSettled([getJson("/api/v10/cio"),getJson("/api/portfolio"),getJson("/api/portfolio/optimizer"),getJson("/api/portfolio/opportunity-allocation"),getJson("/api/portfolio/cash-buffer")]).then(rs=>{if(!ok)return;const v=rs.map(x=>x.status==="fulfilled"?x.value:{});setData({cio:v[0],portfolio:v[1],optimizer:v[2],allocation:v[3],buffer:v[4]});const n=rs.filter(x=>x.status==="rejected").length;setError(n?`${n} data source(s) unavailable; meeting continued with partial data.`:null)}).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[refresh]);
 const m=useMemo(()=>{const decisions=data?.cio?.decisions??[];const macro=decisions.find((x:any)=>String(x?.desk).toUpperCase()==="MACRO")??{};const raw=`${macro.action??""} ${macro.reason??""}`.toUpperCase();const defensive=/DEFENSIVE|RISK OFF|BEAR|CAUTION/.test(raw),riskOn=/RISK ON|BULL|AGGRESSIVE/.test(raw);const proposals=data?.optimizer?.proposals??[],alloc=data?.allocation?.allocations??[],holdings=(data?.portfolio?.holdings??[]).filter((x:any)=>!x.closed_at);return{posture:defensive?"DEFENSIVE":riskOn?"GROWTH / RISK-ON":"BALANCED / SELECTIVE",cash:defensive?15:riskOn?5:10,open:holdings.length,add:alloc.filter((x:any)=>Number(x?.approvedCapitalUsd)>0).length,trim:proposals.filter((x:any)=>/TRIM|REDUCE/.test(String(x?.action??"").toUpperCase())).length,exit:proposals.filter((x:any)=>/EXIT|SELL/.test(String(x?.action??"").toUpperCase())).length,deployable:Number(data?.allocation?.portfolio?.deployableCapitalUsd??data?.buffer?.gapValue??0)||0,direction:defensive?"Raise cash, trim weak holdings, exit broken theses and wait for better risk/reward.":riskOn?"Deploy selectively into approved themes and high-conviction holdings.":"Keep a balanced book and fund only positive-upside ideas.",macro:macro.reason??"Macro rationale pending."}},[data]);
 return <><section className="card" style={{borderTop:"2px solid var(--accent)",marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:11,letterSpacing:1.2}}>END-TO-END INVESTMENT COMMITTEE</div><h2 className="section" style={{margin:"6px 0"}}>{lang==="th"?"การประชุมบริหารการลงทุนทั้งกองทุน":"FULL FUND INVESTMENT MANDATE"}</h2><p className="muted" style={{margin:0}}>One meeting sets regime, cash target, risk posture, holding actions, opportunity search, funding and the final rebalance package.</p></div><button className="btn" onClick={()=>setRefresh(x=>x+1)} disabled={loading}>{loading?"Consolidating…":"Run Full Fund Meeting"}</button></div>{error&&<div className="notice" style={{marginTop:12}}>⚠ {error}</div>}<div className="grid cols-4" style={{marginTop:14}}><div className="metric"><span>Fund posture</span><strong>{loading?"…":m.posture}</strong></div><div className="metric"><span>Target cash</span><strong>{loading?"…":`${m.cash}%`}</strong></div><div className="metric"><span>Deployable</span><strong>{loading?"…":money(m.deployable)}</strong></div><div className="metric"><span>Open holdings</span><strong>{loading?"…":m.open}</strong></div></div><div className="grid cols-4" style={{marginTop:9}}><div className="metric"><span>ADD / OPEN</span><strong>{loading?"…":m.add}</strong></div><div className="metric"><span>TRIM</span><strong>{loading?"…":m.trim}</strong></div><div className="metric"><span>EXIT</span><strong>{loading?"…":m.exit}</strong></div><div className="metric"><span>Meeting scope</span><strong>8 stages</strong></div></div>{!loading&&<div className="notice" style={{marginTop:12,lineHeight:1.6}}><strong>Strategic direction:</strong> {m.direction}<br/><span className="muted">Macro: {m.macro}</span></div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:8,marginTop:12}}>{["1 Macro & Regime","2 Cash / Risk Budget","3 Holdings Review","4 Theme / Stock Search","5 ADD / TRIM / EXIT","6 Funding Plan","7 Committee Vote","8 Execution & Minutes"].map(x=><div className="tag" style={{padding:"10px 12px"}} key={x}>{x}</div>)}</div></section><CommitteeMeetingV10 lang={lang}/></>
}
