"use client";
import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";

type Action="OPEN NEW"|"ADD EXISTING"|"TRIM"|"EXIT";
type MeetingItem={ticker:string;action:Action;amount:number;reason:string;approved:boolean;status:"APPROVED"|"DEFERRED"|"REJECTED";votes:string[];upside:number|null;conviction:number|null;target:number|null;price:number|null;risks:string[];monitoring:string[];rank:number};
type HoldingReview={ticker:string;weight:number;marketValue:number;pnlPct:number|null;portfolio:string;valuation:string;risk:string;liquidity:string;decision:string;reason:string};
const desks=["CIO","MACRO","RESEARCH","RISK","QUANT","PORTFOLIO","TREASURY"];
const finite=(v:unknown):number|null=>{if(v===null||v===undefined||String(v).trim()==="")return null;const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)?n:null};
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
const usd=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v);
async function getJson(path:string,init?:RequestInit){const r=await fetch(path,{cache:"no-store",headers:{Accept:"application/json","Content-Type":"application/json",...(init?.headers??{})},...init});const raw=await r.text();let json:any={};try{json=raw?JSON.parse(raw):{}}catch{throw new Error(`${path} returned invalid JSON`)}if(!r.ok)throw new Error(json?.error??`${path} returned ${r.status}`);return json}

export default function EndToEndInvestmentCommittee({lang}:{lang:AppLang}){
 const[data,setData]=useState<any>(null),[cycle,setCycle]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<Record<string,boolean>>({}),[submitting,setSubmitting]=useState(false),[execution,setExecution]=useState<any>(null);
 useEffect(()=>{let active=true;setLoading(true);setError(null);setExecution(null);Promise.allSettled([getJson("/api/macro/intelligence"),getJson("/api/v10/cio"),getJson("/api/portfolio"),getJson("/api/portfolio/optimizer"),getJson("/api/portfolio/opportunity-allocation"),getJson("/api/portfolio/cash-buffer")]).then(results=>{if(!active)return;const values=results.map(x=>x.status==="fulfilled"?x.value:{});setData({macro:values[0],cio:values[1],portfolio:values[2],optimizer:values[3],allocation:values[4],buffer:values[5]});const failed=results.filter(x=>x.status==="rejected").length;setError(failed?`${failed} meeting source(s) unavailable; unresolved evidence was excluded.`:null);setSelected({})}).finally(()=>active&&setLoading(false));return()=>{active=false}},[cycle]);
 const meeting=useMemo(()=>{
  const holdings=(Array.isArray(data?.portfolio?.holdings)?data.portfolio.holdings:[]).filter((x:any)=>!x.closed_at);
  const macroScore=finite(data?.macro?.regime?.score)??50;
  const macroLabel=String(data?.macro?.regime?.classification??data?.macro?.regime?.label??"NEUTRAL").toUpperCase();
  const riskOff=macroScore<40||/BEAR|RISK.OFF|DEFENSIVE/.test(macroLabel),riskOn=macroScore>=65||/BULL|RISK.ON|EXPANSION/.test(macroLabel);
  const posture=riskOff?"REDUCE RISK / RAISE CASH":riskOn?"ADVANCE SELECTIVELY":"BALANCED / SELECTIVE",cashTarget=riskOff?15:riskOn?5:10;
  const macroDrivers=[{label:"Trend",score:clamp(Math.round(macroScore*.95)),view:macroScore>=55?"supportive":"soft"},{label:"Liquidity",score:clamp(Math.round(macroScore*.88)),view:macroScore>=50?"adequate":"tight"},{label:"Breadth",score:clamp(Math.round(macroScore*.82)),view:macroScore>=60?"broad":"narrow"},{label:"Volatility",score:clamp(Math.round(100-(100-macroScore)*.72)),view:riskOff?"elevated":"contained"},{label:"Valuation",score:clamp(Math.round(42+macroScore*.42)),view:riskOn?"acceptable":"selective"},{label:"Sentiment",score:clamp(Math.round(50+(macroScore-50)*.65)),view:macroScore>70?"crowded":macroScore<35?"fearful":"neutral"}];
  const transcript=[{desk:"CIO",text:riskOff?"Protect capital first; raise cash and remove broken theses.":riskOn?"Advance only into high-conviction ideas with defined risk.":"Maintain a balanced book and approve only asymmetric opportunities."},{desk:"MACRO",text:`Regime is ${macroLabel}; liquidity and breadth justify a ${posture.toLowerCase()} stance.`},{desk:"RESEARCH",text:"Present a ranked shortlist, not a single stock. Approved, deferred and rejected ideas remain visible."},{desk:"RISK",text:riskOff?"Cut exposure and concentration before adding risk.":"Approve only with position-size controls and explicit invalidation levels."},{desk:"QUANT",text:"Rank by expected return, conviction, valuation and evidence quality."},{desk:"PORTFOLIO",text:"Every holding receives KEEP, WATCH, ADD, TRIM or EXIT opinion even when no trade is proposed."},{desk:"TREASURY",text:"SGOV remains reserve capital until a named destination is human-approved."}];
  const marketValue=holdings.reduce((s:number,h:any)=>s+Math.max(0,(finite(h?.shares)??0)*(finite(h?.price??h?.avg_cost)??0)),0);
  const holdingReviews:HoldingReview[]=holdings.map((h:any)=>{const ticker=String(h?.ticker??"").toUpperCase(),shares=Math.max(0,finite(h?.shares)??0),price=finite(h?.price??h?.current_price??h?.avg_cost)??0,cost=finite(h?.avg_cost),mv=shares*price,weight=marketValue>0?mv/marketValue*100:0,pnl=cost&&cost>0?((price/cost)-1)*100:null;const over=weight>20,weak=pnl!=null&&pnl<-12,strong=pnl!=null&&pnl>18;const decision=over?"TRIM REVIEW":weak?"WATCH / THESIS REVIEW":strong?"KEEP WINNER":"KEEP";return{ticker,weight,marketValue:mv,pnlPct:pnl,portfolio:decision,valuation:pnl==null?"DATA LIMITED":pnl>25?"PREMIUM / WATCH":pnl<-10?"DISCOUNT / VERIFY THESIS":"FAIR RANGE",risk:over?"CONCENTRATION HIGH":weak?"DRAWDOWN WATCH":"WITHIN POLICY",liquidity:shares>0&&price>0?"TRADEABLE":"VERIFY PRICE",decision,reason:over?"Weight exceeds the single-name review zone.":weak?"Loss threshold requires thesis and catalyst review.":strong?"Winner remains within policy; do not trim mechanically.":"No evidence currently justifies a portfolio change."}}).sort((a,b)=>b.weight-a.weight);
  const optimizer=Array.isArray(data?.optimizer?.proposals)?data.optimizer.proposals:[];
  const portfolioItems:MeetingItem[]=optimizer.flatMap((x:any,i:number)=>{const ticker=String(x?.ticker??"").trim().toUpperCase(),raw=String(x?.action??"").toUpperCase();if(!ticker||ticker==="LIQUIDITY")return[];const action:Action|null=/TRIM|REDUCE/.test(raw)?"TRIM":/EXIT|SELL/.test(raw)?"EXIT":/ADD|BUY/.test(raw)?"ADD EXISTING":null;if(!action)return[];const amount=Math.max(0,finite(x?.capitalUsd??x?.amountUsd)??0),approved=(action==="TRIM"||action==="EXIT")?(riskOff||finite(x?.score)!=null):(riskOn||macroScore>=45);return[{ticker,action,amount,reason:String(x?.reason??"Portfolio review recommendation."),approved,status:approved?"APPROVED":"DEFERRED",votes:deskVotes(action,approved,riskOff),upside:finite(x?.expectedReturnPct),conviction:finite(x?.score),target:finite(x?.targetPrice),price:finite(x?.price),risks:["Position concentration","Thesis deterioration","Correlation shock"],monitoring:["Weight drift","Price trend","Earnings revisions"],rank:i+1}]});
  const held=new Set(holdings.map((x:any)=>String(x?.ticker??"").toUpperCase())),allocations=Array.isArray(data?.allocation?.allocations)?data.allocation.allocations:[],rejected=Array.isArray(data?.allocation?.rejected)?data.allocation.rejected:[];
  const candidateMap=new Map<string,any>();for(const x of allocations)candidateMap.set(String(x?.ticker??"").toUpperCase(),{...x,_source:"allocation"});for(const x of rejected)if(!candidateMap.has(String(x?.ticker??"").toUpperCase()))candidateMap.set(String(x?.ticker??"").toUpperCase(),{...x,_source:"rejected"});
  const rawCandidates=[...candidateMap.values()].filter((x:any)=>x?.ticker).sort((a:any,b:any)=>(finite(b?.conviction)??0)-(finite(a?.conviction)??0)||(finite(b?.expectedReturnPct)??-999)-(finite(a?.expectedReturnPct)??-999)).slice(0,8);
  const strategyItems:MeetingItem[]=rawCandidates.map((x:any,i:number)=>{const ticker=String(x?.ticker??"").toUpperCase(),amount=Math.max(0,finite(x?.approvedCapitalUsd)??0),action:Action=held.has(ticker)?"ADD EXISTING":"OPEN NEW",upside=finite(x?.expectedReturnPct),conviction=finite(x?.conviction),target=finite(x?.targetPrice),price=finite(x?.currentPrice??x?.price),approved=x?._source==="allocation"&&amount>0&&!riskOff&&(upside==null||upside>=8)&&(conviction==null||conviction>=60)&&(target==null||price==null||target>price),status:MeetingItem["status"]=approved?"APPROVED":x?._source==="allocation"?"DEFERRED":"REJECTED";return{ticker,action,amount,reason:String(x?.thesis??x?.reason??"Candidate did not clear all allocation gates."),approved,status,votes:deskVotes(action,approved,riskOff),upside,conviction,target,price,risks:Array.isArray(x?.risks)?x.risks.map(String):["Execution risk","Valuation compression","Catalyst delay"],monitoring:Array.isArray(x?.monitoring)?x.monitoring.map(String):["Revenue growth","Free cash flow","Guidance and valuation"],rank:i+1}});
  const approved=[...portfolioItems,...strategyItems].filter(x=>x.approved),reserve=finite(data?.allocation?.portfolio?.deployableCapitalUsd??data?.buffer?.gapValue)??0,concentration=clamp(100-Math.min(55,holdings.length<8?38:12)),diversification=clamp(45+holdings.length*2.2),quality=clamp(Math.round(62+macroScore*.18)),liquidity=clamp(Math.round(78+Math.min(15,reserve/100))),riskScore=clamp(Math.round(100-(100-macroScore)*.58-(holdings.length<8?12:0))),health=clamp(Math.round(quality*.30+diversification*.22+liquidity*.18+riskScore*.18+macroScore*.12)),opportunity=clamp(Math.round(macroScore*.55+(strategyItems.length?72:44)*.45)),consensus=approved.length?clamp(Math.round(70+approved.length*5)):clamp(Math.round(48+macroScore*.25));
  return{holdings,holdingReviews,macroScore,macroLabel,posture,cashTarget,macroDrivers,transcript,portfolioItems,strategyItems,approved,reserve,marketValue,health,quality,diversification,liquidity,riskScore,opportunity,consensus,concentration,riskOff};
 },[data]);
 const key=(x:MeetingItem)=>`${x.action}:${x.ticker}`;const selectedItems=meeting.approved.filter(x=>selected[key(x)]),buys=selectedItems.filter(x=>x.action==="OPEN NEW"||x.action==="ADD EXISTING"),sells=selectedItems.filter(x=>x.action==="TRIM"||x.action==="EXIT"),buyTotal=buys.reduce((s,x)=>s+x.amount,0),sellTotal=sells.reduce((s,x)=>s+x.amount,0),reserveNeeded=Math.max(0,buyTotal-sellTotal),reserveUsed=Math.min(meeting.reserve,reserveNeeded),funding=buys.length?`TRIM SGOV ${usd(reserveUsed)} → ${buys.map(x=>`${x.ticker} ${usd(x.amount)}`).join(" + ")}`:`KEEP ${usd(meeting.reserve)} IN SGOV — NO SALE AUTHORIZED`,projectedCash=Math.max(0,meeting.reserve+sellTotal-buyTotal),projectedHoldings=meeting.holdings.length+selectedItems.filter(x=>x.action==="OPEN NEW").length-selectedItems.filter(x=>x.action==="EXIT").length;
 const selectApproved=()=>setSelected(Object.fromEntries(meeting.approved.map(x=>[key(x),true]))),toggle=(x:MeetingItem)=>setSelected(s=>({...s,[key(x)]:!s[key(x)]}));
 async function submit(){if(!selectedItems.length)return;setSubmitting(true);setError(null);try{const result=await getJson("/api/portfolio/rebalance-execution",{method:"POST",body:JSON.stringify({humanApproved:true,humanApprovedBy:"portfolio_owner",meetingCode:`IC-${new Date().toISOString().slice(0,10)}`,reserveTicker:"SGOV",deployable:meeting.reserve,portfolioBefore:data?.portfolio??{},macro:{label:meeting.macroLabel,score:meeting.macroScore,posture:meeting.posture},items:selectedItems})});setExecution(result)}catch(e:any){setError(e?.message??"Execution package failed")}finally{setSubmitting(false)}}
 const agendaStyle={border:"1px solid rgba(119,137,255,.28)",borderRadius:18,padding:18,marginTop:14,background:"rgba(7,18,45,.52)"} as const,summaryStyle={cursor:"pointer",fontWeight:900,fontSize:"1.02rem",letterSpacing:.3} as const;
 return <section className="card" style={{borderTop:"2px solid var(--accent)"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="muted" style={{fontSize:11,letterSpacing:1.4}}>INSTITUTIONAL AI FUND OPERATING SYSTEM · SINGLE MEETING STATE</div><h2 className="section" style={{margin:"6px 0"}}>{lang==="th"?"กองทุนอัจฉริยะและคณะกรรมการลงทุน":"INTELLIGENT FUND COMMITTEE"}</h2><p className="muted" style={{margin:0}}>One governed meeting: macro, every holding, ranked research shortlist, debate, funding and execution.</p></div><button className="btn" onClick={()=>setCycle(x=>x+1)} disabled={loading}>{loading?"Running meeting…":"Run Full Fund Meeting"}</button></div>
  {error&&<div className="notice" style={{marginTop:12}}>⚠ {error}</div>}{execution&&<div className="notice" style={{marginTop:12,borderColor:"rgba(72,228,167,.45)"}}>✓ Package {execution.package?.packageId} · {execution.package?.status}</div>}
  <section style={{...agendaStyle,background:"linear-gradient(145deg,rgba(20,33,75,.78),rgba(7,18,45,.66))"}}><div className="muted" style={{fontSize:11,letterSpacing:1.2}}>CIO EXECUTIVE VIEW</div><h3 style={{margin:"5px 0"}}>Fund intelligence dashboard</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(145px,1fr))",gap:12,marginTop:14}}><Gauge label="Fund health" value={meeting.health} note="Institutional composite"/><Gauge label="Market opportunity" value={meeting.opportunity} note="Selective opportunity"/><Gauge label="Portfolio quality" value={meeting.quality} note="Quality composite"/><Gauge label="Risk control" value={meeting.riskScore} note="Policy control"/><Gauge label="Committee consensus" value={meeting.consensus} note={`${meeting.approved.length} approved ideas`}/></div></section>
  <details style={agendaStyle} open><summary style={summaryStyle}>1 · MACRO, REGIME & SENTIMENT</summary><div style={{marginTop:14}}><div className="grid cols-4"><Metric l="Regime" v={meeting.macroLabel}/><Metric l="Macro score" v={`${meeting.macroScore}/100`}/><Metric l="Fund posture" v={meeting.posture}/><Metric l="Target cash" v={`${meeting.cashTarget}%`}/></div><DriverChart rows={meeting.macroDrivers}/><Transcript rows={meeting.transcript}/></div></details>
  <details style={agendaStyle}><summary style={summaryStyle}>2 · PORTFOLIO, VALUATION, RISK & LIQUIDITY REVIEW</summary><div style={{marginTop:14}}><div className="grid cols-4"><Metric l="Open holdings" v={String(meeting.holdings.length)}/><Metric l="Market value" v={usd(meeting.marketValue)}/><Metric l="Trade proposals" v={String(meeting.portfolioItems.length)}/><Metric l="Reserve" v={usd(meeting.reserve)}/></div><RiskPanel values={[{l:"Diversification",v:meeting.diversification},{l:"Concentration control",v:meeting.concentration},{l:"Liquidity",v:meeting.liquidity},{l:"Portfolio quality",v:meeting.quality}]}/><HoldingTable rows={meeting.holdingReviews}/><Items items={meeting.portfolioItems} selected={selected} toggle={toggle}/></div></details>
  <details style={agendaStyle}><summary style={summaryStyle}>3 · INVESTMENT STRATEGY, RESEARCH & CAPITAL ALLOCATION</summary><div style={{marginTop:14}}><p className="notice"><strong>Research funnel:</strong> {data?.allocation?.sources?.watchlistCandidates??0} watchlist candidates · {data?.allocation?.sources?.discoveredCandidates??"—"} discovered · {meeting.strategyItems.length} presented to committee · {meeting.strategyItems.filter(x=>x.approved).length} approved.</p><CandidateRanking items={meeting.strategyItems}/><Items items={meeting.strategyItems} selected={selected} toggle={toggle}/>{!meeting.strategyItems.length&&<div className="notice">No candidate was available from the research engine. Reserve remains in SGOV.</div>}</div></details>
  <details style={agendaStyle}><summary style={summaryStyle}>4 · FINAL RESOLUTION, FUNDING & EXECUTION</summary><div style={{marginTop:14}}><div className="grid cols-4"><Metric l="Approved ideas" v={String(meeting.approved.length)}/><Metric l="Human selected" v={String(selectedItems.length)}/><Metric l="Buy total" v={usd(buyTotal)}/><Metric l="Capital released" v={usd(sellTotal)}/></div><CapitalFlow reserve={meeting.reserve} buys={buys} reserveUsed={reserveUsed}/><div className="notice" style={{marginTop:12,borderColor:"rgba(72,228,167,.4)"}}><strong>Funding plan:</strong> {funding}</div><div className="grid cols-3" style={{marginTop:10}}><Metric l="Projected holdings" v={String(projectedHoldings)}/><Metric l="Projected reserve" v={usd(projectedCash)}/><Metric l="Execution state" v={execution?String(execution.package?.status??"SUBMITTED"):selectedItems.length?"READY FOR HUMAN SUBMISSION":"NO AUTHORIZED TRADE"}/></div><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:12}}><button className="btn ghost" onClick={selectApproved} disabled={!meeting.approved.length}>Select All Approved</button><button className="btn" onClick={submit} disabled={!selectedItems.length||submitting}>{submitting?"Submitting…":`Submit Rebalance Package (${selectedItems.length})`}</button></div></div></details>
 </section>
}
function Gauge({label,value,note}:{label:string;value:number;note:string}){const v=clamp(value);return <div className="metric" style={{textAlign:"center",padding:12}}><svg viewBox="0 0 110 70" role="img" aria-label={`${label} ${v} out of 100`} style={{width:"100%",maxWidth:145}}><path d="M13 58 A42 42 0 0 1 97 58" fill="none" stroke="rgba(130,145,190,.22)" strokeWidth="10" strokeLinecap="round"/><path d="M13 58 A42 42 0 0 1 97 58" fill="none" stroke="#748cff" strokeWidth="10" strokeLinecap="round" pathLength="100" strokeDasharray={`${v} ${100-v}`}/><text x="55" y="54" textAnchor="middle" fill="currentColor" fontSize="20" fontWeight="800">{v}</text></svg><strong style={{display:"block",fontSize:14}}>{label}</strong><small>{note}</small></div>}
function DriverChart({rows}:{rows:{label:string;score:number;view:string}[]}){return <div style={{display:"grid",gap:8,marginTop:12}}>{rows.map(x=><div key={x.label} style={{display:"grid",gridTemplateColumns:"90px 1fr 44px",gap:10,alignItems:"center"}}><span className="muted" style={{fontSize:12}}>{x.label}</span><div style={{height:9,borderRadius:99,background:"rgba(130,145,190,.16)",overflow:"hidden"}}><div style={{height:"100%",width:`${clamp(x.score)}%`,background:"linear-gradient(90deg,#4f8cff,#9a62ff)",borderRadius:99}}/></div><strong style={{fontSize:12,textAlign:"right"}}>{x.score}</strong></div>)}</div>}
function RiskPanel({values}:{values:{l:string;v:number}[]}){return <div className="grid cols-4" style={{marginTop:12}}>{values.map(x=><div className="metric" key={x.l}><span>{x.l}</span><strong>{x.v}/100</strong><div style={{height:8,borderRadius:99,background:"rgba(130,145,190,.16)",overflow:"hidden",marginTop:8}}><div style={{height:"100%",width:`${clamp(x.v)}%`,background:"linear-gradient(90deg,#4f8cff,#9a62ff)"}}/></div></div>)}</div>}
function CapitalFlow({reserve,buys,reserveUsed}:{reserve:number;buys:MeetingItem[];reserveUsed:number}){return <div style={{display:"flex",alignItems:"center",gap:10,flexWrap:"wrap",marginTop:14}}><div className="metric"><span>Source</span><strong>SGOV</strong><small>{usd(reserve)}</small></div><span>→</span><div className="metric"><span>Authorized capital</span><strong>{usd(reserveUsed)}</strong></div><span>→</span>{buys.length?buys.map(x=><div className="metric" key={x.ticker}><span>{x.action}</span><strong>{x.ticker}</strong><small>{usd(x.amount)}</small></div>):<div className="metric"><span>Destination</span><strong>KEEP SGOV</strong></div>}</div>}
function HoldingTable({rows}:{rows:HoldingReview[]}){return <div style={{display:"grid",gap:8,marginTop:14}}>{rows.map(x=><article className="metric" key={x.ticker}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{x.ticker}</strong><b>{x.decision}</b></div><small>Weight {x.weight.toFixed(1)}% · Value {usd(x.marketValue)} · P/L {x.pnlPct==null?"—":`${x.pnlPct.toFixed(1)}%`}</small><div className="grid cols-4" style={{marginTop:8}}><Metric l="Portfolio" v={x.portfolio}/><Metric l="Valuation" v={x.valuation}/><Metric l="Risk" v={x.risk}/><Metric l="Liquidity" v={x.liquidity}/></div><small>{x.reason}</small></article>)}</div>}
function CandidateRanking({items}:{items:MeetingItem[]}){return <div style={{display:"grid",gap:8,marginTop:12}}>{items.map(x=><div className="metric" key={x.ticker} style={{display:"grid",gridTemplateColumns:"40px 1fr auto",gap:10,alignItems:"center"}}><strong>#{x.rank}</strong><div><strong>{x.ticker}</strong><small style={{display:"block"}}>Expected {x.upside==null?"—":`${x.upside.toFixed(1)}%`} · Conviction {x.conviction==null?"—":x.conviction}</small></div><b>{x.status}</b></div>)}</div>}
function deskVotes(action:Action,approved:boolean,riskOff:boolean){return desks.map(d=>{if(!approved)return `${d}: ${d==="TREASURY"?"KEEP CASH":"HOLD / DEFER"}`;if(d==="RISK")return `${d}: ${riskOff?"REDUCE / LIMIT":"SIZE CONTROL"}`;if(d==="TREASURY")return `${d}: ${action==="TRIM"||action==="EXIT"?"RELEASE CAPITAL":"FUND IF SELECTED"}`;if(d==="RESEARCH")return `${d}: ${action==="TRIM"||action==="EXIT"?"THESIS REVIEW":"BUY"}`;if(d==="PORTFOLIO")return `${d}: ${action==="TRIM"||action==="EXIT"?"REBALANCE":"PORTFOLIO FIT"}`;return `${d}: SUPPORT`})}
function Metric({l,v}:{l:string;v:string}){return <div className="metric"><span>{l}</span><strong style={{fontSize:17}}>{v}</strong></div>}
function Transcript({rows}:{rows:{desk:string;text:string}[]}){return <div style={{display:"grid",gap:8,marginTop:12}}>{rows.map(x=><div className="notice" key={x.desk}><strong>{x.desk}:</strong> {x.text}</div>)}</div>}
function Items({items,selected,toggle}:{items:MeetingItem[];selected:Record<string,boolean>;toggle:(x:MeetingItem)=>void}){return <div style={{display:"grid",gap:10,marginTop:12}}>{items.map(x=>{const k=`${x.action}:${x.ticker}`;return <article className="metric" key={k} style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) auto",gap:12,alignItems:"start"}}><div><span>#{x.rank} · {x.action}</span><strong style={{display:"block",fontSize:20}}>{x.ticker} · {usd(x.amount)}</strong><small>{x.reason}</small><div className="grid cols-3" style={{marginTop:8}}><Metric l="Price" v={usd(x.price)}/><Metric l="Target" v={usd(x.target)}/><Metric l="Expected return" v={x.upside==null?"—":`${x.upside.toFixed(1)}%`}/></div><div className="notice" style={{marginTop:8}}><strong>Risks:</strong> {x.risks.join(" · ")}<br/><strong>Monitoring:</strong> {x.monitoring.join(" · ")}</div><div style={{marginTop:8,fontSize:11}}>{x.votes.join(" · ")}</div></div><label style={{display:"grid",gap:6,justifyItems:"center"}}><input type="checkbox" checked={Boolean(selected[k])} disabled={!x.approved} onChange={()=>toggle(x)}/><b style={{fontSize:11}}>{x.status}</b></label></article>})}</div>}
