"use client";

import { useMemo, useState } from "react";
import type { AppLang } from "../page";
import styles from "./FundOperatingCycle.module.css";

type StageState="idle"|"running"|"done"|"warning";
type Kind="ADD_EXISTING"|"ADD_NEW"|"HOLD"|"TRIM"|"EXIT"|"CASH";
type Action={kind:Kind;ticker:string;label:string;reason:string;amount?:number|null;weight?:number|null;score?:number|null};
type Stage={key:string;en:string;th:string;endpoint:string;state:StageState;detail?:string};

const t=(l:AppLang,en:string,th:string)=>l==="th"?th:en;
const finite=(v:unknown)=>{const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)?n:null};
const money=(v:number|null)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const txt=(...v:unknown[])=>v.find(x=>typeof x==="string"&&x.trim()) as string|undefined;
const stages0:Stage[]=[
 {key:"macro",en:"Macro & regime",th:"Macro และสภาวะตลาด",endpoint:"/api/macro/intelligence",state:"idle"},
 {key:"portfolio",en:"Holdings & market truth",th:"Holdings และราคาตลาด",endpoint:"/api/portfolio",state:"idle"},
 {key:"integrity",en:"Admin integrity diagnostics",th:"การตรวจสอบข้อมูลระดับผู้ดูแล",endpoint:"/api/portfolio/integrity",state:"idle"},
 {key:"liquidity",en:"Liquidity & reserve",th:"สภาพคล่องและเงินสำรอง",endpoint:"/api/portfolio/cash-buffer",state:"idle"},
 {key:"optimizer",en:"Portfolio construction",th:"การจัดพอร์ต",endpoint:"/api/portfolio/optimizer",state:"idle"},
 {key:"opportunity",en:"New opportunities",th:"โอกาสลงทุนใหม่",endpoint:"/api/portfolio/opportunity-allocation",state:"idle"},
 {key:"committee",en:"Investment committee",th:"คณะกรรมการลงทุน",endpoint:"/api/committee/audit",state:"idle"},
 {key:"cio",en:"Final CIO resolution",th:"มติสุดท้ายของ CIO",endpoint:"/api/v10/cio",state:"idle"},
];
async function read(endpoint:string){const r=await fetch(endpoint,{cache:"no-store"});let body:any=null;try{body=await r.json()}catch{}return{ok:r.ok,status:r.status,body}}
function optimizerAction(raw:any):Action|null{const ticker=String(raw?.ticker??"").toUpperCase();if(!ticker||ticker==="LIQUIDITY"||ticker==="OPPORTUNITY PIPELINE")return null;const label=String(raw?.action??"HOLD").toUpperCase();const kind:Kind=label.includes("TRIM")||label.includes("REDUCE")?"TRIM":label.includes("EXIT")?"EXIT":"HOLD";return{kind,ticker,label,reason:txt(raw?.reason)??"Portfolio policy review completed.",amount:finite(raw?.capitalUsd),weight:finite(raw?.targetWeightPct)}}
function allocationAction(raw:any,held:Set<string>):Action|null{const ticker=String(raw?.ticker??"").toUpperCase();if(!ticker)return null;const amount=finite(raw?.approvedCapitalUsd)??0;return{kind:held.has(ticker)?"ADD_EXISTING":"ADD_NEW",ticker,label:amount>0?"COMMITTEE APPROVED":"WAITING FOR CAPITAL",reason:txt(raw?.thesis,raw?.reason)??"Candidate cleared the evidence and committee gates.",amount,weight:finite(raw?.proposedWeightPct),score:finite(raw?.conviction)}}

export default function FundOperatingCycleV2({lang}:{lang:AppLang}){
 const[stages,setStages]=useState<Stage[]>(stages0);const[running,setRunning]=useState(false);const[actions,setActions]=useState<Action[]>([]);const[summary,setSummary]=useState<any>(null);const[warnings,setWarnings]=useState<string[]>([]);const[completed,setCompleted]=useState<string|null>(null);
 const groups=useMemo(()=>{const g:Record<Kind,Action[]>={ADD_EXISTING:[],ADD_NEW:[],HOLD:[],TRIM:[],EXIT:[],CASH:[]};actions.forEach(a=>g[a.kind].push(a));return g},[actions]);
 async function run(){setRunning(true);setActions([]);setSummary(null);setWarnings([]);setCompleted(null);setStages(stages0.map(s=>({...s,state:"idle",detail:undefined})));const results:Record<string,any>={};const notices:string[]=[];
  for(const stage of stages0){setStages(p=>p.map(s=>s.key===stage.key?{...s,state:"running"}:s));const r=await read(stage.endpoint);results[stage.key]=r.body;const adminMissing=stage.key==="integrity"&&r.status===503;const detail=adminMissing?t(lang,"Admin diagnostic unavailable; meeting continues","ไม่มีสิทธิ์ตรวจสอบระดับผู้ดูแล แต่การประชุมยังดำเนินต่อ"):r.ok?`HTTP ${r.status}`:`HTTP ${r.status} · ${txt(r.body?.error,r.body?.message)??"Unavailable"}`;setStages(p=>p.map(s=>s.key===stage.key?{...s,state:r.ok?"done":"warning",detail}:s));if(!r.ok)notices.push(`${t(lang,stage.en,stage.th)}: ${detail}`)}
  const holdings=Array.isArray(results.portfolio?.holdings)?results.portfolio.holdings.filter((h:any)=>!h.closed_at):[];const held=new Set<string>(holdings.map((h:any)=>String(h.ticker??"").toUpperCase()));const list:Action[]=[];
  for(const p of Array.isArray(results.optimizer?.proposals)?results.optimizer.proposals:[]){const a=optimizerAction(p);if(a)list.push(a)}
  for(const a0 of Array.isArray(results.opportunity?.allocations)?results.opportunity.allocations:[]){const a=allocationAction(a0,held);if(a)list.push(a)}
  const reserveLabel=txt(results.liquidity?.action,results.optimizer?.proposals?.[0]?.action);if(reserveLabel)list.push({kind:"CASH",ticker:"RESERVE",label:reserveLabel,reason:txt(results.optimizer?.proposals?.[0]?.reason)??"Liquidity policy result.",amount:Math.abs(finite(results.liquidity?.gapValue)??0),weight:finite(results.liquidity?.targetPct)});
  setActions(Array.from(new Map(list.map(a=>[`${a.kind}:${a.ticker}`,a])).values()));setSummary({posture:txt(results.cio?.posture,results.cio?.status)??"HOLD / VERIFY",readiness:finite(results.cio?.readinessPct??results.cio?.readiness)??0,regime:txt(results.liquidity?.regime?.classification,results.macro?.regime?.classification,results.macro?.classification)??"—",nav:finite(results.liquidity?.totalNav??results.optimizer?.portfolio?.nav??results.opportunity?.portfolio?.nav),reserve:finite(results.liquidity?.bufferPct??results.optimizer?.portfolio?.bufferPct??results.opportunity?.portfolio?.bufferPct)});setWarnings(notices);setCompleted(new Date().toISOString());setRunning(false)}
 return <section className={styles.shell}><div className={styles.hero}><div><div className={styles.eyebrow}>ONE-CLICK FUND OPERATING CYCLE</div><h2>{t(lang,"Convene the entire fund","ประชุมกองทุนทั้งระบบ")}</h2><p>{t(lang,"One meeting runs every desk and returns one concise action plan.","กดครั้งเดียวเพื่อรันทุกทีมและรับแผนปฏิบัติการฉบับเดียว")}</p></div><button className={styles.run} onClick={run} disabled={running}>{running?t(lang,"Meeting in progress…","กำลังประชุม…"):t(lang,"Convene full fund meeting","เริ่มประชุมกองทุนทั้งหมด")}</button></div>
 <div className={styles.stages}>{stages.map((s,i)=><div className={`${styles.stage} ${styles[s.state]}`} key={s.key}><span>{i+1}</span><div><strong>{t(lang,s.en,s.th)}</strong><small>{s.detail??t(lang,"Waiting","รอเริ่ม")}</small></div></div>)}</div>
 {summary&&<><div className={styles.executive}><Metric label={t(lang,"CIO posture","ท่าที CIO")} value={summary.posture}/><Metric label={t(lang,"Readiness","ความพร้อม")} value={`${summary.readiness}%`}/><Metric label={t(lang,"Regime","สภาวะตลาด")} value={summary.regime}/><Metric label="NAV" value={money(summary.nav)}/><Metric label={t(lang,"Liquidity reserve","เงินสำรอง")} value={summary.reserve==null?"—":`${summary.reserve.toFixed(1)}%`}/><Metric label={t(lang,"Execution","การดำเนินการ")} value={t(lang,"HUMAN APPROVAL","มนุษย์อนุมัติ")}/></div>
 <div className={styles.actionGrid}><Group title={t(lang,"Add existing holdings","ซื้อเพิ่มหุ้นที่มีอยู่")} tone="green" a={groups.ADD_EXISTING} empty={t(lang,"No existing holding cleared an add","ไม่มีหุ้นเดิมผ่านเกณฑ์ซื้อเพิ่ม")}/><Group title={t(lang,"Open new positions","เปิดหุ้นใหม่")} tone="cyan" a={groups.ADD_NEW} empty={t(lang,"No new position cleared the committee","ไม่มีหุ้นใหม่ผ่านคณะกรรมการ")}/><Group title={t(lang,"Hold / watch","ถือ / ติดตาม")} tone="blue" a={groups.HOLD} empty={t(lang,"No hold instruction","ไม่มีคำสั่งถือ")}/><Group title={t(lang,"Trim","ลดน้ำหนัก")} tone="amber" a={groups.TRIM} empty={t(lang,"No trim required","ไม่ต้องลดน้ำหนัก")}/><Group title={t(lang,"Exit","ออกจากสถานะ")} tone="red" a={groups.EXIT} empty={t(lang,"No exit required","ไม่มีหุ้นที่ต้องออก")}/><Group title={t(lang,"Cash & reserve","เงินสดและเงินสำรอง")} tone="purple" a={groups.CASH} empty={t(lang,"Maintain current reserve","รักษาเงินสำรองปัจจุบัน")}/></div>
 <div className={styles.nextStep}><strong>{t(lang,"What happens next","ขั้นตอนถัดไป")}</strong><ol><li>{t(lang,"Review only the named securities above.","ตรวจเฉพาะหลักทรัพย์ที่มีชื่อด้านบน")}</li><li>{t(lang,"Approve or reject each proposal.","อนุมัติหรือปฏิเสธแต่ละข้อเสนอ")}</li><li>{t(lang,"Approved actions move to the transaction form; nothing executes automatically.","รายการที่อนุมัติจึงส่งต่อไปแบบฟอร์มธุรกรรม ระบบไม่ซื้อขายอัตโนมัติ")}</li></ol></div>
 {warnings.length>0&&<details className={styles.warning}><summary>{t(lang,"Diagnostics and warnings","รายละเอียดการตรวจสอบและคำเตือน")}</summary>{warnings.map(w=><div key={w}>• {w}</div>)}</details>}<div className={styles.timestamp}>{t(lang,"Completed","เสร็จสิ้น")} · {completed?new Date(completed).toLocaleString():"—"}</div></>}</section>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Group({title,tone,a,empty}:{title:string;tone:string;a:Action[];empty:string}){return <div className={`${styles.group} ${styles[tone]}`}><h3>{title}<span>{a.length}</span></h3>{a.length?a.map(x=><div className={styles.action} key={`${x.kind}-${x.ticker}`}><div><strong>{x.ticker}</strong><span>{x.label}</span></div><p>{x.reason}</p><small>{x.amount&&x.amount>0?money(x.amount):""}{x.weight!=null?` · ${x.weight.toFixed(1)}% target`:""}{x.score!=null?` · ${x.score}/100`:""}</small></div>):<p className={styles.empty}>{empty}</p>}</div>}
