"use client";
import {useEffect,useMemo,useState} from"react";
import {money}from"./format";

type Holding={ticker:string;shares:number;avg_cost:number;closed_at?:string|null};
const pc=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`;

export default function HoldingsMarketMonitor(){
 const[holdings,setHoldings]=useState<Holding[]>([]),[market,setMarket]=useState<Record<string,any>>({}),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const p=await fetch("/api/portfolio").then(r=>r.json());const hs=(p.holdings??[]).filter((h:Holding)=>!h.closed_at);setHoldings(hs);const tickers=Array.from(new Set(hs.map((h:Holding)=>h.ticker)));if(tickers.length){const m=await fetch(`/api/holding-market?tickers=${encodeURIComponent(tickers.join(","))}`).then(r=>r.json());setMarket(m.items??{})}}finally{setLoading(false)}})()},[]);
 const nav=useMemo(()=>holdings.reduce((s,h)=>s+(market[h.ticker]?.price??h.avg_cost)*h.shares,0),[holdings,market]);
 if(loading)return <div className="card"><span className="spinner"/> Loading holdings market intelligence…</div>;
 if(!holdings.length)return null;
 return <div className="card"><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"baseline",flexWrap:"wrap"}}><div><h2 className="section" style={{margin:0}}>📈 Holdings Market Monitor</h2><p className="muted" style={{fontSize:12,marginTop:6}}>Cost basis, live price, weekly move, YTD path and current location inside the 52-week range.</p></div><span className="tag">{holdings.length} open positions</span></div>
 <div className="table-wrap" style={{marginTop:12}}><table className="tbl"><thead><tr><th>Ticker</th><th className="num">Avg cost</th><th className="num">Current</th><th className="num">vs cost</th><th className="num">1W</th><th>YTD</th><th>52W range</th><th className="num">Weight</th></tr></thead><tbody>{holdings.map(h=>{const m=market[h.ticker],price=m?.price??null,vs=price!=null&&h.avg_cost>0?(price/h.avg_cost-1)*100:null,mv=(price??h.avg_cost)*h.shares,w=nav?mv/nav*100:0;return <tr key={h.ticker}><td><strong>{h.ticker}</strong><br/><span className="muted" style={{fontSize:10.5}}>{m?.asOf??"—"}</span></td><td className="num">{money(h.avg_cost)}</td><td className="num"><strong>{price==null?"—":money(price)}</strong></td><td className={`num ${vs==null?"muted":vs>=0?"pos":"neg"}`}>{pc(vs)}</td><td className={`num ${m?.change1w==null?"muted":m.change1w>=0?"pos":"neg"}`}>{pc(m?.change1w??null)}</td><td style={{minWidth:150}}><Spark points={m?.ytdSeries??[]} positive={(m?.ytdChangePct??0)>=0}/><div className={m?.ytdChangePct==null?"muted":m.ytdChangePct>=0?"pos":"neg"} style={{fontSize:10.5,marginTop:2}}>YTD {pc(m?.ytdChangePct??null)}</div></td><td style={{minWidth:210}}><Range low={m?.low52??null} high={m?.high52??null} pos={m?.pos52??null} price={price}/></td><td className="num">{w.toFixed(1)}%</td></tr>})}</tbody></table></div></div>
}
function Spark({points,positive}:{points:any[];positive:boolean}){if(points.length<2)return <span className="muted">—</span>;const vals=points.map(p=>p.close),lo=Math.min(...vals),hi=Math.max(...vals),w=140,h=36,span=Math.max(.0001,hi-lo),d=vals.map((v,i)=>`${i?"L":"M"}${(i/(vals.length-1))*w},${h-((v-lo)/span)*h}`).join(" ");return <svg width={w} height={h} viewBox={`0 0 ${w} ${h}`} role="img" aria-label="YTD price sparkline"><path d={d} fill="none" stroke={positive?"currentColor":"currentColor"} strokeWidth="2" className={positive?"pos":"neg"}/></svg>}
function Range({low,high,pos,price}:{low:number|null;high:number|null;pos:number|null;price:number|null}){return <div><div style={{display:"flex",justifyContent:"space-between",fontSize:10.5}}><span className="muted">{low==null?"—":money(low)}</span><strong>{pos==null?"—":`${pos.toFixed(0)}%`}</strong><span className="muted">{high==null?"—":money(high)}</span></div><div style={{height:7,borderRadius:999,background:"rgba(255,255,255,.08)",position:"relative",marginTop:6}}>{pos!=null&&<span style={{position:"absolute",left:`calc(${pos}% - 5px)`,top:-2,width:11,height:11,borderRadius:"50%",background:"currentColor"}}/>}</div><div className="muted" style={{fontSize:10,marginTop:4}}>{price==null?"No current price":pos==null?"52W history unavailable":pos>=85?"Near 52W high":pos<=15?"Near 52W low":"Inside 52W range"}</div></div>}
