"use client";

import{useMemo,useState}from"react";
import type{AppLang}from"../page";
import MeetingMemoryTimeline from"./MeetingMemoryTimeline";
import styles from"./InvestmentCommitteeCycle.module.css";

type Vote="APPROVE"|"CAUTION"|"REJECT"|"VETO";
type Proposal={ticker:string;action:"OPEN NEW"|"ADD EXISTING"|"TRIM"|"EXIT";amount:number;weight:number|null;reason:string;score:number|null;isNew:boolean;currentPrice:number|null;targetPrice:number|null;fundingSource:string};
type Opinion={desk:string;vote:Vote;comment:string};
type Resolution={proposal:Proposal;opinions:Opinion[];approved:boolean;vetoed:boolean;yes:number;no:number;policy:string[]};
type Ticket={id:string;proposal:Proposal;status:"PENDING_HUMAN"|"RECORDING"|"RECORDED"|"MANUAL_REQUIRED"|"FAILED";message?:string};

const tr=(l:AppLang,en:string,th:string)=>l==="th"?th:en;
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const txt=(...v:any[])=>v.find(x=>typeof x==="string"&&x.trim()) as string|undefined;
const usd=(v:any)=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(v)||0);
async function read(path:string,init?:RequestInit){const r=await fetch(path,{cache:"no-store",...init});let body:any={};try{body=await r.json()}catch{}if(!r.ok)throw new Error(body.error??`${path}: HTTP ${r.status}`);return body}
function holdingValue(h:any){return num(h?.market_value??h?.marketValue??h?.current_value??h?.currentValue)??((num(h?.shares)??0)*(num(h?.current_price??h?.currentPrice??h?.price??h?.avg_cost)??0))}
function healthScore(holdings:any[],nav:number,reserve:number,target:number){const vals=holdings.map(holdingValue),total=nav||vals.reduce((a,b)=>a+b,0),weights=vals.map(v=>total?v/total*100:0),max=Math.max(0,...weights);const diversity=Math.min(100,holdings.length*6),concentration=Math.max(20,100-Math.max(0,max-10)*4),liquidity=Math.max(30,100-Math.abs(reserve-target)*5),covered=holdings.filter(h=>num(h?.current_price??h?.price)!=null&&num(h?.avg_cost)!=null).length,data=holdings.length?Math.max(45,covered/holdings.length*100):50;return Math.round(diversity*.25+concentration*.3+liquidity*.25+data*.2)}

function opinions(p:Proposal,ctx:any):Opinion[]{const regime=String(ctx.regime).toUpperCase(),score=p.score??60,pct=p.weight??(ctx.nav?p.amount/ctx.nav*100:0),isSell=p.action==="TRIM"||p.action==="EXIT";return[
 {desk:"Macro",vote:regime.includes("RISK-OFF")&&!isSell?"CAUTION":"APPROVE",comment:regime.includes("RISK-OFF")&&!isSell?"Defensive regime: reduce deployment size.":"Action is compatible with the current regime."},
 {desk:"Portfolio",vote:"APPROVE",comment:isSell?"Reduces concentration or releases capital.":p.isNew?"Adds a distinct approved exposure.":"Fits the target allocation."},
 {desk:"Research",vote:isSell?"APPROVE":score>=80?"APPROVE":score>=65?"CAUTION":"REJECT",comment:isSell?"Portfolio review supports the reduction.":`Research conviction ${score}/100.`},
 {desk:"Valuation",vote:isSell||!p.targetPrice||!p.currentPrice||p.targetPrice>p.currentPrice?"APPROVE":"CAUTION",comment:p.targetPrice?`Current ${usd(p.currentPrice)} vs target ${usd(p.targetPrice)}.`:"Final valuation check required."},
 {desk:"Risk",vote:pct>10?"VETO":pct>8?"CAUTION":"APPROVE",comment:pct>10?"Position exceeds the 10% hard limit.":"Sizing remains inside policy."},
 {desk:"Treasury",vote:ctx.fundingGap>1&&!isSell?"VETO":"APPROVE",comment:ctx.fundingGap>1&&!isSell?`Package funding gap ${usd(ctx.fundingGap)}.`:`Funding source: ${p.fundingSource}.`},
 {desk:"Compliance",vote:"APPROVE",comment:"Human approval, memory record and reconciliation are mandatory."}
]}

export default function InvestmentCommitteeCycle({lang,onExecuted}:{lang:AppLang;onExecuted?:()=>void}){
 const[running,setRunning]=useState(false),[phase,setPhase]=useState(0),[data,setData]=useState<any>(null),[error,setError]=useState<string|null>(null),[tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState<Record<string,boolean>>({}),[memoryRefresh,setMemoryRefresh]=useState(0),[meetingId,setMeetingId]=useState<string|null>(null);
 const resolutions=useMemo<Resolution[]>(()=>!data?[]:data.proposals.map((p:Proposal)=>{const policy:string[]=[];const proposed=p.weight??(data.nav?p.amount/data.nav*100:0);if(proposed>10)policy.push("MAX_POSITION_10");if((p.action==="OPEN NEW"||p.action==="ADD EXISTING")&&data.reserveAfter<15)policy.push("CASH_FLOOR_15");const os=opinions(p,data),vetoed=os.some(x=>x.vote==="VETO")||policy.length>0,yes=os.filter(x=>x.vote==="APPROVE").length,no=os.filter(x=>x.vote==="REJECT"||x.vote==="VETO").length;return{proposal:p,opinions:os,vetoed,yes,no,policy,approved:!vetoed&&yes>=4&&no<=1}}),[data]);
 const approved=resolutions.filter(x=>x.approved),chosen=approved.filter(x=>selected[`${x.proposal.action}:${x.proposal.ticker}`]!==false);

 async function convene(){setRunning(true);setError(null);setData(null);setTickets([]);setMeetingId(null);setPhase(1);try{
  const memory=await read("/api/committee-memory?limit=1").catch(()=>({latest:null}));const macro=await read("/api/macro/intelligence");setPhase(2);
  const portfolio=await read("/api/portfolio"),analytics=await read("/api/portfolio/analytics").catch(()=>({})),intel=await read("/api/team",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"valuation"})}).catch(()=>({plans:[]}));setPhase(3);
  const optimizer=await read("/api/portfolio/optimizer").catch(()=>({proposals:[],portfolio:{}})),opps=await read("/api/portfolio/opportunity-allocation").catch(()=>({allocations:[]})),cash=await read("/api/portfolio/cash-buffer").catch(()=>({}));setPhase(4);
  const holdings=(portfolio.holdings??[]).filter((h:any)=>!h.closed_at),held=new Set(holdings.map((h:any)=>String(h.ticker).toUpperCase())),nav=num(cash.totalNav??optimizer.portfolio?.nav)??holdings.reduce((s:number,h:any)=>s+holdingValue(h),0),reserve=num(cash.bufferPct??optimizer.portfolio?.bufferPct)??0,target=num(cash.targetPct)??15,excess=Math.max(0,num(cash.gapValue)??0),reserveTicker=held.has("SGOV")?"SGOV":held.has("BIL")?"BIL":held.has("SHV")?"SHV":null;
  const proposals:Proposal[]=[];
  for(const p of optimizer.proposals??[]){const ticker=String(p.ticker??"").toUpperCase(),a=String(p.action??"").toUpperCase();if(!ticker||(!a.includes("TRIM")&&!a.includes("EXIT")))continue;proposals.push({ticker,action:a.includes("EXIT")?"EXIT":"TRIM",amount:Math.abs(num(p.capitalUsd)??0),weight:num(p.targetWeightPct),reason:txt(p.reason)??"Portfolio risk-control proposal.",score:num(p.score),isNew:false,currentPrice:num(p.currentPrice),targetPrice:num(p.targetPrice),fundingSource:`PROCEEDS FROM ${ticker}`})}
  for(const p of opps.allocations??[]){const ticker=String(p.ticker??"").toUpperCase(),amount=num(p.approvedCapitalUsd)??0;if(!ticker||amount<=0)continue;proposals.push({ticker,action:held.has(ticker)?"ADD EXISTING":"OPEN NEW",amount,weight:num(p.proposedWeightPct),reason:txt(p.thesis,p.reason)??"Research candidate cleared the evidence gates.",score:num(p.conviction),isNew:!held.has(ticker),currentPrice:num(p.currentPrice),targetPrice:num(p.targetPrice),fundingSource:reserveTicker?`TRIM ${reserveTicker}`:"CASH RESERVE EXCESS"})}
  const unique=Array.from(new Map(proposals.map(p=>[`${p.action}:${p.ticker}`,p])).values()),sellFunding=unique.filter(p=>p.action==="TRIM"||p.action==="EXIT").reduce((s,p)=>s+p.amount,0),buyNeed=unique.filter(p=>p.action==="OPEN NEW"||p.action==="ADD EXISTING").reduce((s,p)=>s+p.amount,0),available=excess+sellFunding,gap=Math.max(0,buyNeed-available),reserveAfter=nav>0?Math.max(0,(reserve/100*nav+sellFunding-buyNeed)/nav*100):reserve;
  const reports=(intel.plans??[]).map((p:any)=>({ticker:String(p.ticker??"").toUpperCase(),status:String(p.ticker).toUpperCase()===reserveTicker&&excess>0?"FUNDING SOURCE":["ADD","TRIM","EXIT","EXIT REVIEW"].includes(String(p.action).toUpperCase())?"REVIEW":"HOLD",weight:num(p.weightPct),fairValue:num(p.fairValue),reason:txt(p.valuationNote,p.reasons?.[0])??"Monitoring only; no trade authority outside committee resolution."})).filter((x:any)=>x.ticker);
  const apiHealth=num(analytics.healthScore??analytics.portfolioHealthScore),health=apiHealth&&apiHealth>0?Math.round(apiHealth):healthScore(holdings,nav,reserve,target);
  const payload={previous:memory.latest,regime:txt(cash.regime?.classification,macro.regime?.classification,macro.classification)??"NEUTRAL",macroScore:num(macro.regime?.score??macro.score)??50,sentiment:txt(macro.sentiment?.label,macro.outlook?.stance)??"Mixed",nav,reserve,reserveTarget:target,reserveAfter,excess,sellFunding,buyNeed,fundingAvailable:available,fundingGap:gap,fundingSource:reserveTicker?`TRIM ${reserveTicker} up to ${usd(excess)}`:`CASH EXCESS ${usd(excess)}`,holdingsCount:holdings.length,health,risk:txt(analytics.riskLabel)??"MONITOR",holdings:reports,portfolioBefore:{nav,reserve,health,holdingsCount:holdings.length},proposals:unique};setData(payload);const defaults:Object={};unique.forEach(p=>(defaults as any)[`${p.action}:${p.ticker}`]=true);setSelected(defaults as Record<string,boolean>);setPhase(5)
 }catch(e:any){setError(e.message??"Meeting failed")}finally{setRunning(false)}}

 async function approvePackage(){if(!data||chosen.length===0)return;const resolution=chosen.map(x=>({...x.proposal,votes:x.opinions,approved:true}));const saved=await read("/api/committee-memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"APPROVED",summary:{health:data.health,fundingNeed:data.buyNeed,fundingAvailable:data.fundingAvailable,policy:"v10.5"},resolution,portfolioBefore:data.portfolioBefore,macro:{regime:data.regime,score:data.macroScore},learning:{continuityFrom:data.previous?.meeting_code??null}})});setMeetingId(saved.meeting?.id??null);setTickets(chosen.map((r,i)=>({id:`${Date.now()}-${i}`,proposal:r.proposal,status:r.proposal.action==="TRIM"||r.proposal.action==="EXIT"?"MANUAL_REQUIRED":"PENDING_HUMAN"})));setMemoryRefresh(x=>x+1)}
 async function recordBuy(id:string){const t=tickets.find(x=>x.id===id);if(!t||t.status!=="PENDING_HUMAN")return;const p=t.proposal;if(!p.currentPrice||p.currentPrice<=0){setTickets(x=>x.map(y=>y.id===id?{...y,status:"FAILED",message:"Live price required"}:y));return}setTickets(x=>x.map(y=>y.id===id?{...y,status:"RECORDING"}:y));try{const shares=p.amount/p.currentPrice;await read("/api/portfolio",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"buy",ticker:p.ticker,shares:shares.toFixed(7),avg_cost:p.currentPrice.toFixed(4),target_price:p.targetPrice?.toFixed(4)??"",thesis:`IC v10.5 ${meetingId??""}: ${p.reason}`,opened_at:new Date().toISOString().slice(0,10),transaction_date:new Date().toISOString().slice(0,10),source:"investment_committee_v10_5"})});setTickets(x=>x.map(y=>y.id===id?{...y,status:"RECORDED",message:`Recorded ${shares.toFixed(4)} shares. Reconcile actual broker value below.`}:y));onExecuted?.();window.dispatchEvent(new Event("sentinel:portfolio-updated"))}catch(e:any){setTickets(x=>x.map(y=>y.id===id?{...y,status:"FAILED",message:e.message}:y))}}

 return <><section className={styles.shell} data-meeting-state={phase}><header className={styles.hero}><div><span>IC-MEETING · SENTINEL v10.5</span><h2>{tr(lang,"Adaptive Portfolio Committee","คณะกรรมการปรับพอร์ตแบบต่อเนื่อง")}</h2><p>{tr(lang,"Previous memory → actual portfolio → multi-item vote → policy/funding checks → human package approval → reconciliation.","ทบทวนมติเดิม → พอร์ตจริง → โหวตหลายรายการ → ตรวจ Policy/เงินทุน → มนุษย์อนุมัติทั้งแพ็กเกจ → Reconciliation")}</p></div><button onClick={convene} disabled={running}>{running?tr(lang,"Meeting in progress…","กำลังประชุม…"):tr(lang,"Convene adaptive meeting","เริ่มประชุมรอบใหม่")}</button></header><div className={styles.timeline}>{["Previous memory","Portfolio + holdings","Candidates","Vote + policy","Execution + memory"].map((x,i)=><div key={x} className={phase>i?styles.complete:phase===i+1?styles.active:""}><b>{i+1}</b><span>{x}</span></div>)}</div>{error&&<div className={styles.error}>{error}</div>}{data&&<>
 <section className={styles.report}><h3>🧠 {tr(lang,"Previous meeting continuity","ความต่อเนื่องจากการประชุมเดิม")}</h3>{data.previous?<div className={styles.metrics}><Metric label="Meeting" value={data.previous.meeting_code}/><Metric label="Status" value={data.previous.status}/><Metric label="Actions" value={String(data.previous.resolution?.length??0)}/><Metric label="Tolerance" value="±10%"/></div>:<p className={styles.empty}>No previous memory — this becomes the baseline meeting.</p>}</section>
 <section className={styles.report}><h3>📊 Portfolio health & funding</h3><div className={styles.metrics}><Metric label="NAV" value={usd(data.nav)}/><Metric label="Health" value={`${data.health}/100`}/><Metric label="Reserve now" value={`${data.reserve.toFixed(1)}%`}/><Metric label="Reserve after" value={`${data.reserveAfter.toFixed(1)}%`}/></div><div className={styles.metrics}><Metric label="Buy need" value={usd(data.buyNeed)}/><Metric label="Sell/excess funding" value={usd(data.fundingAvailable)}/><Metric label="Funding gap" value={usd(data.fundingGap)}/><Metric label="Policy floor" value="15% cash"/></div></section>
 <section className={styles.report}><h3>🧾 Holdings intelligence — report only</h3><div className={styles.proposals}>{data.holdings.map((h:any)=><article key={h.ticker}><header><strong>{h.ticker}</strong><span>{h.status}</span></header><p>{h.reason}</p><small>{h.weight==null?"—":`${h.weight.toFixed(1)}%`} · Fair {usd(h.fairValue)}</small></article>)}</div></section>
 <section className={styles.report}><h3>⚖️ Multi-item portfolio resolution</h3>{resolutions.length===0?<p className={styles.empty}>No actionable proposal.</p>:resolutions.map(r=>{const key=`${r.proposal.action}:${r.proposal.ticker}`;return <article className={styles.ballot} key={key}><header><label style={{display:"flex",gap:8,alignItems:"center"}}><input type="checkbox" checked={selected[key]!==false} disabled={!r.approved} onChange={e=>setSelected(x=>({...x,[key]:e.target.checked}))}/><strong>{r.proposal.action} {r.proposal.ticker} · {usd(r.proposal.amount)}</strong></label><b className={r.approved?styles.approved:styles.rejected}>{r.policy.length?`POLICY BLOCK: ${r.policy.join(", ")}`:r.vetoed?"VETOED":r.approved?"APPROVED":"REVIEW"}</b></header><p>{r.proposal.reason}</p><small>Funding: {r.proposal.fundingSource} · {r.yes}/7 approve</small><div className={styles.votes}>{r.opinions.map(o=><div key={o.desk}><span>{o.desk}</span><b>{o.vote}</b><small>{o.comment}</small></div>)}</div></article>})}</section>
 <section className={styles.execution}><h3>🧾 Human-approved rebalance package</h3><div className={styles.metrics}><Metric label="Approved items" value={String(chosen.length)}/><Metric label="Required" value={usd(chosen.filter(x=>x.proposal.action.includes("NEW")||x.proposal.action.includes("ADD")).reduce((s,x)=>s+x.proposal.amount,0))}/><Metric label="Funding" value={usd(data.fundingAvailable)}/><Metric label="Memory" value="TIERED"/></div>{chosen.length>0&&tickets.length===0&&<button className={styles.createTickets} onClick={approvePackage}>Approve selected package & save meeting</button>}{tickets.map(t=><article className={styles.ticket} key={t.id}><div><strong>{t.proposal.ticker}</strong><span>{t.proposal.action}</span></div><p>{usd(t.proposal.amount)} · {t.proposal.fundingSource}</p><small>{t.message??t.status}</small>{t.status==="PENDING_HUMAN"&&<button onClick={()=>recordBuy(t.id)}>Approve & record buy</button>}</article>)}</section>
 </>}</section><MeetingMemoryTimeline lang={lang} refreshKey={memoryRefresh}/></>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
