"use client";
import{useEffect,useState}from"react";
import type{AppLang}from"../page";

const tr=(l:AppLang,en:string,th:string)=>l==="th"?th:en;
const usd=(v:any)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(v)||0);

export default function MeetingMemoryTimeline({lang,refreshKey=0}:{lang:AppLang;refreshKey?:number}){
 const[rows,setRows]=useState<any[]>([]),[open,setOpen]=useState<string|null>(null),[actual,setActual]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/committee-memory?limit=12",{cache:"no-store"});const j=await r.json();setRows(j.meetings??[])}
 useEffect(()=>{load()},[refreshKey]);
 async function reconcile(m:any){setBusy(true);setMessage("");const trades=(m.resolution??[]).map((p:any)=>({ticker:p.ticker,action:p.action,amount:Number(actual[`${m.id}:${p.action}:${p.ticker}`]??0)})).filter((x:any)=>x.amount>0);const r=await fetch("/api/committee-memory",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"reconcile",id:m.id,actual:trades})});const j=await r.json();setMessage(r.ok?tr(lang,"Reconciliation saved. Actual fills are now the next meeting baseline.","บันทึก Reconciliation แล้ว ยอดซื้อขายจริงจะเป็นฐานของการประชุมรอบถัดไป"):j.error??"Failed");await load();setBusy(false)}
 return <section className="card" style={{marginTop:18}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><h3 className="sub" style={{margin:0}}>🧠 {tr(lang,"Committee Memory & Portfolio Timeline","ความจำการประชุมและ Timeline พอร์ต")}</h3><p className="muted" style={{fontSize:12,lineHeight:1.6}}>{tr(lang,"Compact resolutions and material changes remain; temporary working detail expires. Actual fills within ±10% are accepted as the new baseline.","เก็บมติแบบย่อและการเปลี่ยนแปลงสำคัญ ส่วนรายละเอียดชั่วคราวจะหมดอายุ ยอดจริงที่ต่างไม่เกิน ±10% จะถูกยอมรับเป็นฐานใหม่")}</p></div><button className="btn ghost sm" onClick={load}>Refresh</button></div>{message&&<div className="notice" style={{marginTop:10}}>{message}</div>}{rows.length===0?<p className="muted">{tr(lang,"No archived committee meeting yet.","ยังไม่มีการประชุมที่บันทึกไว้")}</p>:<div style={{display:"grid",gap:10,marginTop:12}}>{rows.map(m=><article key={m.id} style={{border:"1px solid var(--border)",borderRadius:12,padding:12,background:"rgba(8,14,28,.35)"}}><button type="button" onClick={()=>setOpen(open===m.id?null:m.id)} style={{width:"100%",display:"flex",justifyContent:"space-between",gap:10,background:"none",border:0,color:"inherit",textAlign:"left",cursor:"pointer"}}><span><strong>{m.meeting_code}</strong><small className="muted" style={{display:"block",marginTop:4}}>{new Date(m.created_at).toLocaleString()} · {(m.resolution??[]).length} actions</small></span><span className="tag">{m.status}</span></button>{open===m.id&&<div style={{marginTop:12}}><div className="table-wrap"><table className="tbl"><thead><tr><th>Action</th><th>Ticker</th><th className="num">Planned</th><th className="num">Actual</th><th className="num">Variance</th><th>Status</th></tr></thead><tbody>{(m.resolution??[]).map((p:any)=>{const v=(m.variance?.items??[]).find((x:any)=>x.ticker===p.ticker&&x.action===p.action);const key=`${m.id}:${p.action}:${p.ticker}`;return <tr key={key}><td><strong>{p.action}</strong></td><td>{p.ticker}</td><td className="num">{usd(p.amount)}</td><td className="num"><input inputMode="decimal" value={actual[key]??(v?.actualUsd?String(v.actualUsd):"")} onChange={e=>setActual(x=>({...x,[key]:e.target.value}))} placeholder="Actual USD" style={{width:110}}/></td><td className="num">{v?`${v.variancePct>=0?"+":""}${v.variancePct}%`:"—"}</td><td>{v?.status??"PENDING"}</td></tr>})}</tbody></table></div><button className="btn" disabled={busy} onClick={()=>reconcile(m)} style={{marginTop:10}}>{busy?tr(lang,"Saving…","กำลังบันทึก…"):tr(lang,"Reconcile actual execution","เทียบยอดซื้อขายจริง")}</button></div>}</article>)}</div>}</section>
}
