"use client";

import {useEffect,useState} from "react";
import type {AppLang} from "../page";
import TickerInput from "./TickerInput";

const tr=(lang:AppLang,en:string,th:string)=>lang==="th"?th:en;
const money=(value:unknown)=>Number.isFinite(Number(value))?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(value)):"—";
const pct=(value:unknown)=>Number.isFinite(Number(value))?`${Number(value)>=0?"+":""}${Number(value).toFixed(1)}%`:"—";
const num=(value:unknown)=>Number.isFinite(Number(value))?Number(value).toLocaleString(undefined,{maximumFractionDigits:1}):"—";
const text=(value:unknown)=>typeof value==="string"&&value.trim()?value:"—";

type Props={lang:AppLang};

export default function StockAnalysisWorkspaceV12({lang}:Props){
 const[ticker,setTicker]=useState("");const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(false);const[exporting,setExporting]=useState(false);const[error,setError]=useState<string|null>(null);
 useEffect(()=>{const saved=window.localStorage.getItem("sentinel:selectedResearchTicker");if(saved){setTicker(saved);run(undefined,saved)}},[]);
 async function run(event?:React.FormEvent,override?:string){event?.preventDefault();const symbol=(override??ticker).trim().toUpperCase();if(!symbol)return;setLoading(true);setError(null);setData(null);try{const engine=window.localStorage.getItem("sentinel:selectedResearchEngine")??"";const horizon=window.localStorage.getItem("sentinel:selectedResearchHorizon")??"";const query=new URLSearchParams({ticker:symbol});if(engine)query.set("engine",engine);if(horizon)query.set("horizon",horizon);const response=await fetch(`/api/analyze?${query}`,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error??"Analysis failed");setData(json)}catch(reason:unknown){setError(reason instanceof Error?reason.message:"Analysis failed")}finally{setLoading(false)}}
 async function exportWorkbook(){const u=data?.underwriting;if(!u?.exportSheets)return;setExporting(true);try{const response=await fetch("/api/analyze/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker:data.ticker,sheets:u.exportSheets})});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error??"Export failed")}const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`Sentinel_${data.ticker}_Institutional_Research.xlsx`;anchor.click();URL.revokeObjectURL(url)}catch(reason:unknown){setError(reason instanceof Error?reason.message:"Export failed")}finally{setExporting(false)}}
 const u=data?.underwriting;
 return <div className="workspace-stack" data-stock-analysis-version="12.1">
  <section className="card" style={{borderTop:"2px solid var(--accent)"}}><span className="tag">STOCK ANALYSIS · PHASE 2</span><h2 className="section" style={{margin:"12px 0 6px"}}>{tr(lang,"Institutional Equity Research","วิเคราะห์หุ้นระดับสถาบัน")}</h2><p className="muted">{tr(lang,"Integrated sector, company, competitor, financial, earnings, catalyst, forecast, DCF and thesis workflow. Missing evidence stays unavailable instead of being invented.","วิเคราะห์ Sector, Company, Competitor, Financial, Earnings, Catalyst, Forecast, DCF และ Thesis ใน workflow เดียว ข้อมูลที่ไม่มีจะไม่ถูกสร้างขึ้นเอง")}</p><form className="searchbar" onSubmit={run} style={{marginTop:16}}><TickerInput value={ticker} onChange={setTicker} placeholder="QCOM" onSubmitTicker={(value)=>run(undefined,value)}/><button className="btn" disabled={loading}>{loading?tr(lang,"Underwriting…","กำลังวิเคราะห์…"):tr(lang,"Analyze Stock","วิเคราะห์หุ้น")}</button></form>{error&&<div className="err" style={{marginTop:12}}>⚠ {error}</div>}</section>
  {loading&&<section className="card"><span className="spinner"/> {tr(lang,"Building institutional research pack…","กำลังสร้างรายงานวิจัยระดับสถาบัน…")}</section>}
  {u&&<>
   <section className="card" style={{borderTop:`2px solid ${u.decision.includes("BUY")?"var(--green)":u.decision.includes("SELL")||u.decision==="BLOCKED"?"var(--red)":"var(--amber)"}`}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:16,alignItems:"flex-start",flexWrap:"wrap"}}><div><span className="tag">{u.provenance?.receivedFromResearch?`FROM ${String(u.provenance.researchEngine).toUpperCase()} RESEARCH`:"DIRECT ANALYSIS"}</span><h2 className="section" style={{margin:"10px 0 4px"}}>{data.ticker} · {data.data?.overview?.name??""}</h2><p className="muted">{u.sector.sector} · {u.sector.industry}</p></div><div style={{textAlign:"right"}}><div style={{fontSize:34,fontWeight:800}}>{u.decision}</div><div className="muted">{tr(lang,"Conviction","ความเชื่อมั่น")} {u.conviction}/100</div><button className="btn ghost sm" type="button" onClick={exportWorkbook} disabled={exporting} style={{marginTop:10}}>{exporting?"Exporting…":"Export Excel · 7 sheets"}</button></div></div>
    <div className="grid cols-4" style={{marginTop:16}}><Metric label="Price" value={money(u.valuation.price)}/><Metric label="Target" value={money(u.valuation.targetPrice)} sub={pct(u.valuation.upsidePct)}/><Metric label="Evidence" value={`${u.evidence.score}/100`} sub={u.evidence.grade}/><Metric label="Horizon" value={u.horizon}/></div>{u.evidence.hardBlocks?.length>0&&<div className="err" style={{marginTop:14}}><strong>Hard blocks:</strong> {u.evidence.hardBlocks.join(" · ")}</div>}
   </section>

   <Section title="A · Executive Summary"><p className="notice">{u.executive.summary}</p><p><strong>Variant perception:</strong> {u.executive.variantPerception}</p><div className="grid cols-4"><Score title="Quality" value={u.quality.score}/><Score title="Growth" value={u.growth.score}/><Score title="Valuation" value={u.valuation.score}/><Score title="Risk" value={u.risk.score}/></div></Section>

   <Section title="1 · Sector Overview"><div className="grid cols-3"><Metric label="Industry structure" value={u.sector.structure}/><Metric label="Industry cycle" value={u.sector.cycle}/><Metric label="TAM / SAM / SOM" value={`${u.sector.tam??"—"} / ${u.sector.sam??"—"} / ${u.sector.som??"—"}`}/></div><div className="grid cols-2"><ListCard title="Growth drivers" items={u.sector.growthDrivers}/><ListCard title="Regulatory risks" items={u.sector.regulatoryRisks}/></div></Section>

   <Section title="2 · Company Analysis"><p className="notice"><strong>Business model:</strong> {u.company.businessModel}</p><div className="grid cols-3"><ListCard title="Revenue segments" items={u.company.revenueSegments}/><ListCard title="Geographic exposure" items={u.company.geographicExposure}/><ListCard title="Competitive moat" items={u.company.moat}/></div><p><strong>Management quality:</strong> {u.company.managementQuality}</p></Section>

   <Section title="3 · Competitive Analysis"><p className="muted">{u.competitors.basis}</p><DataTable headers={["Ticker","Company","Revenue","Growth","Margin","P/E","Share"]} rows={u.competitors.rows.map((r:any)=>[r.ticker,r.name,num(r.revenue),pct(r.growthPct),pct(r.marginPct),r.pe==null?"—":`${num(r.pe)}x`,pct(r.marketSharePct)])}/></Section>

   <Section title="4 · Financial Analysis"><div className="grid cols-3"><Score title="Financial" value={u.financial.scores.financial}/><Score title="Quality" value={u.financial.scores.quality}/><Score title="Growth" value={u.financial.scores.growth}/></div><p className="notice">{u.financial.debtCommentary}</p><DataTable headers={["Period","Revenue","Gross %","Op %","Net %","FCF","ROIC","ROE","Net debt"]} rows={u.financial.annual.map((r:any)=>[r.period,num(r.revenue),pct(r.grossMarginPct),pct(r.operatingMarginPct),pct(r.netMarginPct),num(r.freeCashFlow),pct(r.roicPct),pct(r.roePct),num(r.netDebt)])}/></Section>

   <Section title="5 · Earnings Analysis"><div className="grid cols-3"><Metric label="Beat rate" value={pct(u.earnings.beatRatePct)}/><Metric label="Guidance trend" value={u.earnings.guidanceTrend}/><Metric label="Quarters reviewed" value={String(u.earnings.quarters.length)}/></div><DataTable headers={["Quarter","Revenue","EPS","Beat/Miss","Guidance","Key KPI"]} rows={u.earnings.quarters.map((r:any)=>[r.period,num(r.revenue),num(r.eps),r.beatMiss,r.guidance,r.kpi])}/></Section>

   <Section title="6 · Catalyst Calendar"><div className="grid cols-4"><Score title="Catalyst score" value={u.catalysts.score}/></div><DataTable headers={["Date","Type","Event","Impact","Evidence"]} rows={u.catalysts.items.map((r:any)=>[r.date??"—",r.type,r.title,r.impact,r.sourceStatus])}/></Section>

   <Section title="7 · Three Statement Model"><div className="grid cols-4"><Metric label="Revenue growth assumption" value={pct(u.forecast.assumptions.revenueGrowthPct)}/><Metric label="Operating margin" value={pct(u.forecast.assumptions.operatingMarginPct)}/><Metric label="Tax rate" value={pct(u.forecast.assumptions.taxRatePct)}/><Metric label="Capex / revenue" value={pct(u.forecast.assumptions.capexPctRevenue)}/></div>{u.forecast.scenarios.map((scenario:any)=><div key={scenario.name} style={{marginTop:14}}><h4>{scenario.name} scenario</h4><DataTable headers={["Year","Revenue","Operating income","Net income","FCF"]} rows={scenario.years.map((r:any)=>[r.year,num(r.revenue),num(r.operatingIncome),num(r.netIncome),num(r.freeCashFlow)])}/></div>)}</Section>

   <Section title="8 · DCF Model"><div className="grid cols-4"><Metric label="Status" value={u.dcf.status}/><Metric label="WACC" value={pct(u.dcf.waccPct)}/><Metric label="Terminal growth" value={pct(u.dcf.terminalGrowthPct)}/><Metric label="DCF fair value" value={money(u.dcf.fairValue)}/></div><DataTable headers={["WACC","Terminal growth","Fair value"]} rows={u.dcf.sensitivity.map((r:any)=>[pct(r.waccPct),pct(r.terminalGrowthPct),money(r.value)])}/></Section>

   <Section title="9 · Thesis Tracker"><Thesis title="Bull Case" text={u.thesis.bull}/><Thesis title="Base Case" text={u.thesis.base}/><Thesis title="Bear Case" text={u.thesis.bear}/><Thesis title="Variant Perception" text={u.thesis.variantPerception}/><div className="grid cols-2"><ListCard title="Key risks" items={u.thesis.keyRisks}/><ListCard title="Monitoring metrics" items={u.thesis.monitoringMetrics}/></div></Section>

   <Section title="10 · Investment Conclusion"><div className="grid cols-4"><Score title="Quality" value={u.quality.score}/><Score title="Growth" value={u.growth.score}/><Score title="Valuation" value={u.valuation.score}/><Score title="Risk" value={u.risk.score}/></div><div className="grid cols-4" style={{marginTop:14}}><Metric label="Final rating" value={u.decision}/><Metric label="Conviction" value={`${u.conviction}/100`}/><Metric label="Entry zone" value={`${money(u.technical.entryZoneLow)} – ${money(u.technical.entryZoneHigh)}`}/><Metric label="Stop loss" value={money(u.technical.stopLoss)}/></div><div className="notice" style={{marginTop:14}}>{tr(lang,"Analysis does not execute trades. BUY or STRONG BUY means eligible for CIO review after human validation.","การวิเคราะห์ไม่ส่งคำสั่งซื้อขาย BUY หรือ STRONG BUY หมายถึงผ่านเข้าสู่การพิจารณาของ CIO หลังมนุษย์ตรวจสอบ")}</div></Section>
  </>}
 </div>
}

function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h3 className="sub">{title}</h3>{children}</section>}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small className="muted">{sub}</small>}</div>}
function Score({title,value}:{title:string;value:number}){return <div className="metric"><span>{title}</span><strong>{value}/100</strong><div style={{height:6,borderRadius:9,background:"rgba(88,111,170,.2)",marginTop:10}}><div style={{width:`${Math.max(0,Math.min(100,value))}%`,height:"100%",borderRadius:9,background:"linear-gradient(90deg,#42d8e8,#8b5cf6)"}}/></div></div>}
function Thesis({title,text}:{title:string;text:string}){return <div className="notice" style={{marginTop:10}}><strong>{title}</strong><p style={{margin:"7px 0 0"}}>{text}</p></div>}
function ListCard({title,items}:{title:string;items:string[]}){return <div className="card" style={{padding:18}}><h4 style={{marginTop:0}}>{title}</h4>{items?.length?items.map((item,index)=><p key={`${item}-${index}`} className="muted">• {item}</p>):<p className="muted">Evidence unavailable</p>}</div>}
function DataTable({headers,rows}:{headers:string[];rows:string[][]}){if(!rows.length)return <div className="notice">Evidence unavailable.</div>;return <div style={{overflowX:"auto"}}><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,i)=><td key={i}>{text(cell)}</td>)}</tr>)}</tbody></table></div>}
