"use client";

import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";
import TickerInput from "./TickerInput";
import StockAnalysisChartsV12 from "./StockAnalysisChartsV12";

const tr=(lang:AppLang,en:string,th:string)=>lang==="th"?th:en;
const money=(v:unknown)=>Number.isFinite(Number(v))?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(v)):"—";
const pct=(v:unknown)=>Number.isFinite(Number(v))?`${Number(v)>=0?"+":""}${Number(v).toFixed(1)}%`:"—";
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{maximumFractionDigits:1}):"—";

type Tab="overview"|"financials"|"valuation"|"competitors"|"catalysts"|"risks"|"thesis"|"portfolio";
const TABS:Tab[]=["overview","financials","valuation","competitors","catalysts","risks","thesis","portfolio"];

export default function StockAnalysisDashboardV12({lang}:{lang:AppLang}){
 const[ticker,setTicker]=useState("");const[data,setData]=useState<any>(null);const[holdings,setHoldings]=useState<any[]>([]);const[performance,setPerformance]=useState<any>(null);const[tab,setTab]=useState<Tab>("overview");const[loading,setLoading]=useState(false);const[actionLoading,setActionLoading]=useState("");const[message,setMessage]=useState("");const[error,setError]=useState("");
 useEffect(()=>{const saved=window.localStorage.getItem("sentinel:selectedResearchTicker");if(saved){setTicker(saved);run(saved)}},[]);
 async function run(override?:string){const symbol=(override??ticker).trim().toUpperCase();if(!symbol)return;setLoading(true);setError("");setMessage("");try{const engine=window.localStorage.getItem("sentinel:selectedResearchEngine")??"";const horizon=window.localStorage.getItem("sentinel:selectedResearchHorizon")??"";const q=new URLSearchParams({ticker:symbol});if(engine)q.set("engine",engine);if(horizon)q.set("horizon",horizon);const [analysisRes,portfolioRes,perfRes]=await Promise.all([fetch(`/api/analyze?${q}`,{cache:"no-store"}),fetch("/api/portfolio",{cache:"no-store"}),fetch(`/api/analyze/performance?ticker=${symbol}`,{cache:"no-store"})]);const analysis=await analysisRes.json();if(!analysisRes.ok)throw new Error(analysis.error??"Analysis failed");setData(analysis);if(portfolioRes.ok){const p=await portfolioRes.json();setHoldings(p.holdings??[])}if(perfRes.ok)setPerformance(await perfRes.json());setTab("overview")}catch(reason:unknown){setError(reason instanceof Error?reason.message:"Analysis failed")}finally{setLoading(false)}}
 const u=data?.underwriting;
 const fit=useMemo(()=>portfolioFit(data,holdings),[data,holdings]);
 const committee=useMemo(()=>committeeScores(u,fit),[u,fit]);
 async function queue(action:"WATCHLIST"|"COMMITTEE"){if(!u)return;setActionLoading(action);setMessage("");try{const response=await fetch("/api/analyze/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker:data.ticker,action,rating:u.decision,conviction:u.conviction,payload:{target:u.valuation.targetPrice,entryLow:u.technical.entryZoneLow,entryHigh:u.technical.entryZoneHigh,stopLoss:u.technical.stopLoss,portfolioFit:fit}})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Action failed");setMessage(action==="WATCHLIST"?"Added to Watchlist queue":"Sent to CIO Committee queue")}catch(reason:unknown){setError(reason instanceof Error?reason.message:"Action failed")}finally{setActionLoading("")}}
 async function track(){if(!u)return;setActionLoading("TRACK");try{const response=await fetch("/api/analyze/performance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker:data.ticker,rating:u.decision,entry_price:u.technical.entryZoneHigh??u.valuation.price,target_price:u.valuation.targetPrice,stop_loss:u.technical.stopLoss,conviction:u.conviction})});const body=await response.json();if(!response.ok)throw new Error(body.error??"Tracking failed");setMessage("Analysis added to 30/90/180/365-day performance tracking");const refresh=await fetch(`/api/analyze/performance?ticker=${data.ticker}`,{cache:"no-store"});if(refresh.ok)setPerformance(await refresh.json())}catch(reason:unknown){setError(reason instanceof Error?reason.message:"Tracking failed")}finally{setActionLoading("")}}
 function exportCommittee(){if(!u)return;const blob=new Blob([JSON.stringify({ticker:data.ticker,underwriting:u,portfolioFit:fit,committee},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`Sentinel_${data.ticker}_Committee_Pack.json`;a.click();URL.revokeObjectURL(url)}
 async function exportExcel(){if(!u?.exportSheets)return;const response=await fetch("/api/analyze/export",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker:data.ticker,sheets:u.exportSheets})});if(!response.ok)return setError("Excel export failed");const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`Sentinel_${data.ticker}_Institutional_Research.xlsx`;a.click();URL.revokeObjectURL(url)}
 return <div className="workspace-stack" data-stock-analysis-version="12.2">
  <section className="card" style={{borderTop:"2px solid var(--accent)"}}><span className="tag">STOCK ANALYZE · PHASE 2.2</span><h2 className="section" style={{margin:"10px 0 6px"}}>{tr(lang,"Interactive institutional equity dashboard","แดชบอร์ดวิเคราะห์หุ้นระดับสถาบัน")}</h2><form className="searchbar" onSubmit={event=>{event.preventDefault();run()}}><TickerInput value={ticker} onChange={setTicker} placeholder="MU" onSubmitTicker={run}/><button className="btn" disabled={loading}>{loading?"Analyzing…":"Analyze Stock"}</button></form>{error&&<div className="err" style={{marginTop:10}}>⚠ {error}</div>}{message&&<div className="notice" style={{marginTop:10}}>✓ {message}</div>}</section>
  {loading&&<section className="card"><span className="spinner"/> Building institutional research pack…</section>}
  {u&&<>
   <section className="card" style={{borderTop:`2px solid ${u.decision.includes("BUY")?"var(--green)":u.decision.includes("SELL")||u.decision==="BLOCKED"?"var(--red)":"var(--amber)"}`}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><span className="tag">{u.provenance?.receivedFromResearch?`FROM ${String(u.provenance.researchEngine).toUpperCase()} RESEARCH`:"DIRECT ANALYSIS"}</span><h2 className="section" style={{margin:"8px 0 2px"}}>{data.ticker} · {data.data?.overview?.name??""}</h2><p className="muted">{u.sector.sector} · {u.sector.industry} · {u.horizon}</p></div><div style={{textAlign:"right"}}><div style={{fontSize:34,fontWeight:850}}>{u.decision}</div><div className="muted">Conviction {u.conviction}/100</div></div></div>
    <div className="grid cols-4" style={{marginTop:14}}><Metric label="Current" value={money(u.valuation.price)}/><Metric label="Entry" value={`${money(u.technical.entryZoneLow)}–${money(u.technical.entryZoneHigh)}`}/><Metric label="Stop" value={money(u.technical.stopLoss)}/><Metric label="Target" value={money(u.valuation.targetPrice)} sub={pct(u.valuation.upsidePct)}/></div>
    <div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:14}}><button className="btn" onClick={()=>queue("WATCHLIST")} disabled={!!actionLoading}>{actionLoading==="WATCHLIST"?"Saving…":"Add Watchlist"}</button><button className="btn" onClick={()=>queue("COMMITTEE")} disabled={!!actionLoading||u.decision==="BLOCKED"}>{actionLoading==="COMMITTEE"?"Sending…":"Send to CIO Committee"}</button><button className="btn ghost" onClick={track} disabled={!!actionLoading}>{actionLoading==="TRACK"?"Tracking…":"Track Performance"}</button><button className="btn ghost" onClick={exportExcel}>Export Excel</button><button className="btn ghost" onClick={()=>window.print()}>Export PDF</button><button className="btn ghost" onClick={exportCommittee}>Committee Pack</button></div>
   </section>
   <StockAnalysisChartsV12 report={u}/>
   <section className="card"><div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:4}}>{TABS.map(id=><button key={id} className={`btn ${tab===id?"":"ghost"}`} onClick={()=>setTab(id)}>{id[0].toUpperCase()+id.slice(1)}</button>)}</div></section>
   {tab==="overview"&&<Overview u={u} performance={performance}/>} {tab==="financials"&&<Financials u={u}/>} {tab==="valuation"&&<Valuation u={u}/>} {tab==="competitors"&&<Competitors u={u}/>} {tab==="catalysts"&&<Catalysts u={u}/>} {tab==="risks"&&<Risks u={u}/>} {tab==="thesis"&&<Thesis u={u}/>} {tab==="portfolio"&&<PortfolioFit fit={fit} committee={committee}/>} 
  </>}
 </div>
}

function Overview({u,performance}:{u:any;performance:any}){return <><section className="card"><h3 className="sub">Executive Summary</h3><p className="notice">{u.executive.summary}</p><div className="grid cols-3"><Gauge title="Financial Health" value={Math.round((u.quality.score+u.growth.score+u.financial.scores.financial)/3)}/><Gauge title="Valuation" value={u.valuation.score}/><Gauge title="Risk" value={100-u.risk.score}/></div></section><section className="card"><h3 className="sub">Analysis Performance</h3><div className="grid cols-4"><Metric label="Tracked" value={String(performance?.summary?.total??0)}/><Metric label="Open" value={String(performance?.summary?.open??0)}/><Metric label="Win rate" value={pct(performance?.summary?.winRatePct)}/><Metric label="Average return" value={pct(performance?.summary?.averageReturnPct)}/></div></section></>}
function Financials({u}:{u:any}){return <section className="card"><h3 className="sub">Financial Health Dashboard</h3><div className="grid cols-4"><Metric label="Quality" value={`${u.quality.score}/100`}/><Metric label="Growth" value={`${u.growth.score}/100`}/><Metric label="ROE" value={pct(u.quality.roePct)}/><Metric label="FCF" value={num(u.quality.freeCashFlow)}/></div><Table headers={["Period","Revenue","Gross %","Op %","Net %","FCF","Net debt"]} rows={u.financial.annual.map((r:any)=>[r.period,num(r.revenue),pct(r.grossMarginPct),pct(r.operatingMarginPct),pct(r.netMarginPct),num(r.freeCashFlow),num(r.netDebt)])}/></section>}
function Valuation({u}:{u:any}){const values=[{label:"Stop",value:u.technical.stopLoss},{label:"Entry",value:u.technical.entryZoneHigh},{label:"Current",value:u.valuation.price},{label:"Bear",value:u.dcf.bearValue},{label:"Base",value:u.dcf.baseValue??u.dcf.fairValue},{label:"Bull",value:u.dcf.bullValue},{label:"Target",value:u.valuation.targetPrice}];return <section className="card"><h3 className="sub">Valuation Range Dashboard</h3><div className="grid cols-4"><Metric label="Fair value" value={money(u.valuation.fairValue)}/><Metric label="Upside" value={pct(u.valuation.upsidePct)}/><Metric label="Margin of safety" value={pct(u.valuation.marginOfSafetyPct)}/><Metric label="WACC" value={pct(u.dcf.waccPct)}/></div><div className="grid cols-4" style={{marginTop:12}}>{values.map(item=><Metric key={item.label} label={item.label} value={money(item.value)}/>)}</div></section>}
function Competitors({u}:{u:any}){return <section className="card"><h3 className="sub">Competitive Comparison</h3><Table headers={["Ticker","Company","Revenue","Growth","Margin","P/E","Share"]} rows={u.competitors.rows.map((r:any)=>[r.ticker,r.name,num(r.revenue),pct(r.growthPct),pct(r.marginPct),r.pe==null?"—":`${num(r.pe)}x`,pct(r.marketSharePct)])}/></section>}
function Catalysts({u}:{u:any}){return <section className="card"><h3 className="sub">Catalyst Calendar</h3><Table headers={["Date","Type","Event","Impact","Evidence"]} rows={u.catalysts.items.map((r:any)=>[r.date??"—",r.type,r.title,r.impact,r.sourceStatus])}/></section>}
function Risks({u}:{u:any}){const components=[{label:"Overall",value:u.risk.score},{label:"Execution",value:Math.min(100,u.risk.score+5)},{label:"Valuation",value:100-u.valuation.score},{label:"Macro",value:Math.min(100,u.risk.score+10)},{label:"Competition",value:Math.max(0,u.risk.score-5)}];return <section className="card"><h3 className="sub">Risk Dashboard</h3><div className="grid cols-3">{components.map(item=><Gauge key={item.label} title={item.label} value={item.value}/>)}</div><List title="Key risks" items={u.risk.items}/><List title="Kill criteria" items={u.risk.killCriteria}/></section>}
function Thesis({u}:{u:any}){return <section className="card"><h3 className="sub">Thesis Tracker</h3><Note title="Bull Case" text={u.thesis.bull}/><Note title="Base Case" text={u.thesis.base}/><Note title="Bear Case" text={u.thesis.bear}/><Note title="Variant Perception" text={u.thesis.variantPerception}/><List title="Monitoring metrics" items={u.thesis.monitoringMetrics}/></section>}
function PortfolioFit({fit,committee}:{fit:any;committee:any}){return <><section className="card"><h3 className="sub">Portfolio Fit Engine</h3><div className="grid cols-4"><Metric label="Current sector weight" value={pct(fit.currentSectorWeightPct)}/><Metric label="After proposed buy" value={pct(fit.postTradeSectorWeightPct)}/><Metric label="Existing holding" value={fit.existingHolding?"YES":"NO"}/><Metric label="Recommendation" value={fit.recommendation}/></div><p className="notice">{fit.reason}</p></section><section className="card"><h3 className="sub">Committee Consensus</h3><div className="grid cols-3">{committee.desks.map((desk:any)=><Metric key={desk.name} label={desk.name} value={`${desk.vote} · ${desk.score}/100`}/>)}</div><div className="notice" style={{marginTop:12}}><strong>Consensus:</strong> {committee.consensus} · {committee.approvalPct.toFixed(0)}%</div></section></>}
function portfolioFit(data:any,holdings:any[]){if(!data?.underwriting)return{currentSectorWeightPct:0,postTradeSectorWeightPct:0,existingHolding:false,recommendation:"WAIT",reason:"Analyze a stock first."};const u=data.underwriting;const sector=String(u.sector.sector??"");const values=holdings.map(row=>({ticker:String(row.ticker??"").toUpperCase(),sector:String(row.sector??""),value:Number(row.market_value??row.current_value??(Number(row.shares??0)*Number(row.current_price??row.avg_cost??0)))||0}));const nav=values.reduce((s,r)=>s+r.value,0);const sectorValue=values.filter(r=>r.sector===sector).reduce((s,r)=>s+r.value,0);const proposed=Math.max(nav*.03,Number(u.technical.entryZoneHigh??u.valuation.price??0));const current=nav?sectorValue/nav*100:0;const post=nav+proposed?(sectorValue+proposed)/(nav+proposed)*100:current;const existing=values.some(r=>r.ticker===String(data.ticker).toUpperCase());let recommendation="FIT";let reason="Adds a controlled position without breaching the provisional 35% sector concentration threshold.";if(existing){recommendation="ADD REVIEW";reason="Ticker already exists in Holdings; committee should review target weight before adding."}if(post>35){recommendation="WAIT";reason="Proposed position would push sector concentration above the provisional 35% limit."}if(u.risk.score>70){recommendation="WAIT";reason="Risk score is too high for automatic committee promotion."}return{currentSectorWeightPct:current,postTradeSectorWeightPct:post,existingHolding:existing,recommendation,reason}}
function committeeScores(u:any,fit:any){if(!u)return{desks:[],consensus:"HOLD",approvalPct:0};const desks=[{name:"Research",score:u.conviction},{name:"Quality",score:u.quality.score},{name:"Valuation",score:u.valuation.score},{name:"Risk",score:100-u.risk.score},{name:"Portfolio",score:fit.recommendation==="FIT"?80:fit.recommendation==="ADD REVIEW"?60:35},{name:"Data",score:u.evidence.score}].map(d=>({...d,vote:d.score>=70?"BUY":d.score>=50?"HOLD":"REJECT"}));const approval=desks.filter(d=>d.vote==="BUY").length/desks.length*100;return{desks,approvalPct:approval,consensus:approval>=67?"BUY":approval>=40?"HOLD":"REJECT"}}
function Metric({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small className="muted">{sub}</small>}</div>}
function Gauge({title,value}:{title:string;value:number}){const score=Math.max(0,Math.min(100,Number(value)||0));return <div className="card" style={{padding:16,textAlign:"center"}}><div style={{width:112,height:112,borderRadius:"50%",margin:"0 auto",display:"grid",placeItems:"center",background:`conic-gradient(var(--accent) ${score*3.6}deg,rgba(100,120,170,.18) 0)`}}><div style={{width:82,height:82,borderRadius:"50%",background:"var(--panel)",display:"grid",placeItems:"center",fontSize:24,fontWeight:800}}>{Math.round(score)}</div></div><strong style={{display:"block",marginTop:10}}>{title}</strong></div>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){if(!rows.length)return <div className="notice">Evidence unavailable.</div>;return <div style={{overflowX:"auto",marginTop:12}}><table className="table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function Note({title,text}:{title:string;text:string}){return <div className="notice" style={{marginTop:10}}><strong>{title}</strong><p style={{margin:"7px 0 0"}}>{text}</p></div>}
function List({title,items}:{title:string;items:string[]}){return <div style={{marginTop:14}}><strong>{title}</strong>{items?.length?items.map((item,index)=><p className="muted" key={`${item}-${index}`}>• {item}</p>):<p className="muted">Evidence unavailable</p>}</div>}
