"use client";

import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";

type Stage="RESEARCH"|"WATCH"|"READY"|"COMMITTEE"|"PROMOTED"|"REJECTED"|"ARCHIVED";
type WatchRow={id:string;ticker:string;reason?:string|null;alert_price?:number|null;target_price?:number|null;stop_price?:number|null;entry_price?:number|null;source?:string|null;created_at?:string|null};
type SymbolHit={ticker:string;name:string;type?:string;exchange?:string};
const stages:Stage[]=["RESEARCH","WATCH","READY","COMMITTEE","PROMOTED","REJECTED","ARCHIVED"];
const stageKey=(ticker:string)=>`sentinel:watchlist-stage:${ticker.toUpperCase()}`;
const money=(v:any)=>Number.isFinite(Number(v))?`$${Number(v).toLocaleString("en-US",{maximumFractionDigits:2})}`:"—";

export default function WatchlistIntelligenceV14({lang,onNavigate}:{lang:AppLang;onNavigate:(id:string)=>void}){
 const t=(en:string,th:string)=>lang==="th"?th:en;
 const[rows,setRows]=useState<WatchRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const[query,setQuery]=useState("");const[hits,setHits]=useState<SymbolHit[]>([]);const[searching,setSearching]=useState(false);const[mutating,setMutating]=useState<string|null>(null);const[filter,setFilter]=useState<"ALL"|Stage>("ALL");const[stageMap,setStageMap]=useState<Record<string,Stage>>({});
 const stageOf=(ticker:string):Stage=>stageMap[ticker.toUpperCase()]??"RESEARCH";
 const setStage=(ticker:string,stage:Stage)=>{localStorage.setItem(stageKey(ticker),stage);setStageMap(x=>({...x,[ticker.toUpperCase()]:stage}))};
 const load=async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/watchlist",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error??"Watchlist unavailable");const list=Array.isArray(j.watchlist)?j.watchlist:[];setRows(list);const m:Record<string,Stage>={};for(const row of list){const s=localStorage.getItem(stageKey(row.ticker)) as Stage|null;m[row.ticker.toUpperCase()]=stages.includes(s as Stage)?s as Stage:"RESEARCH"}setStageMap(m)}catch(e){setError(e instanceof Error?e.message:"Watchlist unavailable")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const q=query.trim();if(!q){setHits([]);return}let dead=false;const timer=setTimeout(async()=>{setSearching(true);try{const r=await fetch(`/api/symbols?q=${encodeURIComponent(q)}&limit=8`,{cache:"no-store"});const j=await r.json();if(!dead)setHits(Array.isArray(j.results)?j.results:[])}catch{if(!dead)setHits([])}finally{if(!dead)setSearching(false)}},250);return()=>{dead=true;clearTimeout(timer)}},[query]);
 const tracked=useMemo(()=>new Set(rows.map(r=>r.ticker.toUpperCase())),[rows]);
 const visible=useMemo(()=>rows.filter(r=>filter==="ALL"||stageOf(r.ticker)===filter),[rows,filter,stageMap]);
 const counts=useMemo(()=>Object.fromEntries(stages.map(s=>[s,rows.filter(r=>stageOf(r.ticker)===s).length])),[rows,stageMap]);
 const add=async(hit:SymbolHit)=>{setMutating(hit.ticker);setError(null);try{const r=await fetch("/api/watchlist",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticker:hit.ticker,reason:hit.name?`Research candidate · ${hit.name}`:"Research candidate",source:"watchlist-v14-intake"})});const j=await r.json();if(!r.ok)throw new Error(j.error??"Unable to add ticker");setStage(hit.ticker,"RESEARCH");setQuery("");setHits([]);await load()}catch(e){setError(e instanceof Error?e.message:"Unable to add ticker")}finally{setMutating(null)}};
 const remove=async(row:WatchRow)=>{setMutating(row.ticker);setError(null);try{const r=await fetch(`/api/watchlist?id=${encodeURIComponent(row.id)}`,{method:"DELETE"});const j=await r.json();if(!r.ok)throw new Error(j.error??"Unable to remove ticker");localStorage.removeItem(stageKey(row.ticker));await load()}catch(e){setError(e instanceof Error?e.message:"Unable to remove ticker")}finally{setMutating(null)}};
 const analyze=(ticker:string)=>{localStorage.setItem("sentinel:selectedResearchTicker",ticker);onNavigate("analyze")};
 return <section className="card" data-watchlist-version="14.0" style={{borderTop:"2px solid var(--accent)"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><span className="tag">WATCHLIST INTELLIGENCE · V14</span><h3 className="sub" style={{margin:"10px 0 4px"}}>{t("Candidate research & promotion pipeline","ระบบติดตาม วิจัย และเลื่อนสถานะหุ้น")}</h3><p className="muted" style={{margin:0,maxWidth:760}}>{t("Every stock enters as RESEARCH. Promotion is explicit: Research → Watch → Ready → Committee → Promoted. Nothing is auto-promoted or auto-bought.","หุ้นทุกตัวเริ่มที่ RESEARCH และต้องเลื่อนสถานะอย่างชัดเจน: Research → Watch → Ready → Committee → Promoted ไม่มีการส่งเข้าพอร์ตหรือซื้ออัตโนมัติ")}</p></div><button className="btn ghost sm" onClick={()=>void load()}>Refresh</button></div>
  <div className="grid cols-4" style={{marginTop:14}}><Metric label="Tracked" value={String(rows.length)}/><Metric label="Research" value={String(counts.RESEARCH??0)}/><Metric label="Ready" value={String(counts.READY??0)}/><Metric label="Committee" value={String(counts.COMMITTEE??0)}/></div>
  <div className="searchbar" style={{marginTop:14}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t("Add ticker or company to research queue","เพิ่ม ticker หรือชื่อบริษัทเข้า Research Queue")}/><span className="tag">LIVE SYMBOL SEARCH</span></div>
  {!!query.trim()&&<div className="card" style={{marginTop:8,padding:8}}>{searching?<div className="muted" style={{padding:8}}>{t("Searching market…","กำลังค้นหาตลาด…")}</div>:hits.length?hits.map(h=><div key={`${h.ticker}-${h.exchange??""}`} style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",padding:"9px 8px",borderBottom:"1px solid var(--line)"}}><div><strong>{h.ticker}</strong> <span className="muted">· {h.name}</span><br/><small className="muted">{[h.type,h.exchange].filter(Boolean).join(" · ")}</small></div>{tracked.has(h.ticker.toUpperCase())?<span className="tag">TRACKED · {stageOf(h.ticker)}</span>:<button className="btn ghost sm" disabled={mutating===h.ticker} onClick={()=>void add(h)}>{mutating===h.ticker?"Adding…":"Add to Research"}</button>}</div>):<div className="notice">{t("No matching market symbol.","ไม่พบหุ้นที่ตรงกัน")}</div>}</div>}
  <div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:14}}><button className={`btn sm ${filter==="ALL"?"":"ghost"}`} onClick={()=>setFilter("ALL")}>ALL · {rows.length}</button>{stages.map(s=><button key={s} className={`btn sm ${filter===s?"":"ghost"}`} onClick={()=>setFilter(s)}>{s} · {counts[s]??0}</button>)}</div>
  {error&&<div className="err" style={{marginTop:12}}>{error}</div>}{loading&&<div className="notice" style={{marginTop:12}}>Loading watchlist…</div>}
  {!loading&&!visible.length?<div className="notice" style={{marginTop:14}}>{t("No candidates in this stage.","ไม่มีหุ้นในสถานะนี้")}</div>:<div style={{display:"grid",gap:10,marginTop:14}}>{visible.map(r=>{const stage=stageOf(r.ticker);const idx=stages.indexOf(stage);const next=idx>=0&&idx<4?stages[idx+1]:null;return <article key={r.id} className="card" style={{margin:0,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10,flexWrap:"wrap"}}><div><div style={{display:"flex",gap:7,alignItems:"center",flexWrap:"wrap"}}><h3 style={{margin:0}}>{r.ticker}</h3><span className="tag">{stage}</span><span className="tag">{r.source??"manual"}</span></div><p className="muted" style={{margin:"7px 0 0",maxWidth:720}}>{r.reason??t("Research candidate","หุ้นรอการวิจัย")}</p></div><div style={{textAlign:"right"}}><small className="muted">TARGET</small><strong style={{display:"block"}}>{money(r.target_price)}</strong></div></div><div style={{display:"flex",gap:7,flexWrap:"wrap",marginTop:12}}><button className="btn ghost sm" onClick={()=>analyze(r.ticker)}>{t("Analyze","วิเคราะห์")}</button>{next&&<button className="btn sm" onClick={()=>setStage(r.ticker,next)}>{t("Promote to","เลื่อนไป")} {next}</button>}{stage!=="REJECTED"&&stage!=="ARCHIVED"&&<button className="btn ghost sm" onClick={()=>setStage(r.ticker,"REJECTED")}>Reject</button>}<button className="btn ghost sm" onClick={()=>setStage(r.ticker,"ARCHIVED")}>Archive</button><button className="btn ghost sm" disabled={mutating===r.ticker} onClick={()=>void remove(r)}>{mutating===r.ticker?"Removing…":"Remove"}</button></div></article>})}</div>}
 </section>
}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
