"use client";

import {useEffect,useMemo,useState} from "react";
import type {AppLang} from "../page";

type ActionRow={id:string;ticker:string;action:string;rating:string|null;conviction:number|null;payload:Record<string,any>;created_at:string};
const finite=(v:unknown):number|null=>Number.isFinite(Number(v))?Number(v):null;
const pct=(v:number|null)=>v==null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`;

export default function WatchlistIntelligenceV13({lang,onNavigate}:{lang:AppLang;onNavigate:(id:string)=>void}){
 const[rows,setRows]=useState<ActionRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[query,setQuery]=useState("");
 const t=(en:string,th:string)=>lang==="th"?th:en;
 const load=async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/analyze/actions",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error??"Watchlist unavailable");setRows((j.actions??[]).filter((x:ActionRow)=>x.action==="WATCHLIST"))}catch(e){setError(e instanceof Error?e.message:"Watchlist unavailable")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>{const q=query.trim().toUpperCase();return rows.filter(r=>!q||r.ticker.includes(q)).map(r=>{const upside=finite(r.payload?.upsidePct??r.payload?.expectedReturnPct);const risk=finite(r.payload?.riskScore);const status=(r.conviction??0)>=75&&upside!=null&&upside>=10?"PROMOTE":risk!=null&&risk>=75?"RISK REVIEW":"MONITOR";const alerts=[upside!=null&&upside>=10?"Upside above 10%":null,(r.conviction??0)>=75?"High conviction":null,r.rating?.includes("BUY")?"Positive rating":null,risk!=null&&risk>=75?"Risk elevated":null].filter(Boolean) as string[];return{...r,upside,risk,status,alerts}})},[rows,query]);
 return <section className="card" data-watchlist-version="13.0" style={{borderTop:"2px solid var(--accent)"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",alignItems:"flex-start"}}><div><span className="tag">WATCHLIST INTELLIGENCE · V13</span><h3 className="sub" style={{margin:"10px 0 4px"}}>{t("Research follow-up and promotion pipeline","ติดตามหุ้นและส่งต่อเข้าสู่กระบวนการลงทุน")}</h3><p className="muted" style={{margin:0}}>{t("Built from explicit Watchlist actions created in Stock Analyze. No stock is promoted automatically.","ใช้รายการ Watchlist ที่ส่งมาจาก Stock Analyze เท่านั้น และไม่เลื่อนสถานะอัตโนมัติ")}</p></div><button className="btn ghost sm" type="button" onClick={load}>Refresh</button></div><div className="searchbar" style={{marginTop:14}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ticker"/><span className="tag">{visible.length} tracked</span></div>{loading&&<div className="notice" style={{marginTop:12}}>Loading watchlist…</div>}{error&&<div className="err" style={{marginTop:12}}>{error}</div>}{!loading&&!visible.length?<div className="notice" style={{marginTop:14}}>{t("No securities have been sent to Watchlist yet.","ยังไม่มีหุ้นถูกส่งเข้า Watchlist")}</div>:<div className="table-wrap" style={{marginTop:14}}><table className="tbl"><thead><tr><th>Ticker</th><th>Rating</th><th className="num">Conviction</th><th className="num">Upside</th><th>Status</th><th>Alerts</th><th>Action</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.ticker}</strong><br/><span className="muted" style={{fontSize:10}}>{new Date(r.created_at).toLocaleDateString()}</span></td><td>{r.rating??"—"}</td><td className="num">{r.conviction==null?"—":`${r.conviction}/100`}</td><td className="num">{pct(r.upside)}</td><td><span className="tag">{r.status}</span></td><td>{r.alerts.length?r.alerts.join(" · "):"No active alert"}</td><td><button className="btn ghost sm" type="button" onClick={()=>{localStorage.setItem("sentinel:selectedResearchTicker",r.ticker);onNavigate("analyze")}}>Open Analyze</button></td></tr>)}</tbody></table></div>}<div className="notice" style={{marginTop:14}}>{t("Promotion to Committee still requires a fresh analysis, verified evidence and human approval.","การส่งเข้าที่ประชุมยังต้องวิเคราะห์ใหม่ ตรวจสอบหลักฐาน และได้รับอนุมัติจากมนุษย์")}</div></section>
}
